part of '../app_strings.dart';

const Map<String, String> _arStrings = {
  'navHome': 'الرئيسية',
  'navWealth': 'الثروة',
  'navPlans': 'الخطط',
  'navSecurity': 'الأمان',
  'navUma': 'UMA',
  'helloLabel': 'مرحبًا،',
  'defaultUserName': 'مستخدم فيرا',
  'totalNetWorth': 'إجمالي صافي الثروة',
  'liveFeed': 'مباشر',
  'syncing': 'مزامنة',
  'thisMonth': 'هذا الشهر',
  'connectedAccounts': 'الحسابات المتصلة',
  'refresh': 'تحديث',
  'syncingDots': 'جارٍ المزامنة...',
  'recentTransactions': 'المعاملات الأخيرة',
  'itemsCount': '{n} عناصر',
  'itemsVisible': 'مرئية',
  'connectBank': 'ربط بنك',
  'homeFirstStepsTitle': 'لنبدأ بأول خطوة',
  'homeFirstStepsBody':
      'تصبح Vera أفضل بكثير بعد وصول أول جزء من بياناتك. استورد كشفًا أو امسح إيصالًا أو أضف بنكًا لتبدأ الشاشة الرئيسية بالحياة.',
  'homeFirstStepsHint':
      'حتى خطوة واحدة من هذه الخطوات تكفي لتفعيل الاقتراحات والأرصدة والتنبيهات الذكية.',
  'connectedAccountsEmptyTitle': 'لا توجد حسابات متصلة بعد',
  'connectedAccountsEmptyBody':
      'عندما تضيف بنكًا، نستطيع متابعة الرصيد على الشاشة الرئيسية وتجهيز إجراءات Uma بسياق أفضل.',
  'addBankTitle': 'إضافة بنك',
  'addBankSubtitle': 'Vera لا تتصل بالبنوك — تضيفها وتتابع الرصيد.',
  'addBankName': 'اسم البنك',
  'addBankLast4': 'آخر 4 أرقام',
  'addBankBalance': 'الرصيد (TL)',
  'addBankColor': 'اللون',
  'addBankSave': 'إضافة بنك',
  'addBankNameRequired': 'اسم البنك مطلوب.',
  'bankAdded': 'تمت إضافة {name}',
  'umaInsight': 'رؤية UMA',
  'umaInsightNoData':
      'Vera لا تعرفك بعد. استورد كشفًا أو امسح إيصالًا أو أضف بنكًا لنبدأ ببناء إرشادات أذكى معًا.',
  'umaInsightNoTransactions':
      'لا توجد معاملات ظاهرة بعد. استورد أول كشف لك أو أضف معاملة يدويًا حتى تفهم Uma نمط إنفاقك.',
  'umaInsightNoPattern':
      'لا يوجد بعد نمط إنفاق واضح لهذه الفترة. كلما وصلت معاملات جديدة ستصبح الرؤية هنا أوضح.',
  'umaInsightTopCategory':
      'أكبر إنفاق كان على {category}: {amount}، أي نحو {share}% من إجمالي الإنفاق المحلل البالغ {total}.',
  'umaInsightImportCta': 'استيراد كشف',
  'umaInsightAddFirstTxnCta': 'أضف أول معاملة',
  'umaInsightDeepenCta': 'عمّقها مع Uma',
  'spent': 'منفق',
  'incoming': 'وارد',
  'creditTitle': 'الائتمان',
  'creditSubtitle': 'اقتراض مبني على دخلك الفعلي.',
  'creditSummaryCardSubtitle': 'احسب القسط الشهري ونسبة الدين',
  'openCredit': 'فتح الائتمان',
  'wealthTitle': 'الثروة',
  'wealthSubtitle': 'أموالك تعمل باستقلالية.',
  'portfolio': 'المحفظة',
  'ytd': 'من بداية السنة',
  'today': 'اليوم',
  'autonomousWealth': 'ثروة ذاتية',
  'profile': 'الملف',
  'moveLimit': 'حد التحويل',
  'approval': 'الموافقة',
  'activityFeed': 'سجل النشاط',
  'explainability': 'القابلية للشرح',
  'undo': 'تراجع',
  'viewDetails': 'عرض التفاصيل',
  'plansTitle': 'الخطط',
  'plansSubtitle': 'اكتشف تسريبات المال الصامتة.',
  'subscriptionIntelligence': 'ذكاء الاشتراكات',
  'detectedPlans': 'الخطط المكتشفة',
  'filterAll': 'الكل',
  'filterAttention': 'تحتاج انتباه',
  'filterUnused': 'غير مستخدمة',
  'filterPriceChanges': 'تغير السعر',
  'askUma': 'اسأل UMA',
  'securityTitle': 'الأمان',
  'securitySubtitle': 'طبقة حمايتك المباشرة.',
  'profileAndSettings': 'الملف والإعدادات',
  'sectionAppearance': 'المظهر والتصميم',
  'sectionAi': 'تفضيلات الذكاء',
  'sectionConnected': 'المؤسسات المتصلة',
  'sectionAccount': 'الحساب',
  'sectionLanguage': 'اللغة',
  'sectionNotifications': 'الإشعارات والأمان',
  'brandPalette': 'لوحة الألوان',
  'mood': 'الوضع',
  'moodLight': 'فاتح',
  'moodDark': 'داكن',
  'vibe': 'الأجواء',
  'vibeCalm': 'هادئ',
  'vibeStandard': 'قياسي',
  'vibeBold': 'جريء',
  'language': 'اللغة',
  'signOut': 'تسجيل الخروج',
  'umaTone': 'نبرة UMA',
  'toneConcise': 'مختصر',
  'toneCoach': 'مدرب',
  'toneProactive': 'استباقي',
  'scanReceipt': 'مسح',
  'scanReceiptTitle': 'مسح إيصال أو شاشة',
  'scanReceiptSubtitle':
      'التقط إيصالاً أو فاتورة أو شاشة بنك وحوّلها إلى معاملة.',
  'scanHint':
      'يقرأ الذكاء الاصطناعي الإيصال، يستخرج الفئة والإجمالي ويطلب موافقتك.',
  'takePhoto': 'التقاط صورة',
  'pickFromGallery': 'اختيار من المعرض',
  'scanReading': 'يقرأ الذكاء الاصطناعي...',
  'scanTotalLabel': 'الإجمالي',
  'scanAgain': 'مسح مجددًا',
  'addToTransactions': 'أضف إلى المعاملات',
  'scanNoTotal': 'تعذرت قراءة المبلغ، أعد المسح.',
  'addedToTransactions': 'تمت الإضافة',
  'parsedByAi': 'ذكاء',
  'parsedFallback': 'تجريبي',
  'scanFallbackWarning':
      'مفتاح Gemini API غير موجود أو تعذر تحليل الإيصال. يُرجى إدخال العملية يدويًا.',
  'scanFallbackAction': 'تعذر على الذكاء القراءة — إدخال يدوي',
  'savingsStoryLabel': 'وفّرت هذا الشهر',
  'savingsStoryFooter': 'بفضل 3 اقتراحات من UMA',
  'savingsStoryDelta': '{pct}% أقل من الشهر الماضي',
  'upcomingBills': 'الفواتير القادمة',
  'billPayViaUma': 'الدفع عبر UMA',
  'daysLeft': 'متبقي {n} يوم',
  'statementImport': 'استيراد كشف',
  'statementImportTitle': 'استيراد كشف الحساب',
  'statementImportSubtitle':
      'حمّل كشفك بصيغة PDF أو صورة، وسيستخرج الذكاء الاصطناعي المعاملات.',
  'pickStatementFile': 'اختر ملفًا (PDF / صورة)',
  'statementImportHint':
      'بنكك يصدّر الكشف بصيغة PDF — تقرؤه Vera دون الحاجة إلى الخدمات المصرفية المفتوحة.',
  'statementParsing': 'يقرأ الذكاء الاصطناعي الكشف...',
  'closingBalance': 'الرصيد الختامي',
  'detectedTransactions': 'تم اكتشاف {n} معاملة',
  'statementImportAgain': 'استيراد مجددًا',
  'statementNoTransactions': 'لم يتم استخراج أي معاملات.',
  'statementImported': 'تمت الإضافة إلى معاملاتك',
  'importToVera': 'استيراد إلى Vera',
  'statementFallbackWarning':
      'مفتاح Gemini API غير موجود أو تعذر تحليل كشف الحساب. يُرجى إدخال المعاملات يدويًا.',
  'statementFallbackAction': 'تعذر على الذكاء القراءة — إدخال يدوي',
  'thisMonthsAiPlan': 'خطة الذكاء الاصطناعي لهذا الشهر',
  'aiPlanFooter': 'اقتراح Uma — طبّقه عبر بنكك، وVera تحتفظ بالسجل.',
  'applyAtBank': 'تطبيق عبر بنكي',
  'securityVeraSideBanner':
      'Vera ليست طبقة الأمان للبنك. ترصد الشذوذ في بياناتك وتنبهك؛ القرار يكون بينك وبنكك.',
  'statusAllClear': 'كل شيء آمن',
  'statusMonitoring': 'مراقبة',
  'securityRecentActivity': 'النشاط الأخير',
  'securityScanning': 'جارٍ المسح...',
  'liveAnomalyDetected': 'تم رصد حالة شاذة',
  'highRiskConfidence': 'مخاطر عالية',
  'reviewedSignal': 'تمت المراجعة',
  'keepBlocked': 'إبقاء الحظر',
  'thisWasMe': 'كنت أنا',
  'emailField': 'البريد الإلكتروني',
  'passwordField': 'كلمة المرور',
  'loginDemoHint':
      'تجربة سريعة بالحساب التجريبي: البريد "{email}"، كلمة المرور "{password}".',
  'umaVoiceStart': 'اسأل بصوتك',
  'umaVoiceStop': 'إيقاف الاستماع',
  'umaVoiceListening': 'أستمع إليك...',
  'umaVoicePermissionDenied':
      'إذن الميكروفون مطلوب. فعّله لتطبيق Vera من إعدادات النظام.',
  'umaVoiceUnavailable': 'التعرف على الصوت غير متاح على هذا الجهاز.',
  'umaToolGoalCreated': 'تم. أنشأت هدفاً بقيمة {target} ليرة.',
  'umaToolBillAdded': 'أضفت فاتورة {name}، استحقاقها بعد {days} يوماً.',
  'umaToolExpenseAdded': 'سجّلت {name} ({amount} ليرة) كمصروف.',
  'umaSuggestionSubs': 'عرض اشتراكاتي',
  'umaSuggestionAnalyze': 'حلّل مصروفاتي',
  'voiceCommandTooltip': 'أمر صوتي',
  'umaAuditTrailTitle': 'سجل التدقيق',
  'umaAuditTrailEmpty': 'لا توجد إجراءات Uma موقّعة بعد.',
  'umaAuditTrailCount': 'تم تسجيل {n} إجراءً موقّعاً على هذا الجهاز.',
  'accountTilePersonal': 'المعلومات الشخصية',
  'accountTileEmail': 'البريد الإلكتروني',
  'accountTileSecurity': 'الأمان وPIN',
  'accountTileStorage': 'سياسة التخزين',
  'accountTileHelp': 'مساعدة ودعم',
  'accountTileHelpValue': 'الأسئلة الشائعة، التواصل',
  'infoDisplayName': 'الاسم المعروض',
  'infoMember': 'العضوية',
  'infoMemberDescription':
      'حساب تجريبي في Vera. عند ربط الواجهة الخلفية ستظهر هنا بيانات العضوية الحقيقية والخطة.',
  'infoEmailLabel': 'البريد الإلكتروني',
  'infoEmailUsage': 'مكان الاستخدام',
  'infoEmailDescription':
      'يُستخدم في الجلسة التجريبية. البيانات تبقى على الجهاز ولا تُرسل لأي خادم.',
  'infoSessionVault': 'خزينة الجلسة',
  'infoSessionVaultDescription':
      'بيانات الجلسة مشفّرة عبر flutter_secure_storage وتُحفظ محلياً على هذا الجهاز فقط.',
  'infoFaceId': 'Face ID',
  'infoFaceIdOn': 'مفعل · يُطلب التحقق البيومتري عند تسجيل الدخول.',
  'infoFaceIdOff': 'مغلق · يكفي كلمة المرور / الدخول التجريبي.',
  'infoFraudAlerts': 'تنبيهات الاحتيال',
  'infoFraudAlertsOn': 'مفعل · يرسل إشعاراً محلياً عند رصد عملية مشبوهة.',
  'infoFraudAlertsOff': 'مغلق · التنبيهات تظهر داخل التطبيق فقط.',
  'infoSyncMode': 'وضع المزامنة',
  'infoLocalData': 'البيانات المحلية',
  'infoLocalDataDescription':
      'فواتير OCR والبنوك المُضافة تُحفظ في SharedPreferences. "تصدير البيانات" ضمن خطط P1.',
  'infoCloudSync': 'مزامنة السحابة',
  'infoCloudSyncActive':
      'مزامنة السحابة مفعّلة. يمكن مزامنة الإيصالات والكشوف والبنوك وإعدادات الملف الشخصي والمعاملات إلى مساحة Vera الخاصة بك.',
  'infoCloudSyncInactive':
      'مزامنة السحابة غير مفعّلة في هذه الجلسة؛ تعمل Vera حالياً محلياً فقط.',
  'fraudAlertTitle': 'Vera • تم حظر معاملة مشبوهة',
  'googleSignInConfigMissing':
      'فشل تسجيل الدخول عبر Google. ربما لم يُسجَّل بصمة SHA-1 للتطبيق في Firebase Console. يجب على المسؤول تحديث إعدادات Firebase.',
  'fraudReasonOutlier':
      'هذا المصروف يفوق وسيطك الأخير {median} ل.ت بـ{multiplier}×. وجدت Vera الفارق مثيراً للانتباه.',
  'fraudNameRoundTransfer': 'تحويل مدوّر · {amount} ل.ت',
  'fraudReasonRoundTransfer':
      'تم رصد مبلغ مدوّر تماماً يفوق 10,000 ل.ت. غالباً تحويل لمستلم؛ أكّد إن كان منك.',
  'fraudNameBurst': '{merchant} · {count}× اليوم نفسه',
  'fraudLocationBurstTotal': 'الإجمالي {total} ل.ت',
  'fraudReasonBurst':
      'نفس التاجر سجّل {count} عملية اليوم. هل كانت محاولة بطاقة متكررة أم تسوّق فعلي؟',
  'helpFaqQ1': 'هل تتصل Vera بمصرفي؟',
  'helpFaqA1':
      'لا. Vera لا تحمل ترخيص AISP/PSP. أنت تجلب البيانات: كشوف PDF، صور إيصالات، لقطات شاشة، أو إدخال يدوي. Vera تجمعها بالذكاء الاصطناعي وتمرر الإجراءات إلى تطبيق مصرفك.',
  'helpFaqQ2': 'أين تُحفظ بياناتي؟',
  'helpFaqA2':
      'بيانات الجلسة الحساسة في flutter_secure_storage (مشفّرة، على الجهاز). إدخالات OCR والبنوك في SharedPreferences. لا خادم ولا مشاركة مع أطراف ثالثة.',
  'helpFaqQ3': 'ماذا يحدث بدون مفتاح Gemini API؟',
  'helpFaqA3':
      'OCR واستيراد الكشوف يعملان عبر بدائل ثابتة (شارة DEMO تظهر). UMA يرد عبر موجه نوايا استدلالي. كل التدفق يعمل — فقط التحليل المباشر بالذكاء الاصطناعي معطل.',
  'helpContact': 'تواصل',
  'demoUser': 'مستخدم تجريبي',
  'umaThinking': 'Uma تفكر...',
  'umaAskHint': 'اسأل Uma...',
  'umaStatusOnline': 'مساعد ذكاء · متصل',
  'onbStep1Title': 'مرحبًا بك في Vera',
  'onbStep1Subtitle':
      'اختر لغتك أولًا. يمكنك تغييرها لاحقًا في الإعدادات في أي وقت.',
  'onbStep2Title': 'اجعلها بطريقتك',
  'onbStep2Subtitle':
      'اختر لوحة الألوان والطابع المناسب. يمكنك تعديل المظهر لاحقًا أيضًا.',
  'onbStep3Title': 'أحضر بياناتك',
  'onbStep3Subtitle':
      'Vera لا تتصل ببنكك مباشرة — أنت تجلب الكشوف، وVera تفهمها. ابدأ الآن أو أضفها لاحقًا.',
  'onbContinue': 'متابعة',
  'onbStart': 'ابدأ Vera',
  'onbSkip': 'تخطي',
  'onbBack': 'رجوع',
  'onbImportNow': 'استيراد كشف',
  'onbScanNow': 'مسح إيصال',
  'onbContinueWithoutImport': 'تابع بدون استيراد',
  'onbPalettePreviewTitle': 'معاينة فورية',
  'onbPalettePreviewBody':
      'اختيارك ينعكس فورًا على البطاقات ولمسات الذكاء الاصطناعي والطابع العام.',
  'onbBlankCanvasTitle': 'لا بأس أن تبدأ فارغًا',
  'onbBlankCanvasBody':
      'إذا أردت، تابع الآن من دون استيراد أي شيء؛ ستوجّهك Vera أيضًا في أول خطوة داخل التطبيق.',
  'goalEmptyPrompt': 'لم تحدد هدفًا بعد — اضغط لإضافته.',
  'goalEmptyHint':
      'حدّد هدفًا أولًا، ثم دع Uma تقدّر كم ينبغي أن تدخر كل شهر بحسب إيقاعك المالي.',
  'goalEmptyCta': 'حدّد هدفًا',
  'goalMonthsLabel': 'خلال كم شهر',
  'goalMonthsOption': '{n} شهر',
  'goalAdviceSummary': '{amount} شهريًا · {months} أشهر',
  'goalCalculate': 'احسب',
  'goalPresetEmergency': 'طوارئ (6 أشهر) · {amount}',
  'goalPresetVacation': 'عطلة (3 أشهر) · {amount}',
  'goalPresetCar': 'سيارة (12 شهر) · {amount}',
  'fieldName': 'الاسم',
  'fieldAmountTl': 'المبلغ (TL)',
  'fieldDate': 'التاريخ',
  'fieldCategory': 'الفئة',
  'fieldDescription': 'الوصف',
  'fieldLabelOptional': 'التسمية (اختياري)',
  'actionAdd': 'إضافة',
  'actionUpdate': 'تحديث',
  'actionDelete': 'حذف',
  'actionManual': 'يدوي',
  'addBillTitle': 'إضافة فاتورة جديدة',
  'editBillTitle': 'تعديل الفاتورة',
  'addBillNameHint': 'مثال: Turk Telekom',
  'dueDateLabel': 'تاريخ الاستحقاق',
  'addBillCta': 'إضافة فاتورة',
  'noTrackedBillsTitle': 'لا توجد فواتير متابَعة بعد',
  'noTrackedBillsBody': 'تذكّرك Vera قبل يوم واحد من تاريخ الدفع.',
  'billKindCard': 'بطاقة',
  'billKindInternet': 'إنترنت',
  'billKindElectric': 'كهرباء',
  'billKindWater': 'مياه',
  'billKindGas': 'غاز',
  'billKindRent': 'إيجار',
  'billKindOther': 'أخرى',
  'addManualTxnTitle': 'إضافة معاملة يدويًا',
  'txnTypeExpense': 'مصروف',
  'txnTypeIncome': 'دخل',
  'addManualTxnNameHint': 'مثال: Migros',
  'aiSuggestionLabel': 'اقتراح Uma',
  'acceptSuggestion': 'قبول',
  'categoryMarket': 'بقالة',
  'categoryFood': 'طعام وشراب',
  'categoryFuel': 'وقود',
  'categoryBill': 'فواتير',
  'categoryHealth': 'صحة',
  'categoryEducation': 'تعليم',
  'categoryEntertainment': 'ترفيه',
  'categoryTransfer': 'تحويل',
  'categorySalary': 'راتب',
  'categorySubscription': 'اشتراك',
  'categoryMusic': 'موسيقى',
  'categoryVideo': 'فيديو',
  'categoryStorage': 'تخزين',
  'categoryDeveloper': 'مطور',
  'categoryAi': 'ذكاء اصطناعي',
  'noTransactionsTitle': 'لا توجد معاملات بعد',
  'noTransactionsBody': 'أضف أول معاملة لك، أو استورد كشفًا، أو امسح إيصالًا.',
  'addHoldingTitle': 'إضافة أصل إلى المحفظة',
  'addHoldingSubtitle':
      'اختر أحد الأنواع أدناه وأدخل قيمته بالليرة. تعيد Uma حساب الأوزان تلقائيًا.',
  'addHoldingHint': 'مثال: THYAO أو XU100 ETF',
  'holdingValueLabel': 'القيمة (TL)',
  'removeHolding': 'إزالة هذا الأصل',
  'noWealthActionsTitle': 'لم تتخذ Uma إجراءً بعد',
  'noWealthActionsBody':
      'عند تفعيل الوضع الذاتي ستظهر التوصيات وحركات إعادة التوازن هنا.',
  'startPortfolioTitle': 'ابدأ ببناء محفظتك',
  'startPortfolioBody':
      'أضف أسهمًا أو ذهبًا أو نقدًا أو أصولًا رقمية. تراقب Uma الانحراف وتكتب اقتراحاتها هنا.',
  'wealthApprovalAuto': 'تلقائي',
  'wealthApprovalHybrid': 'هجين',
  'wealthActionReversed': 'تم التراجع',
  'holdingBucketEquity': 'أسهم',
  'holdingBucketGold': 'ذهب',
  'holdingBucketCash': 'نقد',
  'holdingBucketCrypto': 'كريبتو',
  'holdingBucketFunds': 'صندوق',
  'holdingBucketBonds': 'سندات',
  'subscriptionsAttentionCount': 'هناك {n} خطط تحتاج إلى انتباه في هذه الدورة',
  'noSubscriptionsDetectedTitle': 'لم يتم اكتشاف اشتراكات بعد',
  'noSubscriptionsDetectedBody':
      'استورد كشفًا أو امسح إيصالًا — ستكتشف Vera المدفوعات المتكررة تلقائيًا.',
  'noSubscriptionsForFilterTitle': 'لا توجد اشتراكات مطابقة لهذا الفلتر',
  'noSubscriptionsForFilterBody': 'جرّب فلاتر أخرى.',
  'subsAlertSavingsTitle': 'إمكانات التوفير الشهرية',
  'subsAlertSavingsMessageEmpty':
      'لم يتم اكتشاف اشتراكات بعد. استورد كشفًا أو أضف اشتراكًا يدويًا لتتبعه Vera.',
  'subsAlertSavingsMessageActive':
      'عثرت Vera على اشتراكات يمكنك تجميدها أو خفض باقتها دون التأثير على روتينك.',
  'subsAlertSavingsMetric': 'توفير',
  'subsAlertPriceTitle': 'تم اكتشاف زيادة سعر',
  'subsAlertPriceMessageNone': 'لا توجد قفزات سعر غير معتادة في هذه الدورة.',
  'subsAlertPriceMessageSome':
      'ارتفع سعر خطة واحدة أو أكثر مقارنة بالشهر الماضي.',
  'subsAlertPriceMetric': 'زاد',
  'subsAlertUnusedTitle': 'خطط قليلة الاستخدام',
  'subsAlertUnusedMessageNone': 'كل الاشتراكات تبدو مستخدمة بشكل جيد.',
  'subsAlertUnusedMessageSome':
      'تبدو {n} خطط قليلة الاستخدام وفقًا لنمط نشاطك الأخير.',
  'subsAlertUnusedMetric': 'خامل',
  'subsInsightEmpty': 'تحلل Vera كشوفك أو إيصالاتك وتجمع اشتراكاتك هنا.',
  'subsInsightHealthy':
      'تبدو اشتراكاتك سليمة هذا الشهر. لا يوجد تسرب ادخار عاجل ظاهر.',
  'subsInsightNeedsAttention':
      'لديك {n} اشتراكات تستحق المراجعة. تقدّر Vera أنك قد تستعيد نحو {amount} شهريًا عبر تجميد غير المستخدمة وخفض الباقات الأعلى سعرًا.',
  'subsDetectedFromImport': 'تم اكتشافه من معاملة مستوردة',
  'subsSeenInRecentTransactions': 'ظهر {n}× في المعاملات الأخيرة',
  'subsKnownVendorLabel': 'مزود اشتراك معروف',
  'subsRecommendationDetected':
      'اكتشفت Vera هذا الاشتراك من كشف مستورد. هل ما زلت تستخدمه؟',
  'subsStatusActive': 'نشط',
  'subsStatusPriceUp': 'ارتفع السعر',
  'subsStatusUnused': 'قليل الاستخدام',
  'subsStatusRenewsSoon': 'يتجدد قريبًا',
  'proactiveBadge': 'رصدت Vera',
  'proactiveBillTitle': 'فاتورة {name} تقترب',
  'proactiveBillBody':
      '{amount} · بقي {days} أيام. هل تريد من Uma تجهيز خطة الدفع؟',
  'proactiveBillCta': 'ادفع مع Uma',
  'proactiveBillPrompt': 'ساعدني في دفع فاتورة {name}.',
  'proactivePriceTitle': 'ارتفع سعر {name}',
  'proactivePriceBody': 'زيادة شهرية +{delta}. هل تريد تجميد الاشتراك؟',
  'proactivePriceCta': 'افتح الاشتراكات',
  'proactiveUnusedTitle': '{name} غير مستخدم',
  'proactiveUnusedBody':
      'آخر استخدام: {last}. قد يكون هذا تسربًا ماليًا صامتًا.',
  'proactiveUnusedCta': 'افتح الاشتراكات',
  'proactiveHealthyTitle': 'لا توجد إشارة حرجة حاليًا',
  'proactiveHealthyBody':
      'لا توجد الآن فاتورة عاجلة أو ارتفاع سعر أو اشتراك مهدر بشكل واضح. ومع ذلك يمكن لـ Uma أن تعطيك قراءة سريعة لهذه الفترة إذا أردت.',
  'proactiveHealthyCta': 'دع Uma تراجعها',
  'proactiveEmptyTitle': 'لم تجد Vera إشارة تستحق المتابعة بعد',
  'proactiveEmptyBody':
      'عند استيراد كشف، ستُظهر Vera هنا المدفوعات القادمة والاشتراكات والمخاطر الصغيرة.',
  'proactiveEmptyCta': 'استيراد كشف',
  'securityEmptyTitle': 'لا توجد تنبيهات للمراجعة الآن',
  'securityEmptyBody':
      'يراقب رادار الاحتيال في Vera أجهزتك ومعاملاتك المستوردة بهدوء. إذا حدث شيء فسيظهر هنا.',
  'close': 'إغلاق',
  'categoryOther': 'أخرى',
  'receiptDefaultName': 'إيصال',
  'wealthInsightAddPortfolio':
      'الوضع المستقل متوقف. أضف محفظتك حتى تتمكن Uma من تتبع الانحراف واقتراح الخطوات.',
  'wealthInsightPaused':
      'الوضع المستقل متوقف مؤقتاً. تواصل Vera مراقبة الانحراف لكنها تنتظر موافقتك قبل تحريك أي أموال.',
  'wealthInsightActive':
      'Uma نشطة بسياسة "{profile}". ضمن حد {limit} ليرة شهرياً، نفّذت أو حضّرت {count} تعديلاً على المحفظة.',
  'goalReached': 'لقد وصلت إلى هدفك. يمكنك تحديد هدف جديد الآن.',
  'goalRemainingPlan':
      'لتوفير المبلغ المتبقي {remaining} ليرة خلال {months} شهراً، عليك تخصيص {monthly} ليرة شهرياً.',
  'goalNarrativeNewTarget': 'يمكنك تحديد مبلغ جديد لهدفك.',
  'goalNarrativeNoData':
      'لا توجد بيانات معاملات بعد. استورد كشفاً أو أضف بضع معاملات يدوياً لتقترح Uma خطة مخصصة لك.',
  'goalNarrativeTrim':
      'عليك تخصيص {monthly} ليرة شهرياً. البدء بتخفيضات صغيرة في فئة {topCategory} خيار منطقي.',
  'todayAt': 'اليوم، {time}',
  'loginContinueEmail': 'المتابعة بالبريد الإلكتروني',
  'loginEmailPasswordRequired': 'البريد الإلكتروني وكلمة المرور مطلوبان.',
  'loginFirebaseError': 'فشل تسجيل الدخول عبر Firebase: {code}.',
  'loginFirebaseReadyFooter':
      'Firebase auth متصل. الوضع التجريبي لا يزال متاحاً لتدفقات الـ hackathon.',
  'loginCreateAccount': 'إنشاء حساب',
  'dividerOr': 'أو',
  'signupTitle': 'أنشئ حسابك',
  'signupSubtitleFirebase':
      'أنشئ حسابك — ستتم مزامنة ملفك الشخصي وبياناتك في Vera بأمان.',
  'signupSubtitleLocal':
      'لم يتم إعداد الخادم. سيستمر هذا التدفق في وضع العرض التجريبي على هذا الجهاز.',
  'signupFieldFullName': 'الاسم الكامل',
  'signupFieldEmail': 'البريد الإلكتروني',
  'signupFieldPassword': 'كلمة المرور',
  'signupFieldConfirmPassword': 'تأكيد كلمة المرور',
  'signupErrorNameRequired': 'يرجى إدخال اسمك الكامل.',
  'signupErrorInvalidEmail': 'يرجى إدخال بريد إلكتروني صالح.',
  'signupErrorShortPassword': 'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل.',
  'signupErrorPasswordMismatch': 'كلمات المرور غير متطابقة.',
  'signupErrorAcceptTerms': 'يرجى قبول الشروط للمتابعة.',
  'signupFailedTemplate': 'فشل إنشاء الحساب: {code}.',
  'signupTerms': 'أوافق على شروط Vera وسياسة بيانات العرض التجريبي المحلية.',
  'signupStrengthWeak': 'ضعيفة',
  'signupStrengthMedium': 'متوسطة',
  'signupStrengthStrong': 'قوية',
  'signupCtaCreate': 'تسجيل',
  'signupCtaContinueLocal': 'المتابعة كعرض تجريبي',
  'signupAlreadyHaveAccount': 'هل لديك حساب بالفعل؟ ',
  'signupSignIn': 'تسجيل الدخول',
  'demoSampleLoaded': 'تم تحميل بيانات الحساب التجريبي.',
  'demoBankPrimary': 'بنك Vera — حساب جاري',
  'demoBankSavings': 'بنك Vera — حساب توفير',
  'demoBillCreditCard': 'كشف بطاقة الائتمان',
  'demoBillElectric': 'فاتورة الكهرباء',
  'demoBillInternet': 'فاتورة الإنترنت',
  'demoTxnSalary': 'دفعة الراتب',
  'demoTxnGrocery': 'تسوق البقالة',
  'demoTxnFuel': 'وقود',
  'demoTxnRestaurant': 'مطعم',
  'demoTxnPharmacy': 'صيدلية',
  'demoTxnRent': 'دفعة الإيجار',
  'demoTxnTransfer': 'تحويل — حساب التوفير',
  'demoTxnFamilyIncoming': 'تحويل وارد — العائلة',
  'demoTxnAtm': 'سحب نقدي من الصراف الآلي',
  'deleteAccount': 'حذف الحساب',
  'deleteAccountTile': 'حذف الحساب',
  'deleteAccountTileValue': 'إزالة بيانات السحابة وتسجيل الخروج',
  'deleteAccountDemoTileValue': 'مسح بيانات العرض على هذا الجهاز',
  'deleteAccountTitle': 'هل تريد حذف هذا الحساب؟',
  'deleteAccountBody':
      'سيتم حذف حساب Vera والبيانات المتزامنة وذاكرة التخزين المحلية على هذا الجهاز نهائياً. لا يمكن التراجع عن هذا الإجراء.',
  'deleteAccountDemoBody':
      'سيؤدي هذا إلى مسح حساب العرض وإزالة البيانات المحلية من هذا الجهاز. لا يمكن التراجع عن هذا الإجراء.',
  'deleteAccountConfirm': 'حذف الحساب',
  'deleteAccountCancel': 'إلغاء',
  'deleteAccountProcessing': 'جارٍ حذف الحساب...',
  'deleteAccountDone': 'تم حذف الحساب.',
  'deleteAccountError':
      'تعذر حذف الحساب. يرجى تسجيل الدخول مرة أخرى ثم إعادة المحاولة.',
  'deleteAccountRecentLogin':
      'لأسباب أمنية، يرجى تسجيل الدخول مرة أخرى قبل حذف حسابك.',
  'continueWithGoogle': 'المتابعة باستخدام Google',
  'googleSignInUnavailable':
      'يتطلب تسجيل الدخول عبر Google إعداد Firebase لهذا الإصدار.',
  'bankActionsTitle': 'خيارات البنك',
  'bankActionsCancel': 'إلغاء',
  'bankActionsDelete': 'حذف البنك',
  'bankActionsConfirmTitle': 'حذف هذا البنك؟',
  'bankActionsConfirmBody':
      'سيتم إزالة {name} ولن يُحتسب في الرصيد الإجمالي بعد الآن.',
  'bankDeleted': 'تم حذف {name}',
  'bankActionsFeedNote':
      'هذا البنك يأتي ضمن بيانات العرض ولا يمكن حذفه. يمكنك إزالة البنوك التي أضفتها بنفسك.',
  'billDetailPrompt':
      'فاتورة {name} بقيمة {amount}، متبقي {days} يوماً. ما الذي يجب فعله؟',
  'categoryBudgetLabel': 'إنفاق هذا الشهر',
  'categoryBudgetTopHint': 'الأعلى في {category} · {pct}%',
  'categoryLimitEditTitle': 'حد الفئة',
  'categoryLimitEditSubtitle':
      'حدد ميزانية شهرية لـ{category}. تعرض Vera المتبقي عند كل مصروف.',
  'categoryLimitField': 'الحد الشهري (TL)',
  'categoryLimitSave': 'حفظ',
  'categoryLimitClear': 'إزالة الحد',
  'categoryNoLimit': 'بلا حد',
  'categoryOver': 'تجاوزت بـ{amount}',
  'categoryRemaining': 'متبقي {amount}',
  'creditFieldDebt': 'الالتزامات الشهرية الحالية',
  'creditFieldIncome': 'الدخل الشهري',
  'creditFieldLoanAmount': 'مبلغ القرض',
  'creditFieldTerm': 'المدة',
  'creditLoanSimulation': 'محاكي القرض',
  'creditLoanSimulationSubtitle':
      'اضبط القيم — يتم احتساب القسط الشهري وعبء الدين فوراً.',
  'creditScoreDisclaimer':
      'هذه الصفحة لا تحسب درجة ائتمانية. للحصول على درجة حقيقية، راجع بنكك أو مكتب الائتمان. هنا ترى فقط تقديراً تقريبياً للقسط ونسبة الدين بناءً على القيم التي أدخلتها.',
  'creditTermMonths': '{n} شهراً',
  'creditResultMonthlyPayment': 'القسط الشهري التقديري',
  'creditResultTotalCost': 'إجمالي السداد',
  'creditResultPaymentLoad': 'القسط / الدخل',
  'creditResultDtiAfter': 'نسبة الدين بعد القرض',
  'creditResultGuidance':
      'تفضل البنوك عادةً نسبة دين/دخل تحت 35%. تجاوز 40% يضيّق العروض. للتخطيط فقط.',
  'demoResetTile': 'إعادة ضبط بيانات العرض',
  'demoResetTileValue': 'مسح الواردات والإضافات',
  'demoResetTitle': 'إعادة ضبط بيانات العرض؟',
  'demoResetBody':
      'تعود المعاملات المستوردة والبنوك المضافة وتقدّم الأهداف إلى حالة البداية.',
  'demoResetCancel': 'إلغاء',
  'demoResetConfirm': 'إعادة الضبط',
  'demoResetDone': 'تمت العودة إلى حالة العرض',
  'exportTile': 'تصدير بياناتي',
  'exportTileValue': 'JSON · على الجهاز فقط',
  'exportTitle': 'بيانات Vera الخاصة بك',
  'exportSubtitle':
      'المعاملات المستوردة والبنوك التي أضفتها وأهدافك والاشتراكات المكتشفة. انسخها دون مغادرة الجهاز.',
  'exportCopy': 'نسخ JSON',
  'exportCopied': 'تم النسخ إلى الحافظة',
  'firstScanPending': 'بانتظار أول فحص',
  'firstSyncPending': 'بانتظار أول مزامنة',
  'goalEditTitle': 'تعديل هدفك',
  'goalEditTarget': 'المبلغ المستهدف (TL)',
  'goalEditSaved': 'المُدّخر حتى الآن (TL)',
  'goalEditFooter':
      'Vera تتابع الرصيد؛ وUma تتفقد كل شهر بفكرة جديدة.',
  'goalEditSave': 'حفظ',
  'goalEmergencyFund': 'صندوق الطوارئ',
  'goalEtaMonths': 'باقي {n} شهر',
  'goalEtaReached': 'وصلت إليه 🎯',
  'goalProgress': 'وصلت {pct}%',
  'goalRemaining': 'باقي {amount}',
  'goalsSectionTitle': 'أهدافك',
  'lastScanAt': 'آخر فحص {time}',
  'loginTitle': 'تسجيل الدخول إلى Vera',
  'loginSubtitle':
      'سجّل الدخول بحسابك؛ تفضيلات الملف الشخصي وإجراءات الذكاء تبقى محلية حتى تسجّل الخروج.',
  'loginEmailHint': 'you@vera.app',
  'loginFooter':
      'إذا لم يكن Firebase مهيّأً، سيفشل تسجيل الدخول. راجع ملف .env.',
  'notifTitle': 'الإشعارات',
  'notifSubtitle': '{n} إشارات تراقبها Uma',
  'notifEmpty': 'كل شيء هادئ. Uma لا تزال تراقب بهدوء.',
  'notifBillTitle': 'فاتورة {name} تقترب',
  'notifBillBody': 'القيمة {amount}. ادفع عبر Uma أو بنكك.',
  'notifPriceIncreaseTitle': '{name} رفعت السعر',
  'notifPriceIncreaseBody':
      'شهرياً +{delta} · الآن {price}. يمكنك تجميدها من قسم الخطط.',
  'notifUnusedTitle': '{name} غير مستخدمة',
  'notifUnusedBody':
      'آخر استخدام: {last}. وضعتها Vera كتسرّب صامت.',
  'notifBlockedDefault':
      'وضعت Vera هذه المعاملة كحالة شاذة.',
  'profileAiToneBadge': 'نبرة الذكاء / {tone}',
  'profileAutoApprove': 'حد الموافقة التلقائية',
  'profileAutoApproveOff': 'إيقاف',
  'profileConnectedTitle': '{n} مؤسسات مربوطة',
  'profileConnectedSubtitle':
      'الأرصدة المباشرة تتحدث عبر سياسة المزامنة وذاكرة الخلاصة.',
  'profileConnectedAccount': 'حساب {last4}',
  'profileDailyBriefing': 'إيجاز الذكاء اليومي',
  'profileDailyBriefingSub':
      'ابدأ يومك بصحة الحساب والأنشطة المريبة ونصائح الادخار',
  'profileFaceId': 'إعادة قفل بـFace ID',
  'profileFaceIdSub':
      'طلب التحقق الحيوي قبل الإجراءات الحساسة',
  'profileFraudHigh': 'تنبيهات احتيال عالية الحساسية',
  'profileFraudHighSub':
      'تتيح Vera وضع علامة على أنماط جهاز ودفع غير معتادة في وقت أبكر',
  'profileLiveSync': 'مزامنة مباشرة',
  'profileLiveSyncLive': 'مباشر',
  'profileLiveSyncBalanced': 'متوازن',
  'profileLiveSyncSaver': 'موفر',
  'profileSmartNotif': 'إشعارات ذكية',
  'profileSmartNotifSub':
      'تنبيهات للاحتيال والتجديدات وتغيرات الموافقة',
  'profileVaultTitle': 'خزينة جلسة محمية',
  'profileVaultSubtitle':
      'الهوية محفوظة بشكل منفصل عن التفضيلات المحلية.',
  'profileVaultSignIn': 'تسجيل الدخول',
  'profileVaultProtectedSince': 'محمي منذ',
  'profileVaultThisDevice': 'هذا الجهاز',
  'profileVaultApproval': 'حاجز الموافقة',
  'profileVaultManualOnly': 'يدوي فقط',
  'profileVaultSyncMode': 'وضع المزامنة',
  'profileVaultSyncLive': 'مزامنة مباشرة',
  'profileVaultSyncBalanced': 'مزامنة متوازنة',
  'profileVaultSyncSaver': 'مزامنة موفّرة',
  'securityAccountSection': 'أمان الحساب',
  'securityActiveBody': 'يتابع رادار الاحتيال {n} تنبيهات نشطة.',
  'securityClearBody':
      'لا توجد تنبيهات احتيال غير محلولة في آخر فحص.',
  'securityPillBlocked': 'حُجبت بواسطة الذكاء',
  'securityPillApproved': 'وافقت أنت',
  'securityPillKept': 'بقيت محظورة',
  'securityDecisionKept':
      'أبقيت هذا الحدث محظوراً. سيستمر رادار الاحتيال في معاملة الأنماط المشابهة كخطر مرتفع.',
  'securityDecisionApproved':
      'وسمت هذا الحدث بأنه آمن. سيستخدم رادار الاحتيال هذا الانطباع لتقليل الإنذارات المشابهة الخاطئة.',
  'securityStatBlockedLabel': 'محجوب',
  'securityStatBlockedSub': 'نشط',
  'securityStatReviewedLabel': 'مُراجَع',
  'securityStatReviewedSub': 'هذا الأسبوع',
  'securityStatDevicesLabel': 'الأجهزة',
  'securityStatDevicesSub': 'موثوقة',
  'securityViewReport': 'فتح تقرير UMA',
  'subsRenewalLabel': 'التجديد',
  'subsActivityLabel': 'النشاط',
  'txnDetailWhen': 'الوقت',
  'txnDetailCategory': 'الفئة',
  'txnDetailDirection': 'الاتجاه',
  'txnDetailIncoming': 'وارد',
  'txnDetailOutgoing': 'صادر',
  'txnDetailAskPrompt':
      'ألقِ نظرة على معاملة {name} — هل {amount} طبيعي؟',
  'umaAuditTrailSubtitle':
      'سجل محلي موقّع لردود Uma على هذا الجهاز.',
  'umaAuditTrailEmptyState':
      'لا توجد إجراءات موقّعة بعد. تحدّث مع Uma وسيظهر سجل الثقة هنا.',
  'umaAuditNoteAttached': 'ملاحظة مرفقة',
  'umaAuditActionReplyGenerated': 'تم إنشاء الرد',
  'umaGreeting':
      'مرحباً {name}. قرأت الكشوف التي استوردتها. يمكنني تحليل إنفاقك، وإظهار الاشتراكات غير المستخدمة، ومساعدتك على وضع أهداف ادخار. لا أحرّك أموالاً — عند الحاجة لإجراء، أوجهك إلى تطبيق بنكك.',
  'umaPromptAnalyze': 'حلّل إنفاقي لهذا الشهر.',
  'umaReplyAnalyze':
      'أعلى إنفاقك هذا الشهر في {top} بقيمة {topAmount}. إجمالي الخروج {spending}. يمكننا ضبط حدود لكل فئة إن أردت.',
  'umaReplyAnalyzeEmpty':
      'لا توجد معاملات للتحليل بعد. امسح إيصالاً أو استورد كشفاً وسنفصّل الإنفاق معاً.',
  'umaReplyExplainWealth':
      'تتابع Vera محفظتك عبر الحسابات التي استوردتها. الأسهم تبدو موزّعة بزيادة طفيفة هذا الشهر؛ اقتراحي رفع الذهب أو السيولة في زيارتك القادمة للبنك.',
  'umaReplyLoan':
      'بناءً على الدخل والدين في كشوفك، تبدو مؤهلاً لقروض شخصية متوسطة. افتح محاكاة الائتمان لنضبط المبلغ والمدة بأمان.',
  'umaReplySecurity':
      'وضعت علامة على ذلك التحويل لأن المستلم ظهر مرة واحدة قبلاً ولأن موقع الجهاز لم يطابق نمطك المعتاد. Vera لا تحظر لدى بنكك — تنبهك، والقرار يكون بينكما.',
  'umaReplySubscriptions':
      'لديك {n} خطط تستحق المراجعة. إجمالي اشتراكاتك الشهري نحو {total}.',
  'umaReplySubscriptionsEmpty':
      'لا أرى اشتراكات نشطة بعد. استورد كشفاً وستكتشف Vera الرسوم المتكررة.',
  'umaReplyFallback':
      'يمكنني المساعدة. لو رغبت، أعطيك تقييماً مالياً سريعاً أو أحضّر خطوة آمنة تالية.',
  'updatedAt': 'تم التحديث {time}',
};
