part of '../app_strings.dart';

const Map<String, String> _deStrings = {
  'navHome': 'Start',
  'navWealth': 'Vermögen',
  'navPlans': 'Pläne',
  'navSecurity': 'Sicherheit',
  'navUma': 'UMA',
  'helloLabel': 'Hallo,',
  'defaultUserName': 'Vera Nutzer',
  'totalNetWorth': 'GESAMTVERMÖGEN',
  'liveFeed': 'LIVE',
  'syncing': 'SYNCHRO',
  'thisMonth': 'diesen Monat',
  'connectedAccounts': 'Verbundene Konten',
  'refresh': 'Aktualisieren',
  'syncingDots': 'Synchronisieren...',
  'recentTransactions': 'Letzte Transaktionen',
  'itemsCount': '{n} Einträge',
  'itemsVisible': 'sichtbar',
  'connectBank': 'Bank verbinden',
  'homeFirstStepsTitle': 'Lass uns mit dem ersten Schritt beginnen',
  'homeFirstStepsBody':
      'Vera wird deutlich besser, sobald dein erster Datenpunkt da ist. Importiere einen Auszug, scanne einen Beleg oder füge eine Bank hinzu, damit der Home-Bereich lebendig wird.',
  'homeFirstStepsHint':
      'Schon einer dieser Schritte reicht, um Vorschläge, Kontostände und smarte Hinweise zu aktivieren.',
  'connectedAccountsEmptyTitle': 'Noch keine verbundenen Konten',
  'connectedAccountsEmptyBody':
      'Sobald du eine Bank hinzufügst, verfolgen wir den Kontostand auf der Startseite und bereiten Uma-Aktionen mit besserem Kontext vor.',
  'addBankTitle': 'Bank hinzufügen',
  'addBankSubtitle':
      'Vera verbindet sich nicht — du fügst hinzu, der Saldo wird mitgeführt.',
  'addBankName': 'Bankname',
  'addBankLast4': 'Letzte 4 Ziffern',
  'addBankBalance': 'Saldo (TL)',
  'addBankColor': 'Farbe',
  'addBankSave': 'Bank hinzufügen',
  'addBankNameRequired': 'Bankname erforderlich.',
  'bankAdded': '{name} hinzugefügt',
  'umaInsight': 'UMA EINBLICK',
  'umaInsightNoData':
      'Vera kennt dich noch nicht. Importiere einen Auszug, scanne einen Beleg oder füge eine Bank hinzu, damit wir gemeinsam smarte Hinweise aufbauen können.',
  'umaInsightNoTransactions':
      'Es sind noch keine Buchungen sichtbar. Importiere deinen ersten Auszug oder füge eine manuelle Buchung hinzu, damit Uma dein Ausgabemuster versteht.',
  'umaInsightNoPattern':
      'Für diesen Zeitraum gibt es noch kein aussagekräftiges Ausgabenmuster. Mit neuen Buchungen wird der Einblick hier klarer.',
  'umaInsightTopCategory':
      'Am meisten entfiel auf {category}: {amount}, also etwa {share}% des analysierten Gesamtbetrags von {total}.',
  'umaInsightImportCta': 'Auszug importieren',
  'umaInsightAddFirstTxnCta': 'Erste Buchung hinzufügen',
  'umaInsightDeepenCta': 'Mit Uma vertiefen',
  'spent': 'Ausgegeben',
  'incoming': 'Eingang',
  'creditTitle': 'Kredit',
  'creditSubtitle': 'Kreditaufnahme nach echtem Einkommen.',
  'creditSummaryCardSubtitle': 'Monatsrate und Schuldenquote berechnen',
  'openCredit': 'Kredit öffnen',
  'wealthTitle': 'Vermögen',
  'wealthSubtitle': 'Ihr Geld arbeitet autonom.',
  'portfolio': 'PORTFOLIO',
  'ytd': 'JTD',
  'today': 'heute',
  'autonomousWealth': 'Autonomes Vermögen',
  'profile': 'PROFIL',
  'moveLimit': 'BEWEGUNGSLIMIT',
  'approval': 'FREIGABE',
  'activityFeed': 'Aktivitäten',
  'explainability': 'Erklärbarkeit',
  'undo': 'Rückgängig',
  'viewDetails': 'Details ansehen',
  'plansTitle': 'Pläne',
  'plansSubtitle': 'Stillen Geldverlust frühzeitig erkennen.',
  'subscriptionIntelligence': 'ABONNEMENT-INTELLIGENZ',
  'detectedPlans': 'Erkannte Pläne',
  'filterAll': 'Alle',
  'filterAttention': 'Achtung nötig',
  'filterUnused': 'Ungenutzt',
  'filterPriceChanges': 'Preisänderung',
  'askUma': 'Uma fragen',
  'securityTitle': 'Sicherheit',
  'securitySubtitle': 'Ihre Live-Schutzschicht.',
  'profileAndSettings': 'Profil & Einstellungen',
  'sectionAppearance': 'DESIGN & THEMA',
  'sectionAi': 'KI-EINSTELLUNGEN',
  'sectionConnected': 'VERBUNDENE INSTITUTE',
  'sectionAccount': 'KONTO',
  'sectionLanguage': 'SPRACHE',
  'sectionNotifications': 'BENACHRICHTIGUNGEN & SICHERHEIT',
  'brandPalette': 'Markenpalette',
  'mood': 'Stimmung',
  'moodLight': 'Hell',
  'moodDark': 'Dunkel',
  'vibe': 'Vibe',
  'vibeCalm': 'Ruhig',
  'vibeStandard': 'Standard',
  'vibeBold': 'Mutig',
  'language': 'Sprache',
  'signOut': 'Abmelden',
  'umaTone': 'Uma-Ton',
  'toneConcise': 'Kompakt',
  'toneCoach': 'Coach',
  'toneProactive': 'Proaktiv',
  'scanReceipt': 'Scannen',
  'scanReceiptTitle': 'Beleg oder Bildschirm scannen',
  'scanReceiptSubtitle':
      'Beleg, Rechnung oder Bank-Screen erfassen und in eine Buchung umwandeln.',
  'scanHint':
      'KI liest den Beleg, erkennt Kategorie und Summe und fragt nach Bestätigung.',
  'takePhoto': 'Foto aufnehmen',
  'pickFromGallery': 'Aus Galerie wählen',
  'scanReading': 'KI liest...',
  'scanTotalLabel': 'Summe',
  'scanAgain': 'Erneut scannen',
  'addToTransactions': 'Zu Buchungen',
  'scanNoTotal': 'Betrag nicht erkannt, bitte erneut scannen.',
  'addedToTransactions': 'Hinzugefügt',
  'parsedByAi': 'KI',
  'parsedFallback': 'DEMO',
  'scanFallbackWarning':
      'Der Gemini-API-Schlüssel fehlt oder der Beleg konnte nicht gelesen werden. Bitte manuell eingeben.',
  'scanFallbackAction': 'KI fehlgeschlagen — manuell eingeben',
  'savingsStoryLabel': 'DIESEN MONAT GESPART',
  'savingsStoryFooter': 'Dank 3 Uma-Tipps',
  'savingsStoryDelta': '{pct}% weniger als letzten Monat',
  'upcomingBills': 'Anstehende Rechnungen',
  'billPayViaUma': 'Mit Uma zahlen',
  'daysLeft': 'noch {n} Tage',
  'statementImport': 'Auszug importieren',
  'statementImportTitle': 'Kontoauszug importieren',
  'statementImportSubtitle':
      'PDF oder Bild deines Auszugs hochladen; KI extrahiert die Buchungen.',
  'pickStatementFile': 'Datei wählen (PDF / Bild)',
  'statementImportHint':
      'Deine Bank exportiert Auszüge als PDF — Vera liest sie ohne Open-Banking-Zugang.',
  'statementParsing': 'KI liest den Auszug...',
  'closingBalance': 'Schlussbestand',
  'detectedTransactions': '{n} Buchungen erkannt',
  'statementImportAgain': 'Erneut importieren',
  'statementNoTransactions': 'Keine Buchungen erkannt.',
  'statementImported': 'Zu deinen Buchungen hinzugefügt',
  'importToVera': 'Zu Vera importieren',
  'statementFallbackWarning':
      'Der Gemini-API-Schlüssel fehlt oder der Auszug konnte nicht gelesen werden. Bitte die Buchungen manuell eingeben.',
  'statementFallbackAction': 'KI fehlgeschlagen — manuell eingeben',
  'thisMonthsAiPlan': 'KI-Plan für diesen Monat',
  'aiPlanFooter':
      'Gemini-Anlageideen — die Entscheidung liegt bei dir.',
  'applyAtBank': 'In meiner Bank umsetzen',
  'securityVeraSideBanner':
      'Vera ist nicht die Sicherheitsschicht der Bank. Sie erkennt Anomalien in deinen Daten und warnt dich; das Blockieren entscheidest du gemeinsam mit deiner Bank.',
  'statusAllClear': 'Alles in Ordnung',
  'statusMonitoring': 'Überwachung',
  'securityRecentActivity': 'Letzte Aktivität',
  'securityScanning': 'Scannen...',
  'liveAnomalyDetected': 'Anomalie erkannt',
  'highRiskConfidence': 'Hohes Risiko',
  'reviewedSignal': 'Geprüft',
  'keepBlocked': 'Blockiert lassen',
  'thisWasMe': 'Das war ich',
  'emailField': 'E-Mail',
  'passwordField': 'Passwort',
  'loginDemoHint':
      'Schnelltest mit dem Demo-Konto: E-Mail „{email}", Passwort „{password}".',
  'umaVoiceStart': 'Per Sprache fragen',
  'umaVoiceStop': 'Aufnahme stoppen',
  'umaVoiceListening': 'Ich höre zu...',
  'umaVoicePermissionDenied':
      'Mikrofonberechtigung nötig. In den Systemeinstellungen für Vera erlauben.',
  'umaVoiceUnavailable':
      'Spracherkennung ist auf diesem Gerät nicht verfügbar.',
  'umaToolGoalCreated': 'Erledigt. Ein Ziel über {target} TL wurde erstellt.',
  'umaToolBillAdded': 'Rechnung {name} hinzugefügt, fällig in {days} Tagen.',
  'umaToolExpenseAdded': 'Ausgabe {name} ({amount} TL) erfasst.',
  'umaSuggestionSubs': 'Abos anzeigen',
  'umaSuggestionAnalyze': 'Ausgaben analysieren',
  'voiceCommandTooltip': 'Sprachbefehl',
  'umaAuditTrailTitle': 'Audit-Protokoll',
  'umaAuditTrailEmpty': 'Noch keine signierten Uma-Aktionen.',
  'umaAuditTrailCount': '{n} signierte Aktionen auf diesem Gerät.',
  'accountTilePersonal': 'Persönliche Daten',
  'accountTileEmail': 'E-Mail',
  'accountTileSecurity': 'Sicherheit & PIN',
  'accountTileStorage': 'Datenspeicherung',
  'accountTileHelp': 'Hilfe & Support',
  'accountTileHelpValue': 'FAQ, Kontakt',
  'infoDisplayName': 'Anzeigename',
  'infoMember': 'Mitgliedschaft',
  'infoMemberDescription':
      'Diese Demo-Sitzung läuft lokal auf diesem Gerät.',
  'infoSignInMethod': 'Anmeldemethode',
  'infoEmailLabel': 'E-Mail-Adresse',
  'infoEmailUsage': 'Wofür sie verwendet wird',
  'infoEmailDescription':
      'Für die Demo-Sitzung verwendet. Daten bleiben auf dem Gerät, nichts geht an einen Server.',
  'infoEmailDescriptionLive':
      'Diese Adresse wird für Firebase Auth, Kontowiederherstellung und wichtige Vera-Benachrichtigungen verwendet.',
  'authMethodGoogle': 'Mit Google fortfahren',
  'authMethodEmail': 'E-Mail und Passwort',
  'authMethodDemo': 'Demo-Tresor',
  'infoSessionVault': 'Session-Vault',
  'infoSessionVaultDescription':
      'Sitzungsdaten werden via flutter_secure_storage verschlüsselt und nur lokal auf diesem Gerät gespeichert.',
  'infoFaceId': 'Face ID',
  'infoFaceIdOn': 'An — beim Anmelden wird biometrische Bestätigung verlangt.',
  'infoFaceIdOff': 'Aus — Passwort / Demo-Login genügt.',
  'infoFraudAlerts': 'Fraud-Warnungen',
  'infoFraudAlertsOn':
      'An — sendet eine lokale Benachrichtigung bei verdächtigen Ereignissen.',
  'infoFraudAlertsOff': 'Aus — Warnungen erscheinen nur in der App.',
  'infoSyncMode': 'Sync-Modus',
  'infoLocalData': 'Lokale Daten',
  'infoLocalDataDescription':
      'OCR-Belege und hinzugefügte Banken liegen in SharedPreferences. "Daten exportieren" ist im P1-Backlog.',
  'infoCloudSync': 'Cloud-Sync',
  'infoCloudSyncActive':
      'Cloud-Sync ist aktiv. Importierte Belege, Auszüge, Banken, Profileinstellungen und Transaktionen können in deinen Vera-Bereich synchronisiert werden.',
  'infoCloudSyncInactive':
      'Cloud-Sync ist in dieser Sitzung nicht aktiv; Vera läuft derzeit im lokalen Modus.',
  'fraudAlertTitle': 'Vera • Verdächtige Buchung blockiert',
  'googleSignInConfigMissing':
      'Google-Anmeldung fehlgeschlagen. Der SHA-1-Fingerabdruck der App ist möglicherweise nicht in der Firebase Console hinterlegt. Der Admin muss die Firebase-Einstellungen aktualisieren.',
  'fraudReasonOutlier':
      'Diese Ausgabe liegt {multiplier}× über deinem aktuellen Median von {median} TL. Vera findet den Sprung auffällig.',
  'fraudNameRoundTransfer': 'Runde Überweisung · {amount} TL',
  'fraudReasonRoundTransfer':
      'Ein perfekt runder Betrag über 10.000 TL wurde erkannt. Häufig eine legitime Empfänger-Überweisung — bestätige, ob du es warst.',
  'fraudNameBurst': '{merchant} · {count}× am selben Tag',
  'fraudLocationBurstTotal': 'Gesamt {total} TL',
  'fraudReasonBurst':
      'Derselbe Händler hat heute {count}-mal abgebucht. Kartenwiederholung oder echter Einkaufsbummel?',
  'helpFaqQ1': 'Verbindet Vera sich mit meiner Bank?',
  'helpFaqA1':
      'Nein. Vera hat keine AISP/PSP-Lizenz. Du bringst die Daten: PDF-Auszüge, Belegfotos, Screenshots oder manuelle Einträge. Vera fügt sie mit KI zusammen und leitet reale Aktionen an deine Bank-App weiter.',
  'helpFaqQ2': 'Wo werden meine Daten gespeichert?',
  'helpFaqA2':
      'Sensible Sitzungsdaten im flutter_secure_storage (verschlüsselt, auf dem Gerät). OCR und Bankeinträge in SharedPreferences. Kein Server, keine Datenweitergabe an Dritte.',
  'helpFaqQ3': 'Was passiert ohne Gemini API-Key?',
  'helpFaqA3':
      'OCR und Statement-Import laufen mit deterministischem Fallback (DEMO-Badge erscheint). UMA-Chat antwortet über einen heuristischen Intent-Router. Der gesamte Flow funktioniert — nur das Live-AI-Parsing ist aus.',
  'helpContact': 'Kontakt',
  'demoUser': 'Demo-Nutzer',
  'umaThinking': 'Uma denkt nach...',
  'umaAskHint': 'Frag Uma...',
  'umaStatusOnline': 'KI-Assistent · online',
  'onbStep1Title': 'Willkommen bei Vera',
  'onbStep1Subtitle':
      'Wähle zuerst deine Sprache. Du kannst sie jederzeit in den Einstellungen ändern.',
  'onbStep2Title': 'Mach es zu deinem',
  'onbStep2Subtitle':
      'Wähle Palette und Stimmung der Marke. Das Theme kannst du später ändern.',
  'onbStep3Title': 'Bring deine Daten mit',
  'onbStep3Subtitle':
      'Vera verbindet sich nicht mit deiner Bank — du bringst Auszüge mit, Vera versteht sie. Starte jetzt oder füge sie später hinzu.',
  'onbContinue': 'Weiter',
  'onbStart': 'Vera starten',
  'onbSkip': 'Überspringen',
  'onbBack': 'Zurück',
  'onbImportNow': 'Auszug importieren',
  'onbScanNow': 'Beleg scannen',
  'onbContinueWithoutImport': 'Ohne Import fortfahren',
  'onbPalettePreviewTitle': 'Live-Vorschau',
  'onbPalettePreviewBody':
      'Deine Auswahl verändert Karten, KI-Highlights und die gesamte Stimmung sofort.',
  'onbBlankCanvasTitle': 'Auch leer zu starten ist okay',
  'onbBlankCanvasBody':
      'Wenn du willst, kannst du jetzt ohne Import weitermachen; Vera begleitet dich auch beim ersten Schritt in der App.',
  'goalEmptyPrompt':
      'Du hast noch kein Ziel festgelegt — tippe hier, um eines anzulegen.',
  'goalEmptyHint':
      'Setze zuerst ein Ziel, dann kann Uma aus deinem Monatsrhythmus ableiten, wie viel du zurücklegen solltest.',
  'goalEmptyCta': 'Ziel festlegen',
  'goalMonthsLabel': 'IN WIE VIELEN MONATEN',
  'goalMonthsOption': '{n} Mon.',
  'goalAdviceSummary': '{amount} pro Monat · {months} Monate',
  'goalCalculate': 'Berechnen',
  'goalPresetEmergency': 'Notgroschen (6 Mon) · {amount}',
  'goalPresetVacation': 'Urlaub (3 Mon) · {amount}',
  'goalPresetCar': 'Auto (12 Mon) · {amount}',
  'fieldName': 'Name',
  'fieldAmountTl': 'Betrag (TL)',
  'fieldDate': 'Datum',
  'fieldCategory': 'Kategorie',
  'fieldDescription': 'Beschreibung',
  'fieldLabelOptional': 'Bezeichnung (optional)',
  'actionAdd': 'Hinzufügen',
  'actionUpdate': 'Aktualisieren',
  'actionDelete': 'Löschen',
  'actionBack': 'Zurück',
  'actionManual': 'Manuell',
  'addBillTitle': 'Neue Rechnung hinzufügen',
  'editBillTitle': 'Rechnung bearbeiten',
  'addBillNameHint': 'z. B. Turk Telekom',
  'dueDateLabel': 'Fälligkeitsdatum',
  'addBillCta': 'Rechnung hinzufügen',
  'noTrackedBillsTitle': 'Noch keine verfolgten Rechnungen',
  'noTrackedBillsBody':
      'Vera erinnert dich einen Tag vor dem Fälligkeitsdatum.',
  'billKindCard': 'Karte',
  'billKindInternet': 'Internet',
  'billKindElectric': 'Strom',
  'billKindWater': 'Wasser',
  'billKindGas': 'Gas',
  'billKindRent': 'Miete',
  'billKindOther': 'Andere',
  'addManualTxnTitle': 'Manuelle Buchung hinzufügen',
  'txnTypeExpense': 'Ausgabe',
  'txnTypeIncome': 'Einnahme',
  'addManualTxnNameHint': 'z. B. Migros',
  'aiSuggestionLabel': 'Uma-Vorschlag',
  'acceptSuggestion': 'Übernehmen',
  'categoryMarket': 'Supermarkt',
  'categoryFood': 'Essen & Trinken',
  'categoryFuel': 'Kraftstoff',
  'categoryBill': 'Rechnungen',
  'categoryHealth': 'Gesundheit',
  'categoryEducation': 'Bildung',
  'categoryEntertainment': 'Freizeit',
  'categoryTransfer': 'Überweisung',
  'categorySalary': 'Gehalt',
  'categorySubscription': 'Abo',
  'categoryMusic': 'Musik',
  'categoryVideo': 'Video',
  'categoryStorage': 'Speicher',
  'categoryDeveloper': 'Entwickler',
  'categoryAi': 'KI',
  'noTransactionsTitle': 'Noch keine Buchungen',
  'noTransactionsBody':
      'Füge deine erste Buchung hinzu, importiere einen Auszug oder scanne einen Beleg.',
  'addHoldingTitle': 'Vermögenswert zum Portfolio hinzufügen',
  'addHoldingSubtitle':
      'Wähle unten einen Bucket aus und gib den TL-Wert ein. Uma berechnet die Gewichte automatisch neu.',
  'addHoldingHint': 'z. B. THYAO oder XU100 ETF',
  'holdingValueLabel': 'Wert (TL)',
  'removeHolding': 'Diesen Vermögenswert entfernen',
  'noWealthActionsTitle': 'Uma hat noch keine Aktion ausgeführt',
  'noWealthActionsBody':
      'Sobald du den autonomen Modus aktivierst, erscheinen Empfehlungen und Rebalancing-Schritte hier.',
  'startPortfolioTitle': 'Beginne mit deinem Portfolio',
  'startPortfolioBody':
      'Füge Aktien, Gold, Bargeld oder Krypto hinzu. Uma beobachtet Abweichungen und schreibt hier Vorschläge.',
  'wealthApprovalAuto': 'Auto',
  'wealthApprovalHybrid': 'Hybrid',
  'wealthActionReversed': 'RÜCKGÄNGIG',
  'holdingBucketEquity': 'Aktien',
  'holdingBucketGold': 'Gold',
  'holdingBucketCash': 'Bargeld',
  'holdingBucketCrypto': 'Krypto',
  'holdingBucketFunds': 'Fonds',
  'holdingBucketBonds': 'Anleihe',
  'subscriptionsAttentionCount':
      '{n} Pläne brauchen in diesem Zyklus Aufmerksamkeit',
  'noSubscriptionsDetectedTitle': 'Noch keine Abos erkannt',
  'noSubscriptionsDetectedBody':
      'Importiere einen Auszug oder scanne einen Beleg — Vera erkennt wiederkehrende Zahlungen automatisch.',
  'noSubscriptionsForFilterTitle': 'Keine Abos für diesen Filter',
  'noSubscriptionsForFilterBody': 'Probiere andere Filter aus.',
  'subsAlertSavingsTitle': 'Monatliches Sparpotenzial',
  'subsAlertSavingsMessageEmpty':
      'Noch keine Abos erkannt. Importiere einen Auszug oder füge eines manuell hinzu, dann verfolgt Vera es.',
  'subsAlertSavingsMessageActive':
      'Vera hat Abos gefunden, die du einfrieren oder auf ein kleineres Paket umstellen kannst, ohne deinen Alltag zu stören.',
  'subsAlertSavingsMetric': 'SPAREN',
  'subsAlertPriceTitle': 'Preiserhöhung erkannt',
  'subsAlertPriceMessageNone':
      'In diesem Zyklus gibt es keine ungewöhnlichen Preissprünge.',
  'subsAlertPriceMessageSome':
      'Ein oder mehrere Pläne sind im Vergleich zum letzten Monat teurer geworden.',
  'subsAlertPriceMetric': 'MEHR',
  'subsAlertUnusedTitle': 'Wenig genutzte Pläne',
  'subsAlertUnusedMessageNone': 'Alle Abos wirken gesund genutzt.',
  'subsAlertUnusedMessageSome':
      '{n} Pläne wirken anhand deines letzten Aktivitätsmusters wenig genutzt.',
  'subsAlertUnusedMetric': 'LEER',
  'subsInsightEmpty':
      'Vera analysiert deine Auszüge oder Belege und sammelt deine Abos hier.',
  'subsInsightHealthy':
      'Deine Abos sehen diesen Monat gesund aus. Es gibt kein akutes Sparleck.',
  'subsInsightNeedsAttention':
      'Du hast {n} Abos, die sich lohnen zu prüfen. Vera schätzt, dass du etwa {amount} pro Monat zurückholen könntest, indem du ungenutzte pausierst und teurere herabstufst.',
  'subsDetectedFromImport': 'Aus importierter Buchung erkannt',
  'subsSeenInRecentTransactions': '{n}× in letzten Buchungen gesehen',
  'subsKnownVendorLabel': 'Bekannter Abo-Anbieter',
  'subsRecommendationDetected':
      'Vera hat dieses Abo in einem importierten Auszug erkannt. Nutzt du es noch?',
  'subsStatusActive': 'AKTIV',
  'subsStatusPriceUp': 'TEURER',
  'subsStatusUnused': 'WENIG GENUTZT',
  'subsStatusRenewsSoon': 'BALD ERNEUERT',
  'proactiveBadge': 'VERA HAT ERKANNT',
  'proactiveBillTitle': '{name} steht bald an',
  'proactiveBillBody':
      '{amount} · noch {days} Tage. Soll Uma den Zahlungsplan vorbereiten?',
  'proactiveBillCta': 'Mit Uma bezahlen',
  'proactiveBillPrompt': 'Hilf mir, meine Rechnung für {name} zu bezahlen.',
  'proactivePriceTitle': '{name} wurde teurer',
  'proactivePriceBody': '+{delta} pro Monat. Willst du das Abo pausieren?',
  'proactivePriceCta': 'Abos öffnen',
  'proactiveUnusedTitle': '{name} wird kaum genutzt',
  'proactiveUnusedBody':
      'Zuletzt genutzt: {last}. Das könnte ein stilles Geldleck sein.',
  'proactiveUnusedCta': 'Abos öffnen',
  'proactiveHealthyTitle': 'Im Moment kein kritisches Signal',
  'proactiveHealthyBody':
      'Aktuell sehen wir weder eine dringende Rechnung noch einen Preissprung oder ein offensichtlich unnötiges Abo. Wenn du willst, schaut Uma trotzdem kurz drauf.',
  'proactiveHealthyCta': 'Uma einschätzen lassen',
  'proactiveEmptyTitle': 'Vera hat noch kein Signal zum Beobachten gefunden',
  'proactiveEmptyBody':
      'Sobald du einen Auszug importierst, hebt Vera anstehende Zahlungen, Abos und kleine Risiken hier hervor.',
  'proactiveEmptyCta': 'Auszug importieren',
  'securityEmptyTitle': 'Zurzeit gibt es keine Warnung zur Prüfung',
  'securityEmptyBody':
      'Das Fraud-Radar von Vera überwacht still deine Geräte und importierten Transaktionen. Wenn etwas passiert, erscheint es hier.',
  'close': 'Schließen',
  'categoryOther': 'Sonstiges',
  'receiptDefaultName': 'Beleg',
  'wealthInsightAddPortfolio':
      'Autonomer Modus ist aus. Füge dein Portfolio hinzu, damit Uma Abweichungen verfolgen und Vorschläge machen kann.',
  'wealthInsightPaused':
      'Autonomer Modus pausiert. Vera beobachtet weiter, wartet aber auf deine Bestätigung, bevor Geld bewegt wird.',
  'wealthInsightActive':
      'Uma ist mit der "{profile}"-Richtlinie aktiv. Innerhalb des monatlichen Limits von {limit} TL wurden {count} Portfolioanpassungen vorbereitet oder ausgeführt.',
  'goalReached':
      'Du hast dein Ziel erreicht. Du kannst jetzt ein neues setzen.',
  'goalRemainingPlan':
      'Um die verbleibenden {remaining} TL in {months} Monaten anzusparen, musst du monatlich {monthly} TL zurücklegen.',
  'goalNarrativeNewTarget':
      'Du kannst einen neuen Betrag für dein Ziel festlegen.',
  'goalNarrativeNoData':
      'Noch keine Transaktionsdaten. Importiere einen Auszug oder füge manuelle Einträge hinzu, damit Uma einen Plan vorschlagen kann.',
  'goalNarrativeTrim':
      'Du musst monatlich {monthly} TL zurücklegen. Kleine Kürzungen im {topCategory}-Budget sind ein guter Anfang.',
  'todayAt': 'Heute, {time}',
  'loginContinueEmail': 'Mit E-Mail fortfahren',
  'loginEmailPasswordRequired': 'E-Mail und Passwort sind erforderlich.',
  'loginFirebaseError': 'Firebase-Anmeldung fehlgeschlagen: {code}.',
  'loginFirebaseReadyFooter':
      'Firebase-Auth verbunden. Demo-Modus bleibt für Hackathon-Flows verfügbar.',
  'loginCreateAccount': 'Konto erstellen',
  'dividerOr': 'oder',
  'signupTitle': 'Konto erstellen',
  'signupSubtitleFirebase':
      'Erstelle dein Konto — dein Vera-Profil und deine Daten werden sicher synchronisiert.',
  'signupSubtitleLocal':
      'Keine Server-Konfiguration. Dieser Flow läuft im lokalen Demo-Modus weiter.',
  'signupFieldFullName': 'Vollständiger Name',
  'signupFieldEmail': 'E-Mail',
  'signupFieldPassword': 'Passwort',
  'signupFieldConfirmPassword': 'Passwort bestätigen',
  'signupErrorNameRequired': 'Bitte gib deinen vollständigen Namen ein.',
  'signupErrorInvalidEmail': 'Bitte gib eine gültige E-Mail-Adresse ein.',
  'signupErrorShortPassword':
      'Das Passwort muss mindestens 6 Zeichen lang sein.',
  'signupErrorPasswordMismatch': 'Die Passwörter stimmen nicht überein.',
  'signupErrorAcceptTerms':
      'Bitte akzeptiere die Bedingungen, um fortzufahren.',
  'signupFailedTemplate': 'Kontoerstellung fehlgeschlagen: {code}.',
  'signupTerms':
      'Ich akzeptiere die Vera-Bedingungen und die lokale Demo-Datenrichtlinie.',
  'signupStrengthWeak': 'Schwach',
  'signupStrengthMedium': 'Mittel',
  'signupStrengthStrong': 'Stark',
  'signupCtaCreate': 'Registrieren',
  'signupCtaContinueLocal': 'Als Demo fortfahren',
  'signupAlreadyHaveAccount': 'Hast du schon ein Konto? ',
  'signupSignIn': 'Anmelden',
  'demoSampleLoaded': 'Beispieldaten geladen.',
  'demoBankPrimary': 'Vera Bank — Girokonto',
  'demoBankSavings': 'Vera Bank — Sparkonto',
  'demoBillCreditCard': 'Kreditkartenabrechnung',
  'demoBillElectric': 'Stromrechnung',
  'demoBillInternet': 'Internetrechnung',
  'demoTxnSalary': 'Gehaltszahlung',
  'demoTxnGrocery': 'Lebensmitteleinkauf',
  'demoTxnFuel': 'Kraftstoff',
  'demoTxnRestaurant': 'Restaurant',
  'demoTxnPharmacy': 'Apotheke',
  'demoTxnRent': 'Mietzahlung',
  'demoTxnTransfer': 'Überweisung — Sparkonto',
  'demoTxnFamilyIncoming': 'Eingehende Überweisung — Familie',
  'demoTxnAtm': 'Bargeldabhebung am Geldautomaten',
  'deleteAccount': 'Konto löschen',
  'deleteAccountTile': 'Konto löschen',
  'deleteAccountTileValue': 'Cloud-Daten entfernen und abmelden',
  'deleteAccountDemoTileValue': 'Demo-Daten auf diesem Gerät löschen',
  'deleteAccountTitle': 'Dieses Konto löschen?',
  'deleteAccountBody':
      'Dein Vera-Konto, synchronisierte Daten und der lokale Cache auf diesem Gerät werden dauerhaft gelöscht. Dieser Vorgang kann nicht rückgängig gemacht werden.',
  'deleteAccountDemoBody':
      'Dadurch werden das Demokonto und die lokalen Daten auf diesem Gerät gelöscht. Dieser Vorgang kann nicht rückgängig gemacht werden.',
  'deleteAccountConfirm': 'Konto löschen',
  'deleteAccountCancel': 'Abbrechen',
  'deleteAccountProcessing': 'Konto wird gelöscht...',
  'deleteAccountDone': 'Konto gelöscht.',
  'deleteAccountError':
      'Das Konto konnte nicht gelöscht werden. Bitte melde dich erneut an und versuche es noch einmal.',
  'deleteAccountRecentLogin':
      'Melde dich aus Sicherheitsgründen bitte erneut an, bevor du dein Konto löschst.',
  'continueWithGoogle': 'Mit Google fortfahren',
  'googleSignInUnavailable':
      'Google-Anmeldung erfordert eine Firebase-Konfiguration fÃ¼r diesen Build.',
  'bankActionsTitle': 'Bank-Optionen',
  'bankActionsCancel': 'Abbrechen',
  'bankActionsDelete': 'Bank löschen',
  'bankActionsConfirmTitle': 'Diese Bank löschen?',
  'bankActionsConfirmBody':
      '{name} wird entfernt und zählt nicht mehr zum Gesamtsaldo.',
  'bankDeleted': '{name} gelöscht',
  'bankActionsFeedNote':
      'Diese Bank gehört zu den Demo-Daten und kann nicht gelöscht werden. Selbst hinzugefügte kannst du entfernen.',
  'billDetailPrompt':
      'Meine {name}-Rechnung beträgt {amount}, fällig in {days} Tagen. Was soll ich tun?',
  'categoryBudgetLabel': 'AUSGABEN DIESEN MONAT',
  'categoryBudgetTopHint': 'Am meisten für {category} · {pct}%',
  'categoryLimitEditTitle': 'Kategorielimit',
  'categoryLimitEditSubtitle':
      'Setze ein Monatsbudget für {category}. Vera zeigt bei jeder Ausgabe den Rest.',
  'categoryLimitField': 'Monatslimit (TL)',
  'categoryLimitSave': 'Speichern',
  'categoryLimitClear': 'Limit entfernen',
  'categoryNoLimit': 'kein Limit',
  'categoryOver': '{amount} drüber',
  'categoryRemaining': 'noch {amount}',
  'creditFieldDebt': 'Bestehende Monatsraten',
  'creditFieldIncome': 'Monatliches Einkommen',
  'creditFieldLoanAmount': 'Kreditbetrag',
  'creditFieldTerm': 'Laufzeit',
  'creditTermMonths': '{n} Monate',
  'creditScoreDisclaimer':
      'Diese Seite berechnet keinen Bonitäts-Score. Echte Scores findest du bei deiner Bank oder einer Auskunftei. Hier siehst du nur eine geschätzte Monatsrate und Schuldenquote aus deinen Eingaben.',
  'creditLoanSimulation': 'Kredit-Simulator',
  'creditLoanSimulationSubtitle':
      'Passe die Werte an — Monatsrate und Schuldenlast werden live berechnet.',
  'creditResultMonthlyPayment': 'GESCHÄTZTE MONATSRATE',
  'creditResultTotalCost': 'Gesamtrückzahlung',
  'creditResultPaymentLoad': 'Rate / Einkommen',
  'creditResultDtiAfter': 'Neue Schuldenquote',
  'creditResultGuidance':
      'Banken wünschen meist eine Schuldenquote unter 35%. Über 40% schränkt Angebote stark ein. Nur für Planungszwecke.',
  'demoResetTile': 'Demo-Daten zurücksetzen',
  'demoResetTileValue': 'Importe und Eintragungen löschen',
  'demoResetTitle': 'Demo-Daten zurücksetzen?',
  'demoResetBody':
      'Importierte Transaktionen, von dir hinzugefügte Banken und Zielfortschritt kehren zum Startzustand zurück.',
  'demoResetCancel': 'Abbrechen',
  'demoResetConfirm': 'Zurücksetzen',
  'demoResetDone': 'Zurück im Demo-Zustand',
  'exportTile': 'Meine Daten exportieren',
  'exportTileValue': 'JSON · nur auf dem Gerät',
  'exportTitle': 'Deine Vera-Daten',
  'exportSubtitle':
      'Importierte Transaktionen, hinzugefügte Banken, dein Ziel und die erkannten Abos. Kopieren, ohne das Gerät zu verlassen.',
  'exportCopy': 'JSON kopieren',
  'exportCopied': 'In die Zwischenablage kopiert',
  'firstScanPending': 'Warte auf ersten Scan',
  'firstSyncPending': 'Warte auf ersten Sync',
  'goalEditTitle': 'Ziel bearbeiten',
  'goalEditTarget': 'Zielbetrag (TL)',
  'goalEditSaved': 'Bislang gespart (TL)',
  'goalEditFooter':
      'Vera verfolgt den Saldo; Uma meldet sich monatlich mit einem neuen Impuls.',
  'goalEditSave': 'Speichern',
  'goalEmergencyFund': 'Notgroschen',
  'goalEtaMonths': 'Noch {n} Monate',
  'goalEtaReached': 'Geschafft 🎯',
  'goalProgress': '{pct}% erreicht',
  'goalRemaining': 'noch {amount}',
  'goalsSectionTitle': 'Deine Ziele',
  'lastScanAt': 'Letzter Scan {time}',
  'loginTitle': 'Bei Vera anmelden',
  'loginSubtitle':
      'Melde dich mit deinem Konto an; Profilpräferenzen und KI-Aktionen bleiben lokal, bis du dich abmeldest.',
  'loginEmailHint': 'du@vera.app',
  'loginFooter':
      'Wenn Firebase nicht konfiguriert ist, schlägt die Anmeldung fehl. Prüfe deine .env-Datei.',
  'notifTitle': 'Benachrichtigungen',
  'notifSubtitle': '{n} Signale, die Uma beobachtet',
  'notifEmpty': 'Alles ruhig. Uma wacht weiter im Hintergrund.',
  'notifBillTitle': '{name}-Rechnung steht an',
  'notifBillBody': 'Betrag {amount}. Begleiche über Uma oder deine Bank.',
  'notifPriceIncreaseTitle': '{name} hat den Preis erhöht',
  'notifPriceIncreaseBody':
      'Monatlich +{delta} · jetzt {price}. Du kannst es in Plänen einfrieren.',
  'notifUnusedTitle': '{name} wird nicht genutzt',
  'notifUnusedBody':
      'Zuletzt: {last}. Vera markiert es als unbemerktes Leck.',
  'notifBlockedDefault':
      'Vera hat diese Transaktion als Anomalie eingestuft.',
  'profileAiToneBadge': 'KI-TON / {tone}',
  'profileAutoApprove': 'Auto-Freigabe-Limit',
  'profileAutoApproveOff': 'Aus',
  'profileConnectedTitle': '{n} verbundene Institute',
  'profileConnectedSubtitle':
      'Live-Salden werden über die aktuelle Sync-Richtlinie und den Feed-Cache aktualisiert.',
  'profileConnectedAccount': 'Konto {last4}',
  'profileDailyBriefing': 'Tägliches KI-Briefing',
  'profileDailyBriefingSub':
      'Starte den Tag mit Konto-Gesundheit, verdächtigen Aktivitäten und Spartipps',
  'profileFaceId': 'Face-ID-Sperre',
  'profileFaceIdSub':
      'Biometrische Entsperrung vor sensiblen Aktionen erforderlich',
  'profileFraudHigh': 'Empfindliche Betrugswarnungen',
  'profileFraudHighSub':
      'Vera markiert ungewöhnliche Geräte- und Zahlungsmuster früher',
  'profileLiveSync': 'Live-Datenabgleich',
  'profileLiveSyncLive': 'Live',
  'profileLiveSyncBalanced': 'Ausgewogen',
  'profileLiveSyncSaver': 'Sparmodus',
  'profileSmartNotif': 'Smarte Benachrichtigungen',
  'profileSmartNotifSub':
      'Warnungen bei Betrug, Verlängerungen und Freigabeänderungen',
  'profileVaultTitle': 'Geschützter Sitzungs-Tresor',
  'profileVaultSubtitle':
      'Identität wird separat von lokalen Präferenzen gespeichert.',
  'profileVaultSignIn': 'Anmeldung',
  'profileVaultProtectedSince': 'Geschützt seit',
  'profileVaultThisDevice': 'Dieses Gerät',
  'profileVaultApproval': 'Freigabe-Schutz',
  'profileVaultManualOnly': 'Nur manuell',
  'profileVaultSyncMode': 'Sync-Modus',
  'profileVaultSyncLive': 'Live-Sync',
  'profileVaultSyncBalanced': 'Ausgewogener Sync',
  'profileVaultSyncSaver': 'Energiesparender Sync',
  'securityAccountSection': 'KONTOSICHERHEIT',
  'securityActiveBody': 'Fraud Radar verfolgt {n} aktive Warnungen.',
  'securityClearBody':
      'Keine offenen Betrugswarnungen im letzten Scan.',
  'securityPillBlocked': 'KI-BLOCKIERT',
  'securityPillApproved': 'VON DIR FREIGEGEBEN',
  'securityPillKept': 'BLOCKIERT GELASSEN',
  'securityDecisionKept':
      'Du hast dieses Ereignis blockiert gelassen. Fraud Radar behandelt ähnliche Muster weiterhin als Hochrisiko.',
  'securityDecisionApproved':
      'Du hast dieses Ereignis als sicher markiert. Fraud Radar nutzt dieses Feedback, um ähnliche Fehlalarme zu reduzieren.',
  'securityStatBlockedLabel': 'BLOCKIERT',
  'securityStatBlockedSub': 'aktiv',
  'securityStatReviewedLabel': 'GEPRÜFT',
  'securityStatReviewedSub': 'diese Woche',
  'securityStatDevicesLabel': 'GERÄTE',
  'securityStatDevicesSub': 'vertraut',
  'securityViewReport': 'UMA-BERICHT ÖFFNEN',
  'subsRenewalLabel': 'Verlängerung',
  'subsActivityLabel': 'Aktivität',
  'txnDetailWhen': 'Wann',
  'txnDetailCategory': 'Kategorie',
  'txnDetailDirection': 'Richtung',
  'txnDetailIncoming': 'Eingehend',
  'txnDetailOutgoing': 'Ausgehend',
  'txnDetailAskPrompt':
      'Schau dir die {name}-Buchung an — ist {amount} normal?',
  'umaAuditTrailSubtitle':
      'Eine signierte lokale Aufzeichnung von Umas Antworten auf diesem Gerät.',
  'umaAuditTrailEmptyState':
      'Noch keine signierten Aktionen. Sprich mit Uma, und das Vertrauensprotokoll erscheint hier.',
  'umaAuditNoteAttached': 'Notiz angehängt',
  'umaAuditActionReplyGenerated': 'Antwort erzeugt',
  'umaGreeting':
      'Hallo {name}. Ich habe deine importierten Auszüge gelesen. Ich kann deine Ausgaben analysieren, ungenutzte Abos aufdecken und beim Setzen von Sparzielen helfen. Ich bewege kein Geld — wenn eine Aktion nötig ist, leite ich dich an deine Bank-App weiter.',
  'umaPromptAnalyze': 'Analysiere meine Ausgaben in diesem Monat.',
  'umaReplyAnalyze':
      'Diesen Monat gibst du am meisten für {top} mit {topAmount} aus. Gesamtabfluss {spending}. Wenn du willst, setzen wir Limits pro Kategorie.',
  'umaReplyAnalyzeEmpty':
      'Noch keine Transaktionen zum Auswerten. Scanne einen Beleg oder importiere einen Auszug, dann brechen wir die Ausgaben gemeinsam herunter.',
  'umaReplyExplainWealth':
      'Vera verfolgt dein Portfolio über die importierten Konten. Aktien wirken diesen Monat leicht überallokiert; mein Vorschlag: Gold oder Bargeld beim nächsten Bankbesuch aufstocken.',
  'umaReplyLoan':
      'Basierend auf Einkommen und Schulden aus deinen Auszügen siehst du für mittlere Privatkredite stark aus. Öffne die Kreditsimulation, dann passen wir Betrag und Laufzeit gemeinsam an.',
  'umaReplySecurity':
      'Diesen Transfer habe ich markiert, weil der Empfänger nur einmal zuvor auftauchte und der Gerätestandort nicht zu deinem üblichen Muster passte. Vera blockiert nicht bei deiner Bank — sie warnt, die Entscheidung trefft ihr gemeinsam.',
  'umaReplySubscriptions':
      'Du hast {n} prüfenswerte Pläne. Deine monatliche Abo-Summe liegt bei etwa {total}.',
  'umaReplySubscriptionsEmpty':
      'Ich sehe noch keine aktiven Abos. Importiere einen Auszug, dann erkennt Vera wiederkehrende Buchungen.',
  'umaReplyFallback':
      'Dabei kann ich helfen. Auf Wunsch gebe ich dir eine kurze Finanz-Einschätzung oder bereite einen sicheren nächsten Schritt vor.',
  'updatedAt': 'Aktualisiert {time}',
};
