part of '../app_strings.dart';

const Map<String, String> _enStrings = {
  'navHome': 'Home',
  'navWealth': 'Wealth',
  'navPlans': 'Plans',
  'navSecurity': 'Security',
  'navUma': 'UMA',
  'helloLabel': 'Hello,',
  'defaultUserName': 'Vera User',
  'totalNetWorth': 'TOTAL NET WORTH',
  'liveFeed': 'LIVE FEED',
  'syncing': 'SYNCING',
  'thisMonth': 'this month',
  'connectedAccounts': 'Connected accounts',
  'refresh': 'Refresh',
  'syncingDots': 'Syncing...',
  'firstSyncPending': 'Awaiting first sync',
  'updatedAt': 'Updated {time}',
  'firstScanPending': 'Awaiting first scan',
  'lastScanAt': 'Last scan {time}',
  'recentTransactions': 'Recent transactions',
  'itemsCount': '{n} items',
  'itemsVisible': 'visible',
  'connectBank': 'Connect bank',
  'homeFirstStepsTitle': 'Let’s take the first step',
  'homeFirstStepsBody':
      'Vera gets much better after your first piece of data arrives. Import a statement, scan a receipt, or add a bank to bring the home screen to life.',
  'homeFirstStepsHint':
      'Even one of these is enough to unlock suggestions, balances, and smart alerts.',
  'connectedAccountsEmptyTitle': 'No connected accounts yet',
  'connectedAccountsEmptyBody':
      'Once you add a bank, we can track its balance on home and prepare Uma actions with better context.',
  'addBankTitle': 'Add a bank',
  'addBankSubtitle':
      "Vera doesn't connect to banks — you add them and track the balance.",
  'addBankName': 'Bank name',
  'addBankLast4': 'Last 4 digits',
  'addBankBalance': 'Balance (TL)',
  'addBankColor': 'Color',
  'addBankSave': 'Add bank',
  'addBankNameRequired': 'Bank name is required.',
  'bankAdded': '{name} added',
  'umaInsight': 'UMA INSIGHT',
  'umaInsightNoData':
      'Vera does not know you yet. Import a statement, scan a receipt, or add a bank so we can start building smarter guidance together.',
  'umaInsightNoTransactions':
      'No transactions are visible yet. Import your first statement or add a manual transaction so Uma can map your spending rhythm.',
  'umaInsightNoPattern':
      'There is not enough meaningful spending pattern for this period yet. As new transactions arrive, the insight here will get sharper.',
  'umaInsightTopCategory':
      'You spent the most on {category}: {amount}, about {share}% of the analyzed total of {total}.',
  'umaInsightImportCta': 'Import a statement',
  'umaInsightAddFirstTxnCta': 'Add first transaction',
  'umaInsightDeepenCta': 'Deepen with Uma',
  'spent': 'Spent',
  'incoming': 'In',
  'creditTermMonths': '{n} months',
  'creditScoreDisclaimer':
      "This page does not compute a credit score. For a real bureau score use your bank or a credit-reporting service. Here you only see an approximate monthly payment and debt ratio based on the values you enter.",
  'creditLoanSimulation': 'Loan simulator',
  'creditLoanSimulationSubtitle':
      'Tune the values — monthly payment and debt load update live.',
  'creditFieldLoanAmount': 'Loan amount',
  'creditFieldTerm': 'Term',
  'creditFieldIncome': 'Monthly income',
  'creditFieldDebt': 'Existing monthly debt',
  'creditResultMonthlyPayment': 'ESTIMATED MONTHLY PAYMENT',
  'creditResultTotalCost': 'Total repayment',
  'creditResultPaymentLoad': 'Installment / income',
  'creditResultDtiAfter': 'New debt-to-income ratio',
  'creditResultGuidance':
      "Lenders typically want your debt-to-income under 35%. Above 40% will narrow your offers. For planning only.",
  'subsRenewalLabel': 'Renewal',
  'subsActivityLabel': 'Activity',
  'profileDailyBriefing': 'Daily AI briefing',
  'profileDailyBriefingSub':
      'Start the day with account health, suspicious activity, and savings prompts',
  'profileLiveSync': 'Live data sync',
  'profileLiveSyncLive': 'Live',
  'profileLiveSyncBalanced': 'Balanced',
  'profileLiveSyncSaver': 'Saver',
  'profileAutoApprove': 'Auto-approve limit',
  'profileAutoApproveOff': 'Off',
  'profileSmartNotif': 'Smart notifications',
  'profileSmartNotifSub': 'Alerts for fraud, renewals, and approval changes',
  'profileFaceId': 'Face ID relock',
  'profileFaceIdSub': 'Require biometric unlock before sensitive actions',
  'profileFraudHigh': 'High-sensitivity fraud alerts',
  'profileFraudHighSub':
      'Let Vera flag unusual device and payment patterns earlier',
  'profileVaultTitle': 'Protected session vault',
  'profileVaultSubtitle':
      'Identity is persisted separately from local preferences.',
  'profileVaultSignIn': 'Sign-in',
  'profileVaultProtectedSince': 'Protected since',
  'profileVaultSyncMode': 'Sync mode',
  'profileVaultApproval': 'Approval guardrail',
  'profileVaultThisDevice': 'This device',
  'profileVaultManualOnly': 'Manual only',
  'profileVaultSyncLive': 'Live sync',
  'profileVaultSyncBalanced': 'Balanced sync',
  'profileVaultSyncSaver': 'Battery saver sync',
  'profileAiToneBadge': 'AI TONE / {tone}',
  'profileConnectedTitle': '{n} connected institutions',
  'profileConnectedSubtitle':
      'Live balances refresh through the current sync policy and feed cache.',
  'profileConnectedAccount': 'Account {last4}',
  'creditTitle': 'Credit',
  'creditSubtitle': 'Borrowing built around your real income.',
  'creditSummaryCardSubtitle': 'Estimate the monthly payment and debt ratio',
  'openCredit': 'Open credit',
  'wealthTitle': 'Wealth',
  'wealthSubtitle': 'Your money, working autonomously.',
  'portfolio': 'PORTFOLIO',
  'ytd': 'YTD',
  'today': 'today',
  'autonomousWealth': 'Autonomous Wealth',
  'profile': 'PROFILE',
  'moveLimit': 'MOVE LIMIT',
  'approval': 'APPROVAL',
  'activityFeed': 'Activity feed',
  'explainability': 'Explainability',
  'undo': 'Undo',
  'viewDetails': 'View details',
  'plansTitle': 'Plans',
  'plansSubtitle': 'Catch silent money leaks before they stack up.',
  'subscriptionIntelligence': 'SUBSCRIPTION INTELLIGENCE',
  'detectedPlans': 'Detected plans',
  'filterAll': 'All',
  'filterAttention': 'Needs attention',
  'filterUnused': 'Unused',
  'filterPriceChanges': 'Price changes',
  'askUma': 'Ask Uma',
  'securityTitle': 'Security',
  'securitySubtitle': 'Your live protection layer.',
  'securityStatBlockedLabel': 'BLOCKED',
  'securityStatBlockedSub': 'active',
  'securityStatReviewedLabel': 'REVIEWED',
  'securityStatReviewedSub': 'this week',
  'securityStatDevicesLabel': 'DEVICES',
  'securityStatDevicesSub': 'trusted',
  'securityAccountSection': 'ACCOUNT SECURITY',
  'securityClearBody': 'No unresolved fraud alerts in the latest scan.',
  'securityActiveBody': 'Fraud Radar is tracking {n} active alerts.',
  'securityViewReport': 'VIEW UMA REPORT',
  'securityDecisionKept':
      'You kept this event blocked. Fraud Radar will continue treating similar patterns as high risk.',
  'securityDecisionApproved':
      "You marked this event as safe. Fraud Radar will use that feedback to reduce similar false positives.",
  'securityPillBlocked': 'BLOCKED BY AI',
  'securityPillKept': 'KEPT BLOCKED',
  'securityPillApproved': 'APPROVED BY YOU',
  'profileAndSettings': 'Profile & Settings',
  'sectionAppearance': 'APPEARANCE & THEMING',
  'sectionAi': 'AI PREFERENCES',
  'sectionConnected': 'CONNECTED INSTITUTIONS',
  'sectionAccount': 'ACCOUNT',
  'sectionLanguage': 'LANGUAGE',
  'sectionNotifications': 'NOTIFICATIONS & SECURITY',
  'brandPalette': 'Brand palette',
  'mood': 'Mood',
  'moodLight': 'Light',
  'moodDark': 'Dark',
  'vibe': 'Vibe',
  'vibeCalm': 'Calm',
  'vibeStandard': 'Standard',
  'vibeBold': 'Bold',
  'language': 'Language',
  'signOut': 'Sign out',
  'umaTone': 'Uma tone',
  'toneConcise': 'Concise',
  'toneCoach': 'Coach',
  'toneProactive': 'Proactive',
  'scanReceipt': 'Scan',
  'scanReceiptTitle': 'Scan receipt or screen',
  'scanReceiptSubtitle':
      'Capture a receipt, bill, or bank screen and turn it into a transaction.',
  'scanHint':
      'AI reads the receipt, extracts category and total, then asks for your approval.',
  'takePhoto': 'Take photo',
  'pickFromGallery': 'Pick from gallery',
  'scanReading': 'AI is reading...',
  'scanTotalLabel': 'Total',
  'scanAgain': 'Scan again',
  'addToTransactions': 'Add to transactions',
  'addedToTransactions': 'Added to your transactions',
  'scanNoTotal': "Couldn't read the amount, scan again.",
  'parsedByAi': 'AI',
  'parsedFallback': 'DEMO',
  'scanFallbackWarning':
      'Gemini API key is missing or the receipt could not be parsed. Please enter it manually.',
  'scanFallbackAction': 'AI failed — enter manually',
  'savingsStoryLabel': 'SAVED THIS MONTH',
  'savingsStoryFooter': "With Uma's 3 suggestions",
  'savingsStoryDelta': '{pct}% less than last month',
  'upcomingBills': 'Upcoming bills',
  'billPayViaUma': 'Pay with Uma',
  'daysLeft': '{n} days left',
  'statementImport': 'Import statement',
  'statementImportTitle': 'Import a bank statement',
  'statementImportSubtitle':
      'Upload a PDF or image of your statement; AI extracts the transactions.',
  'pickStatementFile': 'Pick file (PDF / image)',
  'statementImportHint':
      'Your bank exports statements as PDF — Vera reads them without Open Banking access.',
  'statementParsing': 'AI is reading the statement...',
  'closingBalance': 'Closing balance',
  'detectedTransactions': '{n} transactions detected',
  'statementImportAgain': 'Import again',
  'statementImported': 'Added to your transactions',
  'statementNoTransactions': 'No transactions could be extracted.',
  'importToVera': 'Import to Vera',
  'importFallbackNextTitle': 'Next best step',
  'importFallbackNextBody':
      'You can add the transactions manually or ask Uma to log them for you.',
  'importFallbackAskUma': 'Ask Uma to log it',
  'importFallbackManualEntry': 'Add manual transaction',
  'statementFallbackWarning':
      'Gemini API key is missing or the statement could not be parsed. Please enter the transactions manually.',
  'statementFallbackAction': 'AI failed — enter manually',
  'thisMonthsAiPlan': "This month's AI plan",
  'aiPlanFooter':
      "Uma's suggestion — apply it inside your bank; Vera keeps the record.",
  'applyAtBank': 'Apply at my bank',
  'securityVeraSideBanner':
      "Vera is not a bank's security layer. It spots anomalies in your data and warns you; blocking happens together with you and your bank.",
  'statusAllClear': 'All clear',
  'statusMonitoring': 'Monitoring',
  'securityRecentActivity': 'Recent activity',
  'securityScanning': 'Scanning...',
  'liveAnomalyDetected': 'Live anomaly detected',
  'highRiskConfidence': 'High risk confidence',
  'reviewedSignal': 'Reviewed signal',
  'keepBlocked': 'Keep blocked',
  'thisWasMe': 'This was me',
  'emailField': 'Email',
  'passwordField': 'Password',
  'loginTitle': 'Sign in to Vera',
  'loginSubtitle':
      'Sign in with your account; profile preferences and AI actions stay local until you sign out.',
  'loginEmailHint': 'you@vera.app',
  'loginFooter':
      'If Firebase is not configured, sign-in will fail. Check your .env.',
  'loginDemoHint':
      'Quick try with the demo account: email "{email}", password "{password}".',
  'umaVoiceStart': 'Ask by voice',
  'umaVoiceStop': 'Stop listening',
  'umaVoiceListening': 'Listening...',
  'umaVoicePermissionDenied':
      'Microphone permission required. Enable it for Vera in system settings.',
  'umaVoiceUnavailable': 'Speech recognition is not available on this device.',
  'umaToolGoalCreated': 'Done. Created a {target} TL goal for you.',
  'umaToolBillAdded': 'Added the {name} bill, due in {days} days.',
  'umaToolExpenseAdded': 'Logged {name} ({amount} TL) as an expense.',
  'umaSuggestionSubs': 'Show my subscriptions',
  'umaSuggestionAnalyze': 'Analyze my spending',
  'voiceCommandTooltip': 'Voice command',
  'umaAuditTrailTitle': 'Audit trail',
  'umaAuditTrailEmpty': 'No signed Uma actions yet.',
  'umaAuditTrailCount': '{n} signed actions recorded on this device.',
  'accountTilePersonal': 'Personal info',
  'accountTileEmail': 'Email',
  'accountTileSecurity': 'Security & PIN',
  'accountTileStorage': 'Storage policy',
  'accountTileHelp': 'Help & support',
  'accountTileHelpValue': 'FAQ, contact',
  'infoDisplayName': 'Display name',
  'infoMember': 'Membership',
  'infoMemberDescription':
      'Vera demo account. Once a backend is wired in, real membership date and plan show up here.',
  'infoEmailLabel': 'Email address',
  'infoEmailUsage': 'Where it is used',
  'infoEmailDescription':
      'Used for the demo session. Data stays on device; nothing is sent to a server.',
  'infoSessionVault': 'Session vault',
  'infoSessionVaultDescription':
      'Session data is encrypted via flutter_secure_storage and stored locally on this device only.',
  'infoFaceId': 'Face ID',
  'infoFaceIdOn': 'On — biometric verification is requested when you sign in.',
  'infoFaceIdOff': 'Off — password / demo sign-in is enough.',
  'infoFraudAlerts': 'Fraud alerts',
  'infoFraudAlertsOn':
      'On — sends a local notification when a suspicious event is detected.',
  'infoFraudAlertsOff': 'Off — alerts only show inside the app.',
  'infoSyncMode': 'Sync mode',
  'infoLocalData': 'Local data',
  'infoLocalDataDescription':
      'OCR receipts and added banks live in SharedPreferences. "Export your data" is in the P1 backlog.',
  'infoCloudSync': 'Cloud sync',
  'infoCloudSyncActive':
      'Cloud sync is active. Imported receipts, statements, banks, profile settings, and imported transactions can sync to your Vera workspace.',
  'infoCloudSyncInactive':
      'Cloud sync is not active in this session; Vera is currently running in local-only mode.',
  'fraudAlertTitle': 'Vera • Suspicious transaction blocked',
  'googleSignInConfigMissing':
      "Google sign-in failed. The app's SHA-1 fingerprint may not be registered in the Firebase Console. The admin must update Firebase settings.",
  'fraudReasonOutlier':
      'This expense is {multiplier}× above your recent median of {median} TL. Vera found the jump worth flagging.',
  'fraudNameRoundTransfer': 'Round transfer · {amount} TL',
  'fraudReasonRoundTransfer':
      'A perfectly round amount over 10,000 TL was detected. Often a legitimate recipient transfer — confirm if it was you.',
  'fraudNameBurst': '{merchant} · {count}× same day',
  'fraudLocationBurstTotal': 'Total {total} TL',
  'fraudReasonBurst':
      'The same merchant charged {count} times today. Was it a card retry, or a real shopping spree?',
  'helpFaqQ1': 'Does Vera connect to my bank?',
  'helpFaqA1':
      'No. Vera does not hold an AISP/PSP license. You bring the data: PDF statements, receipt photos, screenshots, or manual entries. Vera combines and interprets it with AI and forwards real actions to your bank app.',
  'helpFaqQ2': 'Where is my data stored?',
  'helpFaqA2':
      'Sensitive session info goes to flutter_secure_storage (encrypted, on-device). OCR and add-bank entries go to SharedPreferences. No server, no third-party data sharing.',
  'helpFaqQ3': 'What if I do not have a Gemini API key?',
  'helpFaqA3':
      'OCR and statement import run a deterministic fallback (DEMO badge appears). UMA chat replies via a heuristic intent router. The whole flow still works — only the live AI parsing is off.',
  'helpContact': 'Contact',
  'demoUser': 'Demo user',
  'umaGreeting':
      "Hi {name}. I read your imported statements. I can analyze your spending, surface unused subscriptions, and help you set savings goals. I never move money — I'll point you to your bank app when an action is needed.",
  'umaReplySubscriptions':
      'You have {n} plans worth reviewing. Your monthly subscription total is around {total}.',
  'umaReplySubscriptionsEmpty':
      'I do not see any active subscriptions yet. Import a statement and Vera will detect recurring charges.',
  'umaReplyAnalyze':
      'Your top spending this month is {top} at {topAmount}. Total outflow {spending}. We can set per-category limits if you want.',
  'umaReplyAnalyzeEmpty':
      'No transactions to analyze yet. Scan a receipt or import a statement and we will break the spending down together.',
  'umaReplyExplainWealth':
      'Vera tracks your portfolio across the accounts you imported. Equities look slightly over-allocated this month; my suggestion is to top up gold or cash next time you open your bank.',
  'umaReplyLoan':
      'Based on the income and debt I see in your imported statements, you look strong for mid-sized personal loans. Open the credit simulation and I can help tune the amount and term for a safer fit.',
  'umaReplySecurity':
      'I flagged that transfer because the recipient appeared once before and the device location did not match your usual pattern. Vera does not block at your bank — it warns you and you decide together.',
  'umaReplyFallback':
      'I can help with that. If you want, I can give you a quick financial read or prepare a safe next step.',
  'umaReplyNeedsData':
      'I do not see enough user data yet. Import a statement, scan a receipt, add a manual transaction, or create a goal and I can help with more context.',
  'umaReplyLocalOnly':
      'I am in local mode right now. I cannot start bank actions, but I can still help you create goals, log manual transactions, and organize your data.',
  'umaReplyToolNeedsDetails':
      'I need one or two more details to finish that. Please clarify the amount, name, or due date.',
  'umaToolProposal':
      '{summary} is ready. If you want, confirm it here and I will apply it.',
  'umaThinking': 'Uma is thinking...',
  'umaAskHint': 'Ask Uma anything...',
  'umaStatusOnline': 'AI assistant · online',
  'umaNewChat': 'New chat',
  'umaConfidenceLabel': 'Confidence {pct}%',
  'umaConfirmAction': 'Confirm action',
  'umaActionConfirmedToast': 'Uma applied the action',
  'umaSourceReadiness': 'System readiness',
  'umaSourceMemory': 'User memory',
  'umaWhyGoldPlan':
      'This gold action looks aligned with the connected-account context and current savings posture.',
  'umaWhyBillPlan':
      'The upcoming payment signal and current account context support this bill action.',
  'umaWhyGoalPlan':
      'Your current goal progress and cash rhythm make this savings step look reasonable.',
  'umaWhySubscriptions':
      'This summary is grounded in your subscription list and recent recurring transactions.',
  'umaWhySpending':
      'This answer is based on the category mix I can see in your recent transactions.',
  'umaWhyWealth':
      'I am using your portfolio bucket allocation and recent asset inputs as context.',
  'umaWhyLoan':
      'I am grounding this on the income, expense, and debt rhythm visible in your data.',
  'umaWhySecurity':
      'The tone stays careful because this is a warning-oriented explanation, not a certainty.',
  'umaWhyInsufficientData':
      'I do not have enough source coverage yet to answer this with confidence.',
  'umaWhyLocalOnly':
      'When Firebase or Gemini is unavailable, I rely only on local context.',
  'umaWhyGroundedAnswer':
      'This answer was produced from the in-app data sources currently available.',
  'umaWhyFallbackSoft':
      'A little more data would let me answer this more confidently.',
  'umaWhyFallbackDirect':
      'The current data coverage is not strong enough for a confident answer, so I am avoiding guesses.',
  'umaWhyMissingContext':
      'Once the missing context is provided, I can do this more safely.',
  'umaToolExecutedWhy':
      'After your confirmation, this action was applied to Vera’s in-app data.',
  'umaPolicyNeedsConfirmation':
      'This action changes your data, so I want your confirmation first.',
  'umaPolicyMissingContext':
      'A few critical details are missing before I can do this safely.',
  'umaPolicyReady': 'The context looks sufficient and the action is ready.',
  'umaPolicyBlocked': 'This action is blocked by the current policy.',
  'umaPolicyGoalSummary': 'Create a goal for {amount}',
  'umaPolicyGoalSummaryUnknown': 'Create a goal',
  'umaPolicyBillSummary': 'Add the {name} bill due in {days} days',
  'umaPolicyBillSummaryUnknown': 'Add a bill',
  'umaPolicyExpenseSummary': 'Log {name} for {amount}',
  'umaPolicyExpenseSummaryUnknown': 'Log a manual expense',
  'umaSuggestionBuyGold': 'Buy 10g of gold',
  'umaSuggestionMoveSavings': 'Move 2500 TL to savings',
  'umaActionPolicy': 'ACTION POLICY',
  'umaActionPolicyDesc':
      'Vera never moves money itself; every action opens your bank app for your approval.',
  'umaStatusLocalOnly': 'Local mode · limited AI',
  'umaStatusNeedsData': 'Ready · waiting for data',
  'umaAssistantBadge': 'UMA',
  'umaToolBadge': 'ACTION COMPLETED',
  'umaFallbackBadge': 'NEXT STEP',
  'umaSystemBadge': 'SYSTEM',
  'umaAuditTrailTitle': 'Audit trail',
  'umaAuditTrailSubtitle':
      'Signed local log of Uma replies, forwarded bank actions, and your feedback decisions.',
  'umaAuditTrailEmpty': 'No signed Uma actions yet.',
  'umaAuditTrailCount': '{count} signed actions recorded on this device.',
  'umaAuditTrailEmptyDetail':
      'No signed actions yet. Ask Uma to do something and the trust trail will appear here.',
  'umaAuditNoteAttached': 'Note attached',
  'umaAuditReplyGenerated': 'Reply generated',
  'umaAuditForwarded': 'Forwarded to bank',
  'umaAuditKeptForReview': 'Kept for review',
  'umaAuditHelpfulFeedback': 'Helpful feedback',
  'umaAuditCorrectionFeedback': 'Correction feedback',
  'umaAuditMemoryUpdated': 'Memory updated',
  'umaAuditConfidenceReduced': 'Reduced-confidence answer',
  'categoryBudgetLabel': 'SPENDING THIS MONTH',
  'categoryOther': 'Other',
  'receiptDefaultName': 'Receipt',
  'categoryBudgetTopHint': 'Most on {category} · {pct}%',
  'categoryRemaining': '{amount} left',
  'categoryOver': 'over by {amount}',
  'categoryNoLimit': 'no limit',
  'categoryLimitEditTitle': 'Category limit',
  'categoryLimitEditSubtitle':
      'Set a monthly budget for {category}. Vera shows the remainder on every spend.',
  'categoryLimitField': 'Monthly limit (TL)',
  'categoryLimitSave': 'Save',
  'categoryLimitClear': 'Remove limit',
  'goalsSectionTitle': 'Your goals',
  'goalEmergencyFund': 'Emergency fund',
  'goalProgress': '{pct}% there',
  'goalRemaining': '{amount} to go',
  'goalEditTitle': 'Edit your goal',
  'goalEditTarget': 'Target amount (TL)',
  'goalEditSaved': 'Saved so far (TL)',
  'goalEditSave': 'Save',
  'goalEditFooter':
      "Vera tracks the balance; Uma checks in every month with a new nudge.",
  'goalEtaMonths': '{n} months to finish',
  'goalEtaReached': 'You reached it 🎯',
  'bankActionsTitle': 'Bank options',
  'bankActionsDelete': 'Delete bank',
  'bankActionsCancel': 'Cancel',
  'bankActionsConfirmTitle': 'Delete this bank?',
  'bankActionsConfirmBody':
      '{name} will be removed and stop counting toward your total balance.',
  'bankDeleted': '{name} deleted',
  'bankActionsFeedNote':
      'This bank ships with the demo data and cannot be deleted. You can remove the ones you added.',
  'umaPromptAnalyze': 'Analyze my spending this month.',
  'umaAuditTrailSubtitle': "A signed local record of Uma's replies on this device.",
  'umaAuditTrailEmptyState':
      "No signed actions yet. Talk to Uma and the trust trail will show up here.",
  'umaAuditNoteAttached': 'Note attached',
  'umaAuditActionReplyGenerated': 'Reply generated',
  'txnDetailWhen': 'When',
  'txnDetailCategory': 'Category',
  'txnDetailDirection': 'Direction',
  'txnDetailIncoming': 'Incoming',
  'txnDetailOutgoing': 'Outgoing',
  'txnDetailAskPrompt': 'Look at the {name} transaction — is {amount} normal?',
  'billDetailPrompt':
      'My {name} bill is {amount}, {days} days left. What should I do?',
  'notifTitle': 'Notifications',
  'notifSubtitle': '{n} signals Uma is watching',
  'notifEmpty': 'You\'re all clear. Uma keeps watching quietly.',
  'notifBlockedDefault': 'Vera flagged this transaction as an anomaly.',
  'notifPriceIncreaseTitle': '{name} just raised the price',
  'notifPriceIncreaseBody':
      'Monthly +{delta} · now {price}. You can freeze it from Plans.',
  'notifUnusedTitle': '{name} is going unused',
  'notifUnusedBody': 'Last seen: {last}. Vera flagged this as a silent leak.',
  'notifBillTitle': '{name} bill is approaching',
  'notifBillBody': 'Amount {amount}. Pay through Uma or your bank.',
  'proactiveBadge': 'VERA SPOTTED',
  'proactiveBillTitle': '{name} bill is approaching',
  'proactiveBillBody':
      '{amount} · {days} days left. Want Uma to prepare the payment plan?',
  'proactiveBillCta': 'Pay with Uma',
  'proactiveBillPrompt': 'Help me pay my {name} bill.',
  'proactivePriceTitle': '{name} got more expensive',
  'proactivePriceBody':
      '+{delta} monthly increase. Want to freeze the subscription?',
  'proactivePriceCta': 'Open subscriptions',
  'proactiveUnusedTitle': '{name} is unused',
  'proactiveUnusedBody': 'Last seen: {last}. Could be a silent money leak.',
  'proactiveUnusedCta': 'Open subscriptions',
  'proactiveHealthyTitle': 'No critical signal right now',
  'proactiveHealthyBody':
      'There is no urgent bill, price spike, or obviously wasted subscription at the moment. Uma can still give this period a quick read if you want.',
  'proactiveHealthyCta': 'Ask Uma for a read',
  'proactiveEmptyTitle': 'Vera has not found a signal to watch yet',
  'proactiveEmptyBody':
      'Once you import a statement, Vera surfaces upcoming payments, subscriptions, and small risks here.',
  'proactiveEmptyCta': 'Import a statement',
  'exportTile': 'Export my data',
  'exportTileValue': 'JSON · device-only',
  'exportTitle': 'Your Vera data',
  'exportSubtitle':
      'Imported transactions, banks you added, your goal and the detected subscriptions. Copy without leaving the device.',
  'exportCopy': 'Copy JSON',
  'exportCopied': 'Copied to clipboard',
  'onbStep1Title': 'Welcome to Vera',
  'onbStep1Subtitle':
      'Pick your language. You can change it anytime in settings.',
  'onbStep2Title': 'Make it yours',
  'onbStep2Subtitle':
      'Choose the brand palette and mood. Theme is editable later.',
  'onbStep3Title': 'Bring your data',
  'onbStep3Subtitle':
      "Vera doesn't connect to your bank — you bring statements, Vera makes sense of them. Start now or add later.",
  'onbContinue': 'Continue',
  'onbStart': 'Start Vera',
  'onbSkip': 'Skip',
  'onbBack': 'Back',
  'onbImportNow': 'Import a statement',
  'onbScanNow': 'Scan a receipt',
  'onbContinueWithoutImport': 'Continue without import',
  'onbPalettePreviewTitle': 'Live preview',
  'onbPalettePreviewBody':
      'Your choice instantly changes cards, AI highlights, and the overall tone.',
  'onbBlankCanvasTitle': 'Starting empty is fine too',
  'onbBlankCanvasBody':
      'If you want, continue without importing anything now; Vera will guide your first step inside as well.',
  'demoResetTile': 'Reset demo data',
  'demoResetTileValue': 'Clear imports and additions',
  'demoResetTitle': 'Reset demo data?',
  'demoResetBody':
      'Imported transactions, banks you added, and goal progress return to the starting state.',
  'demoResetConfirm': 'Reset',
  'demoResetCancel': 'Cancel',
  'demoResetDone': 'Back to demo state',
  'goalEmptyPrompt': "You haven't set a goal yet — tap to add one.",
  'goalEmptyHint':
      'Set a goal first, then let Uma estimate how much you should put aside each month.',
  'goalEmptyCta': 'Set a goal',
  'goalMonthsLabel': 'IN HOW MANY MONTHS',
  'goalMonthsOption': '{n} mo',
  'goalAdviceSummary': '{amount} per month · {months} months',
  'goalCalculate': 'Calculate',
  'goalPresetEmergency': 'Emergency (6 Mo) · {amount}',
  'goalPresetVacation': 'Vacation (3 Mo) · {amount}',
  'goalPresetCar': 'Car (12 Mo) · {amount}',
  'fieldName': 'Name',
  'fieldAmountTl': 'Amount (TL)',
  'fieldDate': 'Date',
  'fieldCategory': 'Category',
  'fieldDescription': 'Description',
  'fieldLabelOptional': 'Label (optional)',
  'actionAdd': 'Add',
  'actionUpdate': 'Update',
  'actionDelete': 'Delete',
  'actionManual': 'Manual',
  'addBillTitle': 'Add new bill',
  'editBillTitle': 'Edit bill',
  'addBillNameHint': 'e.g. Turk Telekom',
  'dueDateLabel': 'Due date',
  'addBillCta': 'Add bill',
  'noTrackedBillsTitle': 'No tracked bills yet',
  'noTrackedBillsBody': 'Vera reminds you one day before the due date.',
  'billKindCard': 'Card',
  'billKindInternet': 'Internet',
  'billKindElectric': 'Electricity',
  'billKindWater': 'Water',
  'billKindGas': 'Gas',
  'billKindRent': 'Rent',
  'billKindOther': 'Other',
  'addManualTxnTitle': 'Add manual transaction',
  'txnTypeExpense': 'Expense',
  'txnTypeIncome': 'Income',
  'addManualTxnNameHint': 'e.g. Migros',
  'aiSuggestionLabel': 'Uma suggestion',
  'acceptSuggestion': 'Accept',
  'categoryMarket': 'Groceries',
  'categoryFood': 'Food & Drink',
  'categoryFuel': 'Fuel',
  'categoryBill': 'Bills',
  'categoryHealth': 'Health',
  'categoryEducation': 'Education',
  'categoryEntertainment': 'Entertainment',
  'categoryTransfer': 'Transfer',
  'categorySalary': 'Salary',
  'categorySubscription': 'Subscription',
  'categoryMusic': 'Music',
  'categoryVideo': 'Video',
  'categoryStorage': 'Storage',
  'categoryDeveloper': 'Developer',
  'categoryAi': 'AI',
  'noTransactionsTitle': 'No transactions yet',
  'noTransactionsBody':
      'Add your first transaction, import a statement, or scan a receipt.',
  'addHoldingTitle': 'Add holding to portfolio',
  'addHoldingSubtitle':
      'Pick one of the buckets below and enter its TL value. Uma recalculates the weights automatically.',
  'addHoldingHint': 'e.g. THYAO or XU100 ETF',
  'holdingValueLabel': 'Value (TL)',
  'removeHolding': 'Remove this holding',
  'noWealthActionsTitle': 'Uma has not taken action yet',
  'noWealthActionsBody':
      'Once you enable autonomous mode, recommendations and rebalance moves will show up here.',
  'startPortfolioTitle': 'Start building your portfolio',
  'startPortfolioBody':
      'Add equities, gold, cash, or crypto holdings. Uma tracks drift and writes suggestions here.',
  'wealthApprovalAuto': 'Auto',
  'wealthApprovalHybrid': 'Hybrid',
  'wealthActionReversed': 'REVERSED',
  'holdingBucketEquity': 'Equity',
  'holdingBucketGold': 'Gold',
  'holdingBucketCash': 'Cash',
  'holdingBucketCrypto': 'Crypto',
  'holdingBucketFunds': 'Fund',
  'holdingBucketBonds': 'Bond',
  'subscriptionsAttentionCount': '{n} plans need attention this cycle',
  'noSubscriptionsDetectedTitle': 'No detected subscriptions yet',
  'noSubscriptionsDetectedBody':
      'Import a statement or scan a receipt — Vera will automatically detect recurring payments.',
  'noSubscriptionsForFilterTitle': 'No subscriptions match this filter',
  'noSubscriptionsForFilterBody': 'Try the other filters.',
  'subsAlertSavingsTitle': 'Monthly savings potential',
  'subsAlertSavingsMessageEmpty':
      'No subscriptions detected yet. Import a statement or add one manually and Vera will track it.',
  'subsAlertSavingsMessageActive':
      'Vera found subscriptions you can freeze or downgrade without disrupting your routine.',
  'subsAlertSavingsMetric': 'SAVINGS',
  'subsAlertPriceTitle': 'Price increase detected',
  'subsAlertPriceMessageNone': 'No unusual price spikes this cycle.',
  'subsAlertPriceMessageSome':
      'One or more plans increased in price compared with last month.',
  'subsAlertPriceMetric': 'UP',
  'subsAlertUnusedTitle': 'Lightly used plans',
  'subsAlertUnusedMessageNone': 'All subscriptions look healthy.',
  'subsAlertUnusedMessageSome':
      '{n} plans appear lightly used based on your recent activity pattern.',
  'subsAlertUnusedMetric': 'IDLE',
  'subsInsightEmpty':
      'Vera analyzes your statements or receipts and groups your subscriptions here.',
  'subsInsightHealthy':
      'Your subscriptions look healthy this month. No urgent savings leak is visible.',
  'subsInsightNeedsAttention':
      'You have {n} subscriptions worth reviewing. Vera estimates you could recover about {amount} per month by freezing unused ones and downgrading the pricier ones.',
  'subsDetectedFromImport': 'Detected from an imported transaction',
  'subsSeenInRecentTransactions': 'Seen {n}× in recent transactions',
  'subsKnownVendorLabel': 'Known subscription vendor',
  'subsRecommendationDetected':
      'Vera detected this subscription from an imported statement. Are you still using it?',
  'subsStatusActive': 'ACTIVE',
  'subsStatusPriceUp': 'PRICE UP',
  'subsStatusUnused': 'UNUSED',
  'subsStatusRenewsSoon': 'RENEWS SOON',
  'securityEmptyTitle': 'There is no alert to review right now',
  'securityEmptyBody':
      'Vera fraud radar quietly watches your devices and imported transactions. If something happens, it appears here.',
  'close': 'Close',
  'wealthInsightAddPortfolio':
      'Autonomous mode is off. Add your portfolio so Uma can track drift and suggest moves.',
  'wealthInsightPaused':
      'Autonomous mode is paused. Vera still watches drift but will wait for your approval before moving money.',
  'wealthInsightActive':
      'Uma is active with the "{profile}" policy. Within the monthly {limit} TL limit, it has made or prepared {count} portfolio adjustments.',
  'goalReached': 'You reached your goal. You can set a new one now.',
  'goalRemainingPlan':
      'To save the remaining {remaining} TL in {months} months, you need to set aside {monthly} TL each month.',
  'goalNarrativeNewTarget': 'You can set a new amount for your goal.',
  'goalNarrativeNoData':
      'No transaction data yet. Import a statement or add a few manual entries so Uma can tailor a plan for you.',
  'goalNarrativeTrim':
      'You need to set aside {monthly} TL per month. Starting with small trims from your {topCategory} budget makes sense.',
  'todayAt': 'Today, {time}',
  'loginContinueEmail': 'Continue with email',
  'loginEmailPasswordRequired': 'Email and password are required.',
  'loginFirebaseError': 'Firebase sign-in failed: {code}.',
  'loginFirebaseReadyFooter':
      'Firebase auth is connected. Demo mode is still available for hackathon flows.',
  'loginCreateAccount': 'Create account',
  'dividerOr': 'or',
  'signupTitle': 'Create your account',
  'signupSubtitleFirebase':
      'Your Vera identity and profile will sync through Firebase.',
  'signupSubtitleLocal':
      'Firebase is not configured yet. This flow will continue in local demo mode.',
  'signupFieldFullName': 'Full name',
  'signupFieldEmail': 'Email',
  'signupFieldPassword': 'Password',
  'signupFieldConfirmPassword': 'Confirm password',
  'signupErrorNameRequired': 'Please enter your full name.',
  'signupErrorInvalidEmail': 'Please enter a valid email.',
  'signupErrorShortPassword': 'Password must be at least 6 characters.',
  'signupErrorPasswordMismatch': 'Passwords do not match.',
  'signupErrorAcceptTerms': 'Please accept the terms to continue.',
  'signupFailedTemplate': 'Account creation failed: {code}.',
  'signupTerms': 'I accept Vera terms and the local demo data policy.',
  'signupStrengthWeak': 'Weak',
  'signupStrengthMedium': 'Medium',
  'signupStrengthStrong': 'Strong',
  'signupCtaCreate': 'Sign up',
  'signupCtaContinueLocal': 'Continue as demo',
  'signupAlreadyHaveAccount': 'Already have an account? ',
  'signupSignIn': 'Sign in',
  'demoSampleLoaded': 'Sample account data loaded.',
  'demoBankPrimary': 'Vera Bank — Checking',
  'demoBankSavings': 'Vera Bank — Savings',
  'demoBillCreditCard': 'Credit card statement',
  'demoBillElectric': 'Electricity bill',
  'demoBillInternet': 'Internet bill',
  'demoTxnSalary': 'Salary payment',
  'demoTxnGrocery': 'Grocery shopping',
  'demoTxnFuel': 'Fuel',
  'demoTxnRestaurant': 'Restaurant',
  'demoTxnPharmacy': 'Pharmacy',
  'demoTxnRent': 'Rent payment',
  'demoTxnTransfer': 'Transfer — Savings account',
  'demoTxnFamilyIncoming': 'Incoming transfer — Family',
  'demoTxnAtm': 'ATM cash withdrawal',
  'deleteAccount': 'Delete account',
  'deleteAccountTile': 'Delete account',
  'deleteAccountTileValue': 'Remove cloud data and sign out',
  'deleteAccountDemoTileValue': 'Clear demo data on this device',
  'deleteAccountTitle': 'Delete this account?',
  'deleteAccountBody':
      'Your Vera account, synced data, and on-device cache will be permanently deleted. This action cannot be undone.',
  'deleteAccountDemoBody':
      'This will clear the demo account and remove local data from this device. This action cannot be undone.',
  'deleteAccountConfirm': 'Delete account',
  'deleteAccountCancel': 'Cancel',
  'deleteAccountProcessing': 'Deleting account...',
  'deleteAccountDone': 'Account deleted.',
  'deleteAccountError':
      'Account deletion failed. Please sign in again and retry.',
  'deleteAccountRecentLogin':
      'For security, please sign in again before deleting your account.',
  'continueWithGoogle': 'Continue with Google',
  'googleSignInUnavailable':
      'Google Sign-In needs Firebase to be configured for this build.',
};
