part of '../app_strings.dart';

const Map<String, String> _ruStrings = {
  'navHome': 'Главная',
  'navWealth': 'Капитал',
  'navPlans': 'Планы',
  'navSecurity': 'Защита',
  'navUma': 'UMA',
  'helloLabel': 'Привет,',
  'defaultUserName': 'Пользователь Vera',
  'totalNetWorth': 'ОБЩИЙ КАПИТАЛ',
  'liveFeed': 'ОНЛАЙН',
  'syncing': 'СИНХРО',
  'thisMonth': 'в этом месяце',
  'connectedAccounts': 'Подключённые счета',
  'refresh': 'Обновить',
  'syncingDots': 'Синхронизация...',
  'recentTransactions': 'Последние операции',
  'itemsCount': '{n} операций',
  'itemsVisible': 'видно',
  'connectBank': 'Подключить банк',
  'homeFirstStepsTitle': 'Сделаем первый шаг вместе',
  'homeFirstStepsBody':
      'Vera становится заметно полезнее после появления первых данных. Импортируйте выписку, отсканируйте чек или добавьте банк, чтобы оживить главный экран.',
  'homeFirstStepsHint':
      'Даже одного такого шага достаточно, чтобы появились подсказки, балансы и умные уведомления.',
  'connectedAccountsEmptyTitle': 'Пока нет подключённых счетов',
  'connectedAccountsEmptyBody':
      'Когда вы добавите банк, мы сможем показывать баланс на главном экране и готовить действия Uma с более точным контекстом.',
  'addBankTitle': 'Добавить банк',
  'addBankSubtitle':
      'Vera не подключается к банкам — вы добавляете и отслеживаете баланс.',
  'addBankName': 'Название банка',
  'addBankLast4': 'Последние 4 цифры',
  'addBankBalance': 'Баланс (TL)',
  'addBankColor': 'Цвет',
  'addBankSave': 'Добавить банк',
  'addBankNameRequired': 'Название банка обязательно.',
  'bankAdded': '{name} добавлен',
  'umaInsight': 'ИНСАЙТ UMA',
  'umaInsightNoData':
      'Vera пока вас не знает. Импортируйте выписку, отсканируйте чек или добавьте банк, чтобы мы вместе начали строить более умные подсказки.',
  'umaInsightNoTransactions':
      'Пока не видно ни одной операции. Импортируйте первую выписку или добавьте операцию вручную, чтобы Uma поняла ваш ритм расходов.',
  'umaInsightNoPattern':
      'Для этого периода пока нет достаточно внятного паттерна расходов. Когда появятся новые операции, инсайт здесь станет точнее.',
  'umaInsightTopCategory':
      'Больше всего вы потратили на {category}: {amount}, это около {share}% от проанализированного общего объёма {total}.',
  'umaInsightImportCta': 'Импортировать выписку',
  'umaInsightAddFirstTxnCta': 'Добавить первую операцию',
  'umaInsightDeepenCta': 'Углубить с Uma',
  'spent': 'Расход',
  'incoming': 'Доход',
  'creditTitle': 'Кредит',
  'creditSubtitle': 'Кредит на основе реального дохода.',
  'creditSummaryCardSubtitle': 'Расчёт месячного платежа и долговой нагрузки',
  'openCredit': 'Открыть кредит',
  'wealthTitle': 'Капитал',
  'wealthSubtitle': 'Ваши деньги работают сами.',
  'portfolio': 'ПОРТФЕЛЬ',
  'ytd': 'С НГ',
  'today': 'сегодня',
  'autonomousWealth': 'Автономный капитал',
  'profile': 'ПРОФИЛЬ',
  'moveLimit': 'ЛИМИТ',
  'approval': 'УТВЕРЖД.',
  'activityFeed': 'Активность',
  'explainability': 'Объяснимость',
  'undo': 'Отменить',
  'viewDetails': 'Подробнее',
  'plansTitle': 'Планы',
  'plansSubtitle': 'Ловите тихие утечки денег.',
  'subscriptionIntelligence': 'АНАЛИЗ ПОДПИСОК',
  'detectedPlans': 'Найденные планы',
  'filterAll': 'Все',
  'filterAttention': 'Нужно внимание',
  'filterUnused': 'Неиспользуемые',
  'filterPriceChanges': 'Изменение цены',
  'askUma': 'Спросить UMA',
  'securityTitle': 'Защита',
  'securitySubtitle': 'Активный уровень защиты.',
  'profileAndSettings': 'Профиль и настройки',
  'sectionAppearance': 'ВНЕШНИЙ ВИД',
  'sectionAi': 'НАСТРОЙКИ ИИ',
  'sectionConnected': 'ПОДКЛЮЧЁННЫЕ ОРГАНИЗАЦИИ',
  'sectionAccount': 'АККАУНТ',
  'sectionLanguage': 'ЯЗЫК',
  'brandPalette': 'Палитра бренда',
  'mood': 'Тема',
  'moodLight': 'Светлая',
  'moodDark': 'Тёмная',
  'vibe': 'Стиль',
  'vibeCalm': 'Спокойный',
  'vibeStandard': 'Стандартный',
  'vibeBold': 'Яркий',
  'language': 'Язык',
  'signOut': 'Выйти',
  'umaTone': 'Тон Uma',
  'toneConcise': 'Кратко',
  'toneCoach': 'Коуч',
  'toneProactive': 'Проактивно',
  'scanReceipt': 'Сканер',
  'scanReceiptTitle': 'Сканировать чек или экран',
  'scanReceiptSubtitle':
      'Снимите чек, счёт или экран банка — ИИ превратит его в операцию.',
  'scanHint':
      'ИИ читает чек, выделяет категорию и сумму, спрашивает подтверждение.',
  'takePhoto': 'Сделать фото',
  'pickFromGallery': 'Из галереи',
  'scanReading': 'ИИ читает...',
  'scanTotalLabel': 'Итого',
  'scanAgain': 'Сканировать снова',
  'addToTransactions': 'Добавить к операциям',
  'scanNoTotal': 'Сумма не распознана, отсканируйте снова.',
  'addedToTransactions': 'Добавлено',
  'parsedByAi': 'ИИ',
  'parsedFallback': 'DEMO',
  'scanFallbackWarning':
      'Ключ Gemini API отсутствует или чек не удалось разобрать. Пожалуйста, введите операцию вручную.',
  'scanFallbackAction': 'ИИ не сработал — ввести вручную',
  'savingsStoryLabel': 'СБЕРЕЖЕНО ЗА МЕСЯЦ',
  'savingsStoryFooter': 'Благодаря 3 советам Uma',
  'savingsStoryDelta': 'На {pct}% меньше, чем в прошлом месяце',
  'upcomingBills': 'Предстоящие платежи',
  'billPayViaUma': 'Оплатить через Uma',
  'daysLeft': 'осталось {n} дн.',
  'statementImport': 'Импорт выписки',
  'statementImportTitle': 'Импорт банковской выписки',
  'statementImportSubtitle':
      'Загрузите PDF или скриншот выписки; ИИ извлечёт операции.',
  'pickStatementFile': 'Выбрать файл (PDF / изображение)',
  'statementImportHint':
      'Банк отдаёт выписку в PDF — Vera читает её без подключения к Open Banking.',
  'statementParsing': 'ИИ читает выписку...',
  'closingBalance': 'Остаток',
  'detectedTransactions': 'Найдено {n} операций',
  'statementImportAgain': 'Импорт ещё раз',
  'statementNoTransactions': 'Не удалось извлечь операции.',
  'statementImported': 'Добавлено в ваши операции',
  'importToVera': 'Импорт в Vera',
  'statementFallbackWarning':
      'Ключ Gemini API отсутствует или выписку не удалось разобрать. Пожалуйста, введите операции вручную.',
  'statementFallbackAction': 'ИИ не сработал — ввести вручную',
  'thisMonthsAiPlan': 'План ИИ на этот месяц',
  'aiPlanFooter': 'Совет Uma — выполните в своём банке; Vera ведёт учёт.',
  'applyAtBank': 'Сделать в банке',
  'securityVeraSideBanner':
      'Vera не является службой безопасности банка. Она замечает аномалии в ваших данных и предупреждает вас; блокировку вы решаете вместе с банком.',
  'statusAllClear': 'Всё чисто',
  'statusMonitoring': 'Наблюдение',
  'securityRecentActivity': 'Недавняя активность',
  'securityScanning': 'Сканирование...',
  'liveAnomalyDetected': 'Аномалия обнаружена',
  'highRiskConfidence': 'Высокий риск',
  'reviewedSignal': 'Проверено',
  'keepBlocked': 'Оставить заблокированным',
  'thisWasMe': 'Это был я',
  'emailField': 'E-mail',
  'passwordField': 'Пароль',
  'loginDemoHint':
      'Быстрый вход в демо-аккаунт: e-mail «{email}», пароль «{password}».',
  'umaVoiceStart': 'Спросить голосом',
  'umaVoiceStop': 'Остановить запись',
  'umaVoiceListening': 'Слушаю...',
  'umaVoicePermissionDenied':
      'Нужен доступ к микрофону. Разрешите для Vera в настройках устройства.',
  'umaVoiceUnavailable': 'Распознавание речи недоступно на этом устройстве.',
  'umaToolGoalCreated': 'Готово. Создана цель на {target} TL.',
  'umaToolBillAdded': 'Добавлен счёт {name}, к оплате через {days} дн.',
  'umaToolExpenseAdded': 'Расход {name} ({amount} TL) записан.',
  'umaSuggestionSubs': 'Показать подписки',
  'umaSuggestionAnalyze': 'Анализировать траты',
  'voiceCommandTooltip': 'Голосовая команда',
  'umaAuditTrailTitle': 'Журнал аудита',
  'umaAuditTrailEmpty': 'Пока нет подписанных действий Uma.',
  'umaAuditTrailCount': 'На этом устройстве записано {n} подписанных действий.',
  'accountTilePersonal': 'Личные данные',
  'accountTileEmail': 'E-mail',
  'accountTileSecurity': 'Безопасность и PIN',
  'accountTileStorage': 'Политика хранения',
  'accountTileHelp': 'Помощь и поддержка',
  'infoDisplayName': 'Отображаемое имя',
  'infoMember': 'Членство',
  'infoMemberDescription':
      'Демо-аккаунт Vera. После подключения бэкенда здесь появятся дата регистрации и план.',
  'infoEmailLabel': 'Адрес электронной почты',
  'infoEmailUsage': 'Где используется',
  'infoEmailDescription':
      'Используется для демо-сессии. Данные остаются на устройстве, на сервер ничего не отправляется.',
  'infoSessionVault': 'Хранилище сессии',
  'infoSessionVaultDescription':
      'Данные сессии шифруются через flutter_secure_storage и хранятся только на этом устройстве.',
  'infoFaceId': 'Face ID',
  'infoFaceIdOn': 'Вкл. — при входе требуется биометрическая проверка.',
  'infoFaceIdOff': 'Выкл. — достаточно пароля / демо-входа.',
  'infoFraudAlerts': 'Оповещения о мошенничестве',
  'infoFraudAlertsOn':
      'Вкл. — при подозрительной операции отправляется локальное уведомление.',
  'infoFraudAlertsOff': 'Выкл. — оповещения показываются только в приложении.',
  'infoSyncMode': 'Режим синхронизации',
  'infoLocalData': 'Локальные данные',
  'infoLocalDataDescription':
      'OCR-чеки и добавленные банки хранятся в SharedPreferences. "Экспорт данных" — в P1-бэклоге.',
  'infoCloudSync': 'Облачная синхронизация',
  'infoCloudSyncActive':
      'Облачная синхронизация активна. Импортированные чеки, выписки, банки, настройки профиля и операции могут синхронизироваться в ваше пространство Vera.',
  'infoCloudSyncInactive':
      'Облачная синхронизация в этой сессии не активна; Vera работает только локально.',
  'fraudAlertTitle': 'Vera • Подозрительная операция заблокирована',
  'googleSignInConfigMissing':
      'Не удалось войти через Google. Возможно, отпечаток SHA-1 приложения не зарегистрирован в Firebase Console. Администратор должен обновить настройки Firebase.',
  'fraudReasonOutlier':
      'Эта трата в {multiplier}× выше вашей недавней медианы в {median} TL. Vera посчитала скачок заметным.',
  'fraudNameRoundTransfer': 'Круглый перевод · {amount} TL',
  'fraudReasonRoundTransfer':
      'Обнаружена круглая сумма свыше 10 000 TL. Часто это легитимный перевод получателю — подтвердите, если это были вы.',
  'fraudNameBurst': '{merchant} · {count}× за день',
  'fraudLocationBurstTotal': 'Всего {total} TL',
  'fraudReasonBurst':
      'Сегодня тот же продавец списал {count} раз. Повтор карты или реальный шопинг?',
  'helpFaqQ1': 'Vera подключается к моему банку?',
  'helpFaqA1':
      'Нет. У Vera нет лицензии AISP/PSP. Данные приносите вы: PDF-выписки, фото чеков, скриншоты или ручной ввод. Vera объединяет их с помощью ИИ и направляет действия в ваше банковское приложение.',
  'helpFaqQ2': 'Где хранятся мои данные?',
  'helpFaqA2':
      'Чувствительные данные сессии — flutter_secure_storage (шифрование, на устройстве). OCR и записи о банках — SharedPreferences. Сервера нет, третьим лицам данные не передаются.',
  'helpFaqQ3': 'Что если нет ключа Gemini API?',
  'helpFaqA3':
      'OCR и импорт выписок работают через детерминированный fallback (появляется бейдж DEMO). UMA отвечает через эвристический intent-роутер. Весь поток работает — отключён только live-парсинг ИИ.',
  'helpContact': 'Контакт',
  'demoUser': 'Демо-пользователь',
  'umaThinking': 'Uma думает...',
  'umaAskHint': 'Спросите Uma...',
  'umaStatusOnline': 'ИИ-ассистент · онлайн',
  'onbStep1Title': 'Добро пожаловать в Vera',
  'onbStep1Subtitle':
      'Сначала выберите язык. Позже его всегда можно поменять в настройках.',
  'onbStep2Title': 'Сделайте под себя',
  'onbStep2Subtitle':
      'Выберите палитру и настроение бренда. Тему можно изменить и позже.',
  'onbStep3Title': 'Добавьте свои данные',
  'onbStep3Subtitle':
      'Vera не подключается к вашему банку — вы приносите выписки, а Vera помогает их понять. Начните сейчас или добавьте позже.',
  'onbContinue': 'Продолжить',
  'onbStart': 'Открыть Vera',
  'onbSkip': 'Пропустить',
  'onbBack': 'Назад',
  'onbImportNow': 'Импортировать выписку',
  'onbScanNow': 'Сканировать чек',
  'onbContinueWithoutImport': 'Продолжить без импорта',
  'onbPalettePreviewTitle': 'Живой предпросмотр',
  'onbPalettePreviewBody':
      'Ваш выбор сразу меняет карточки, AI-акценты и общее настроение интерфейса.',
  'onbBlankCanvasTitle': 'Начать с пустого экрана тоже нормально',
  'onbBlankCanvasBody':
      'Если хотите, продолжайте сейчас без импорта; Vera подскажет вам и первый шаг уже внутри приложения.',
  'goalEmptyPrompt': 'Вы ещё не задали цель — нажмите, чтобы добавить.',
  'goalEmptyHint':
      'Сначала задайте цель, и Uma подскажет, сколько стоит откладывать каждый месяц в вашем ритме.',
  'goalEmptyCta': 'Задать цель',
  'goalMonthsLabel': 'ЗА СКОЛЬКО МЕСЯЦЕВ',
  'goalMonthsOption': '{n} мес.',
  'goalAdviceSummary': '{amount} в месяц · {months} мес.',
  'goalCalculate': 'Рассчитать',
  'goalPresetEmergency': 'НЗ (6 мес) · {amount}',
  'goalPresetVacation': 'Отпуск (3 мес) · {amount}',
  'goalPresetCar': 'Автомобиль (12 мес) · {amount}',
  'fieldName': 'Название',
  'fieldAmountTl': 'Сумма (TL)',
  'fieldDate': 'Дата',
  'fieldCategory': 'Категория',
  'fieldDescription': 'Описание',
  'fieldLabelOptional': 'Метка (необязательно)',
  'actionAdd': 'Добавить',
  'actionUpdate': 'Обновить',
  'actionDelete': 'Удалить',
  'actionManual': 'Вручную',
  'addBillTitle': 'Добавить новый счёт',
  'editBillTitle': 'Редактировать счёт',
  'addBillNameHint': 'например, Turk Telekom',
  'dueDateLabel': 'Срок оплаты',
  'addBillCta': 'Добавить счёт',
  'noTrackedBillsTitle': 'Пока нет отслеживаемых счетов',
  'noTrackedBillsBody': 'Vera напомнит за день до срока оплаты.',
  'billKindCard': 'Карта',
  'billKindInternet': 'Интернет',
  'billKindElectric': 'Электричество',
  'billKindWater': 'Вода',
  'billKindGas': 'Газ',
  'billKindRent': 'Аренда',
  'billKindOther': 'Другое',
  'addManualTxnTitle': 'Добавить операцию вручную',
  'txnTypeExpense': 'Расход',
  'txnTypeIncome': 'Доход',
  'addManualTxnNameHint': 'например, Migros',
  'aiSuggestionLabel': 'Подсказка Uma',
  'acceptSuggestion': 'Принять',
  'categoryMarket': 'Маркет',
  'categoryFood': 'Еда и напитки',
  'categoryFuel': 'Топливо',
  'categoryBill': 'Счета',
  'categoryHealth': 'Здоровье',
  'categoryEducation': 'Образование',
  'categoryEntertainment': 'Развлечения',
  'categoryTransfer': 'Перевод',
  'categorySalary': 'Зарплата',
  'categorySubscription': 'Подписка',
  'categoryMusic': 'Музыка',
  'categoryVideo': 'Видео',
  'categoryStorage': 'Хранилище',
  'categoryDeveloper': 'Разработка',
  'categoryAi': 'ИИ',
  'noTransactionsTitle': 'Операций пока нет',
  'noTransactionsBody':
      'Добавьте первую операцию, импортируйте выписку или отсканируйте чек.',
  'addHoldingTitle': 'Добавить актив в портфель',
  'addHoldingSubtitle':
      'Выберите один из классов ниже и введите стоимость в TL. Uma автоматически пересчитает веса.',
  'addHoldingHint': 'например, THYAO или XU100 ETF',
  'holdingValueLabel': 'Стоимость (TL)',
  'removeHolding': 'Удалить этот актив',
  'noWealthActionsTitle': 'Uma ещё не предпринимала действий',
  'noWealthActionsBody':
      'Когда вы включите автономный режим, здесь появятся рекомендации и ребалансировки.',
  'startPortfolioTitle': 'Начните собирать портфель',
  'startPortfolioBody':
      'Добавьте акции, золото, наличные или криптоактивы. Uma будет следить за отклонениями и писать сюда советы.',
  'wealthApprovalAuto': 'Авто',
  'wealthApprovalHybrid': 'Гибрид',
  'wealthActionReversed': 'ОТМЕНЕНО',
  'holdingBucketEquity': 'Акции',
  'holdingBucketGold': 'Золото',
  'holdingBucketCash': 'Наличные',
  'holdingBucketCrypto': 'Крипто',
  'holdingBucketFunds': 'Фонд',
  'holdingBucketBonds': 'Облигации',
  'subscriptionsAttentionCount': 'В этом цикле {n} планам нужно внимание',
  'noSubscriptionsDetectedTitle': 'Подписки пока не обнаружены',
  'noSubscriptionsDetectedBody':
      'Импортируйте выписку или отсканируйте чек — Vera автоматически найдёт регулярные платежи.',
  'noSubscriptionsForFilterTitle': 'Нет подписок для этого фильтра',
  'noSubscriptionsForFilterBody': 'Попробуйте другие фильтры.',
  'subsAlertSavingsTitle': 'Потенциал ежемесячной экономии',
  'subsAlertSavingsMessageEmpty':
      'Подписки пока не найдены. Импортируйте выписку или добавьте подписку вручную, и Vera начнёт её отслеживать.',
  'subsAlertSavingsMessageActive':
      'Vera нашла подписки, которые можно заморозить или перевести на более дешёвый план без ущерба для вашего ритма.',
  'subsAlertSavingsMetric': 'ЭКОНОМИЯ',
  'subsAlertPriceTitle': 'Обнаружено повышение цены',
  'subsAlertPriceMessageNone': 'В этом цикле нет необычных скачков цены.',
  'subsAlertPriceMessageSome':
      'Один или несколько планов подорожали по сравнению с прошлым месяцем.',
  'subsAlertPriceMetric': 'РОСТ',
  'subsAlertUnusedTitle': 'Редко используемые планы',
  'subsAlertUnusedMessageNone': 'Все подписки выглядят здоровыми.',
  'subsAlertUnusedMessageSome':
      'По вашему недавнему паттерну активности {n} планов выглядят малоиспользуемыми.',
  'subsAlertUnusedMetric': 'ПУСТО',
  'subsInsightEmpty':
      'Vera анализирует ваши выписки или чеки и собирает подписки здесь.',
  'subsInsightHealthy':
      'В этом месяце подписки выглядят здоровыми. Срочной утечки экономии не видно.',
  'subsInsightNeedsAttention':
      'У вас есть {n} подписок, которые стоит проверить. Vera оценивает, что вы можете вернуть около {amount} в месяц, если заморозите неиспользуемые и понизите более дорогие планы.',
  'subsDetectedFromImport': 'Обнаружено по импортированной операции',
  'subsSeenInRecentTransactions': 'Встречалось {n}× в недавних операциях',
  'subsKnownVendorLabel': 'Известный поставщик подписки',
  'subsRecommendationDetected':
      'Vera обнаружила эту подписку в импортированной выписке. Вы всё ещё ей пользуетесь?',
  'subsStatusActive': 'АКТИВНА',
  'subsStatusPriceUp': 'ЦЕНА ВЫРОСЛА',
  'subsStatusUnused': 'МАЛО ИСПОЛЬЗУЕТСЯ',
  'subsStatusRenewsSoon': 'СКОРО ПРОДЛИТСЯ',
  'proactiveBadge': 'VERA ЗАМЕТИЛА',
  'proactiveBillTitle': 'Счёт {name} скоро подойдёт',
  'proactiveBillBody':
      '{amount} · осталось {days} дн. Попросить Uma подготовить оплату?',
  'proactiveBillCta': 'Оплатить через Uma',
  'proactiveBillPrompt': 'Помоги мне оплатить счёт {name}.',
  'proactivePriceTitle': '{name} подорожал',
  'proactivePriceBody': '+{delta} в месяц. Хотите заморозить подписку?',
  'proactivePriceCta': 'Открыть подписки',
  'proactiveUnusedTitle': '{name} почти не используется',
  'proactiveUnusedBody':
      'Последнее использование: {last}. Это может быть тихой утечкой денег.',
  'proactiveUnusedCta': 'Открыть подписки',
  'proactiveHealthyTitle': 'Сейчас нет критических сигналов',
  'proactiveHealthyBody':
      'Сейчас не видно ни срочного счёта, ни скачка цены, ни явно бесполезной подписки. Если хотите, Uma всё равно может быстро оценить этот период.',
  'proactiveHealthyCta': 'Попросить Uma оценить',
  'proactiveEmptyTitle': 'Vera пока не нашла сигнал для отслеживания',
  'proactiveEmptyBody':
      'После импорта выписки Vera будет показывать здесь ближайшие платежи, подписки и небольшие риски.',
  'proactiveEmptyCta': 'Импортировать выписку',
  'securityEmptyTitle': 'Сейчас нет предупреждений для проверки',
  'securityEmptyBody':
      'Радар мошенничества Vera тихо следит за вашими устройствами и импортированными транзакциями. Если что-то случится, это появится здесь.',
  'close': 'Закрыть',
  'categoryOther': 'Прочее',
  'receiptDefaultName': 'Чек',
  'wealthInsightAddPortfolio':
      'Автономный режим выключен. Добавь портфель, чтобы Uma отслеживала отклонения и предлагала шаги.',
  'wealthInsightPaused':
      'Автономный режим приостановлен. Vera следит за отклонениями, но ждёт твоего подтверждения перед движением средств.',
  'wealthInsightActive':
      'Uma активна с политикой "{profile}". В пределах месячного лимита {limit} TL выполнено или подготовлено {count} корректировок портфеля.',
  'goalReached': 'Цель достигнута. Можно поставить новую.',
  'goalRemainingPlan':
      'Чтобы накопить оставшиеся {remaining} TL за {months} мес., нужно откладывать {monthly} TL в месяц.',
  'goalNarrativeNewTarget': 'Можно задать новую сумму для цели.',
  'goalNarrativeNoData':
      'Пока нет данных о транзакциях. Импортируй выписку или добавь несколько записей вручную, чтобы Uma предложила план.',
  'goalNarrativeTrim':
      'Нужно откладывать {monthly} TL в месяц. Начать стоит с небольших сокращений по категории {topCategory}.',
  'todayAt': 'Сегодня, {time}',
  'loginContinueEmail': 'Продолжить с email',
  'loginEmailPasswordRequired': 'Email и пароль обязательны.',
  'loginFirebaseError': 'Ошибка входа Firebase: {code}.',
  'loginFirebaseReadyFooter':
      'Firebase auth подключён. Демо-режим остаётся доступным для hackathon-сценариев.',
  'loginCreateAccount': 'Создать аккаунт',
  'dividerOr': 'или',
  'signupTitle': 'Создайте аккаунт',
  'signupSubtitleFirebase':
      'Создайте аккаунт — ваш профиль Vera и данные будут безопасно синхронизироваться.',
  'signupSubtitleLocal':
      'Сервер не настроен. Поток продолжится в локальном демо-режиме на этом устройстве.',
  'signupFieldFullName': 'Полное имя',
  'signupFieldEmail': 'Email',
  'signupFieldPassword': 'Пароль',
  'signupFieldConfirmPassword': 'Подтвердите пароль',
  'signupErrorNameRequired': 'Введите полное имя.',
  'signupErrorInvalidEmail': 'Введите корректный email.',
  'signupErrorShortPassword': 'Пароль должен быть не короче 6 символов.',
  'signupErrorPasswordMismatch': 'Пароли не совпадают.',
  'signupErrorAcceptTerms': 'Примите условия, чтобы продолжить.',
  'signupFailedTemplate': 'Не удалось создать аккаунт: {code}.',
  'signupTerms': 'Я принимаю условия Vera и политику локальных демо-данных.',
  'signupStrengthWeak': 'Слабый',
  'signupStrengthMedium': 'Средний',
  'signupStrengthStrong': 'Сильный',
  'signupCtaCreate': 'Зарегистрироваться',
  'signupCtaContinueLocal': 'Продолжить как демо',
  'signupAlreadyHaveAccount': 'Уже есть аккаунт? ',
  'signupSignIn': 'Войти',
  'demoSampleLoaded': 'Данные демо-аккаунта загружены.',
  'demoBankPrimary': 'Vera Bank — Текущий счёт',
  'demoBankSavings': 'Vera Bank — Сберегательный',
  'demoBillCreditCard': 'Выписка по кредитной карте',
  'demoBillElectric': 'Счёт за электричество',
  'demoBillInternet': 'Счёт за интернет',
  'demoTxnSalary': 'Зарплата',
  'demoTxnGrocery': 'Продукты',
  'demoTxnFuel': 'Топливо',
  'demoTxnRestaurant': 'Ресторан',
  'demoTxnPharmacy': 'Аптека',
  'demoTxnRent': 'Аренда',
  'demoTxnTransfer': 'Перевод — Сбер. счёт',
  'demoTxnFamilyIncoming': 'Входящий перевод — Семья',
  'demoTxnAtm': 'Снятие наличных в банкомате',
  'deleteAccount': 'Удалить аккаунт',
  'deleteAccountTile': 'Удалить аккаунт',
  'deleteAccountTileValue': 'Удалить облачные данные и выйти',
  'deleteAccountDemoTileValue': 'Очистить демоданные на этом устройстве',
  'deleteAccountTitle': 'Удалить этот аккаунт?',
  'deleteAccountBody':
      'Ваш аккаунт Vera, синхронизированные данные и локальный кэш на этом устройстве будут удалены безвозвратно. Это действие нельзя отменить.',
  'deleteAccountDemoBody':
      'Это очистит демоаккаунт и удалит локальные данные с этого устройства. Это действие нельзя отменить.',
  'deleteAccountConfirm': 'Удалить аккаунт',
  'deleteAccountCancel': 'Отмена',
  'deleteAccountProcessing': 'Удаление аккаунта...',
  'deleteAccountDone': 'Аккаунт удалён.',
  'deleteAccountError':
      'Не удалось удалить аккаунт. Пожалуйста, войдите снова и повторите попытку.',
  'deleteAccountRecentLogin':
      'Для безопасности войдите в аккаунт ещё раз перед удалением.',
  'continueWithGoogle': 'Продолжить через Google',
  'googleSignInUnavailable':
      'Для входа через Google в этой сборке должен быть настроен Firebase.',
  'bankActionsTitle': 'Опции банка',
  'bankActionsCancel': 'Отмена',
  'bankActionsDelete': 'Удалить банк',
  'bankActionsConfirmTitle': 'Удалить этот банк?',
  'bankActionsConfirmBody':
      '{name} будет удалён и перестанет учитываться в общем балансе.',
  'bankDeleted': '{name} удалён',
  'bankActionsFeedNote':
      'Этот банк поставляется с демо-данными и не может быть удалён. Свои добавленные можно убрать.',
  'billDetailPrompt':
      'Счёт {name} на {amount}, осталось {days} дн. Что делать?',
  'categoryBudgetLabel': 'ТРАТЫ В ЭТОМ МЕСЯЦЕ',
  'categoryBudgetTopHint': 'Больше всего на {category} · {pct}%',
  'categoryLimitEditTitle': 'Лимит категории',
  'categoryLimitEditSubtitle':
      'Установите месячный бюджет для {category}. Vera покажет остаток при каждой трате.',
  'categoryLimitField': 'Месячный лимит (TL)',
  'categoryLimitSave': 'Сохранить',
  'categoryLimitClear': 'Снять лимит',
  'categoryNoLimit': 'без лимита',
  'categoryOver': 'превышение на {amount}',
  'categoryRemaining': 'осталось {amount}',
  'creditFieldDebt': 'Текущие месячные платежи',
  'creditFieldIncome': 'Месячный доход',
  'creditFieldLoanAmount': 'Сумма кредита',
  'creditFieldTerm': 'Срок',
  'creditLoanSimulation': 'Кредитный калькулятор',
  'creditLoanSimulationSubtitle':
      'Настройте значения — платёж и долговая нагрузка считаются мгновенно.',
  'creditScoreDisclaimer':
      'На этой странице кредитный рейтинг не рассчитывается. Реальный рейтинг получите в банке или бюро кредитных историй. Здесь только примерный платёж и долговая нагрузка по введённым вами данным.',
  'creditTermMonths': '{n} месяцев',
  'creditResultMonthlyPayment': 'ОЦЕНОЧНЫЙ МЕСЯЧНЫЙ ПЛАТЁЖ',
  'creditResultTotalCost': 'Итого к выплате',
  'creditResultPaymentLoad': 'Платёж / доход',
  'creditResultDtiAfter': 'Новая долговая нагрузка',
  'creditResultGuidance':
      'Банки обычно предпочитают долг/доход ниже 35%. Выше 40% сужает предложения. Только для планирования.',
  'demoResetTile': 'Сбросить демо-данные',
  'demoResetTileValue': 'Очистить импорт и добавления',
  'demoResetTitle': 'Сбросить демо-данные?',
  'demoResetBody':
      'Импортированные операции, добавленные банки и прогресс цели вернутся в начальное состояние.',
  'demoResetCancel': 'Отмена',
  'demoResetConfirm': 'Сбросить',
  'demoResetDone': 'Возвращено в демо-состояние',
  'exportTile': 'Экспорт моих данных',
  'exportTileValue': 'JSON · только устройство',
  'exportTitle': 'Ваши данные Vera',
  'exportSubtitle':
      'Импортированные операции, добавленные банки, ваша цель и обнаруженные подписки. Копирование без выхода с устройства.',
  'exportCopy': 'Копировать JSON',
  'exportCopied': 'Скопировано в буфер',
  'firstScanPending': 'Ожидание первого сканирования',
  'firstSyncPending': 'Ожидание первой синхронизации',
  'goalEditTitle': 'Редактировать цель',
  'goalEditTarget': 'Целевая сумма (TL)',
  'goalEditSaved': 'Накоплено (TL)',
  'goalEditFooter':
      'Vera следит за балансом; Uma каждый месяц подкидывает новую идею.',
  'goalEditSave': 'Сохранить',
  'goalEmergencyFund': 'Резервный фонд',
  'goalEtaMonths': 'Осталось {n} мес.',
  'goalEtaReached': 'Цель достигнута 🎯',
  'goalProgress': '{pct}% пройдено',
  'goalRemaining': 'осталось {amount}',
  'goalsSectionTitle': 'Ваши цели',
  'lastScanAt': 'Последнее сканирование {time}',
  'loginTitle': 'Войти в Vera',
  'loginSubtitle':
      'Войдите со своим аккаунтом; предпочтения профиля и действия ИИ хранятся локально до выхода.',
  'loginEmailHint': 'you@vera.app',
  'loginFooter':
      'Если Firebase не настроен, вход не сработает. Проверьте .env.',
  'notifTitle': 'Уведомления',
  'notifSubtitle': '{n} сигналов под наблюдением Uma',
  'notifEmpty': 'Всё тихо. Uma продолжает спокойно наблюдать.',
  'notifBillTitle': 'Счёт {name} приближается',
  'notifBillBody': 'Сумма {amount}. Оплатите через Uma или банк.',
  'notifPriceIncreaseTitle': '{name} подняла цену',
  'notifPriceIncreaseBody':
      'Ежемесячно +{delta} · теперь {price}. Можно заморозить в разделе планов.',
  'notifUnusedTitle': '{name} не используется',
  'notifUnusedBody':
      'Последний раз: {last}. Vera отметила как тихую утечку.',
  'notifBlockedDefault':
      'Vera пометила эту операцию как аномалию.',
  'profileAiToneBadge': 'ТОН ИИ / {tone}',
  'profileAutoApprove': 'Лимит автоодобрения',
  'profileAutoApproveOff': 'Выкл.',
  'profileConnectedTitle': '{n} подключённых учреждений',
  'profileConnectedSubtitle':
      'Балансы в реальном времени обновляются через текущую политику синхронизации и кэш ленты.',
  'profileConnectedAccount': 'Счёт {last4}',
  'profileDailyBriefing': 'Ежедневный ИИ-брифинг',
  'profileDailyBriefingSub':
      'Начинайте день с состояния счёта, подозрительной активности и подсказок по сбережениям',
  'profileFaceId': 'Повторная Face ID',
  'profileFaceIdSub':
      'Требовать биометрию перед чувствительными действиями',
  'profileFraudHigh': 'Чувствительные оповещения о мошенничестве',
  'profileFraudHighSub':
      'Vera помечает необычные шаблоны устройств и платежей раньше',
  'profileLiveSync': 'Live-синхронизация',
  'profileLiveSyncLive': 'Live',
  'profileLiveSyncBalanced': 'Сбалансированный',
  'profileLiveSyncSaver': 'Экономия',
  'profileSmartNotif': 'Умные уведомления',
  'profileSmartNotifSub':
      'Оповещения о мошенничестве, продлениях и изменениях одобрения',
  'profileVaultTitle': 'Защищённый сейф сессии',
  'profileVaultSubtitle':
      'Идентичность хранится отдельно от локальных настроек.',
  'profileVaultSignIn': 'Вход',
  'profileVaultProtectedSince': 'Защита с',
  'profileVaultThisDevice': 'Это устройство',
  'profileVaultApproval': 'Гарант одобрения',
  'profileVaultManualOnly': 'Только вручную',
  'profileVaultSyncMode': 'Режим синхронизации',
  'profileVaultSyncLive': 'Live-синхронизация',
  'profileVaultSyncBalanced': 'Сбалансированная синхронизация',
  'profileVaultSyncSaver': 'Экономная синхронизация',
  'securityAccountSection': 'БЕЗОПАСНОСТЬ АККАУНТА',
  'securityActiveBody': 'Fraud Radar отслеживает {n} активных предупреждений.',
  'securityClearBody':
      'В последнем сканировании нет нерешённых предупреждений.',
  'securityPillBlocked': 'ЗАБЛОКИРОВАНО ИИ',
  'securityPillApproved': 'ВЫ ОДОБРИЛИ',
  'securityPillKept': 'ОСТАВЛЕНО В БЛОКЕ',
  'securityDecisionKept':
      'Вы оставили это событие заблокированным. Fraud Radar продолжит считать похожие шаблоны высоко-рисковыми.',
  'securityDecisionApproved':
      'Вы отметили это событие безопасным. Fraud Radar использует обратную связь, чтобы сокращать похожие ложные срабатывания.',
  'securityStatBlockedLabel': 'БЛОК',
  'securityStatBlockedSub': 'активно',
  'securityStatReviewedLabel': 'ПРОВЕРЕНО',
  'securityStatReviewedSub': 'за неделю',
  'securityStatDevicesLabel': 'УСТРОЙСТВА',
  'securityStatDevicesSub': 'доверенные',
  'securityViewReport': 'ОТКРЫТЬ ОТЧЁТ UMA',
  'subsRenewalLabel': 'Продление',
  'subsActivityLabel': 'Активность',
  'txnDetailWhen': 'Когда',
  'txnDetailCategory': 'Категория',
  'txnDetailDirection': 'Направление',
  'txnDetailIncoming': 'Входящая',
  'txnDetailOutgoing': 'Исходящая',
  'txnDetailAskPrompt':
      'Посмотри на операцию {name} — {amount} это нормально?',
  'umaAuditTrailSubtitle':
      'Подписанный локальный журнал ответов Uma на этом устройстве.',
  'umaAuditTrailEmptyState':
      'Пока нет подписанных действий. Обратитесь к Uma и журнал доверия появится здесь.',
  'umaAuditNoteAttached': 'Заметка прикреплена',
  'umaAuditActionReplyGenerated': 'Ответ сгенерирован',
  'umaGreeting':
      'Привет, {name}. Я прочла импортированные выписки. Могу проанализировать траты, найти неиспользуемые подписки и помочь поставить цели сбережений. Я не двигаю деньги — если нужно действие, направлю в ваше банковское приложение.',
  'umaPromptAnalyze': 'Проанализируй мои траты в этом месяце.',
  'umaReplyAnalyze':
      'Больше всего в этом месяце вы тратите на {top} — {topAmount}. Всего отток {spending}. Если хотите, поставим лимиты по категориям.',
  'umaReplyAnalyzeEmpty':
      'Пока нет операций для анализа. Отсканируйте чек или импортируйте выписку — разберём траты вместе.',
  'umaReplyExplainWealth':
      'Vera следит за портфелем по импортированным счетам. Акции выглядят чуть перевешенными в этом месяце; предложу добавить золото или наличные при следующем входе в банк.',
  'umaReplyLoan':
      'Судя по доходу и долгам из ваших выписок, вы подходите под средние личные кредиты. Откройте кредитную симуляцию — вместе подберём сумму и срок.',
  'umaReplySecurity':
      'Я отметила этот перевод, потому что получатель появлялся раз ранее, а геолокация устройства не совпала с обычной. Vera не блокирует в банке — она предупреждает, решение за вами.',
  'umaReplySubscriptions':
      'У вас {n} планов, заслуживающих проверки. Месячный итог подписок около {total}.',
  'umaReplySubscriptionsEmpty':
      'Пока не вижу активных подписок. Импортируйте выписку — Vera найдёт повторяющиеся списания.',
  'umaReplyFallback':
      'Помогу с этим. Если хотите, дам короткую финансовую сводку или подготовлю безопасный следующий шаг.',
  'updatedAt': 'Обновлено {time}',
};
