part of '../app_strings.dart';

const Map<String, String> _ruStrings = {
  'navHome': 'Главная',
  'navWealth': 'Капитал',
  'navPlans': 'Планы',
  'navSecurity': 'Защита',
  'navUma': 'UMA',
  'helloLabel': 'Привет,',
  'defaultUserName': 'Пользователь Vera',
  'totalNetWorth': 'ОБЩИЙ КАПИТАЛ',
  'liveFeed': 'ОНЛАЙН',
  'syncing': 'СИНХРО',
  'thisMonth': 'в этом месяце',
  'actionSend': 'Отправить',
  'actionRequest': 'Запросить',
  'actionTopUp': 'Пополнить',
  'actionPay': 'Оплатить',
  'connectedAccounts': 'Подключённые счета',
  'refresh': 'Обновить',
  'syncingDots': 'Синхронизация...',
  'recentTransactions': 'Последние операции',
  'itemsCount': '{n} операций',
  'itemsVisible': 'видно',
  'connectBank': 'Подключить банк',
  'homeFirstStepsTitle': 'Сделаем первый шаг вместе',
  'homeFirstStepsBody':
      'Vera становится заметно полезнее после появления первых данных. Импортируйте выписку, отсканируйте чек или добавьте банк, чтобы оживить главный экран.',
  'homeFirstStepsHint':
      'Даже одного такого шага достаточно, чтобы появились подсказки, балансы и умные уведомления.',
  'connectedAccountsEmptyTitle': 'Пока нет подключённых счетов',
  'connectedAccountsEmptyBody':
      'Когда вы добавите банк, мы сможем показывать баланс на главном экране и готовить действия Uma с более точным контекстом.',
  'addBankTitle': 'Добавить банк',
  'addBankSubtitle':
      'Vera не подключается к банкам — вы добавляете и отслеживаете баланс.',
  'addBankName': 'Название банка',
  'addBankLast4': 'Последние 4 цифры',
  'addBankBalance': 'Баланс (TL)',
  'addBankColor': 'Цвет',
  'addBankSave': 'Добавить банк',
  'addBankNameRequired': 'Название банка обязательно.',
  'bankAdded': '{name} добавлен',
  'umaInsight': 'ИНСАЙТ UMA',
  'umaInsightNoData':
      'Vera пока вас не знает. Импортируйте выписку, отсканируйте чек или добавьте банк, чтобы мы вместе начали строить более умные подсказки.',
  'umaInsightNoTransactions':
      'Пока не видно ни одной операции. Импортируйте первую выписку или добавьте операцию вручную, чтобы Uma поняла ваш ритм расходов.',
  'umaInsightNoPattern':
      'Для этого периода пока нет достаточно внятного паттерна расходов. Когда появятся новые операции, инсайт здесь станет точнее.',
  'umaInsightTopCategory':
      'Больше всего вы потратили на {category}: {amount}, это около {share}% от проанализированного общего объёма {total}.',
  'umaInsightImportCta': 'Импортировать выписку',
  'umaInsightAddFirstTxnCta': 'Добавить первую операцию',
  'umaInsightDeepenCta': 'Углубить с Uma',
  'spent': 'Расход',
  'incoming': 'Доход',
  'creditTitle': 'Кредит',
  'creditSubtitle': 'Кредит на основе реального дохода.',
  'creditScoreLabel': 'КРЕДИТНЫЙ РЕЙТИНГ',
  'openCredit': 'Открыть кредит',
  'wealthTitle': 'Капитал',
  'wealthSubtitle': 'Ваши деньги работают сами.',
  'portfolio': 'ПОРТФЕЛЬ',
  'ytd': 'С НГ',
  'today': 'сегодня',
  'autonomousWealth': 'Автономный капитал',
  'profile': 'ПРОФИЛЬ',
  'moveLimit': 'ЛИМИТ',
  'approval': 'УТВЕРЖД.',
  'activityFeed': 'Активность',
  'explainability': 'Объяснимость',
  'undo': 'Отменить',
  'viewDetails': 'Подробнее',
  'plansTitle': 'Планы',
  'plansSubtitle': 'Ловите тихие утечки денег.',
  'subscriptionIntelligence': 'АНАЛИЗ ПОДПИСОК',
  'detectedPlans': 'Найденные планы',
  'filterAll': 'Все',
  'filterAttention': 'Нужно внимание',
  'filterUnused': 'Неиспользуемые',
  'filterPriceChanges': 'Изменение цены',
  'freezePlan': 'Заморозить план',
  'reviewPlan': 'Проверить план',
  'askUma': 'Спросить UMA',
  'securityTitle': 'Защита',
  'securitySubtitle': 'Активный уровень защиты.',
  'profileAndSettings': 'Профиль и настройки',
  'sectionAppearance': 'ВНЕШНИЙ ВИД',
  'sectionAi': 'НАСТРОЙКИ ИИ',
  'sectionConnected': 'ПОДКЛЮЧЁННЫЕ ОРГАНИЗАЦИИ',
  'sectionAccount': 'АККАУНТ',
  'sectionLanguage': 'ЯЗЫК',
  'brandPalette': 'Палитра бренда',
  'mood': 'Тема',
  'moodLight': 'Светлая',
  'moodDark': 'Тёмная',
  'vibe': 'Стиль',
  'vibeCalm': 'Спокойный',
  'vibeStandard': 'Стандартный',
  'vibeBold': 'Яркий',
  'language': 'Язык',
  'signOut': 'Выйти',
  'umaTone': 'Тон Uma',
  'toneConcise': 'Кратко',
  'toneCoach': 'Коуч',
  'toneProactive': 'Проактивно',
  'scanReceipt': 'Сканер',
  'scanReceiptTitle': 'Сканировать чек или экран',
  'scanReceiptSubtitle':
      'Снимите чек, счёт или экран банка — ИИ превратит его в операцию.',
  'scanHint':
      'ИИ читает чек, выделяет категорию и сумму, спрашивает подтверждение.',
  'takePhoto': 'Сделать фото',
  'pickFromGallery': 'Из галереи',
  'scanReading': 'ИИ читает...',
  'scanTotalLabel': 'Итого',
  'scanAgain': 'Сканировать снова',
  'addToTransactions': 'Добавить к операциям',
  'scanNoTotal': 'Сумма не распознана, отсканируйте снова.',
  'addedToTransactions': 'Добавлено',
  'parsedByAi': 'ИИ',
  'parsedFallback': 'DEMO',
  'scanFallbackWarning':
      'Ключ Gemini API отсутствует или чек не удалось разобрать. Пожалуйста, введите операцию вручную.',
  'scanFallbackAction': 'ИИ не сработал — ввести вручную',
  'savingsStoryLabel': 'СБЕРЕЖЕНО ЗА МЕСЯЦ',
  'savingsStoryFooter': 'Благодаря 3 советам Uma',
  'savingsStoryDelta': 'На {pct}% меньше, чем в прошлом месяце',
  'upcomingBills': 'Предстоящие платежи',
  'billPayViaUma': 'Оплатить через Uma',
  'daysLeft': 'осталось {n} дн.',
  'statementImport': 'Импорт выписки',
  'statementImportTitle': 'Импорт банковской выписки',
  'statementImportSubtitle':
      'Загрузите PDF или скриншот выписки; ИИ извлечёт операции.',
  'pickStatementFile': 'Выбрать файл (PDF / изображение)',
  'statementImportHint':
      'Банк отдаёт выписку в PDF — Vera читает её без подключения к Open Banking.',
  'statementParsing': 'ИИ читает выписку...',
  'closingBalance': 'Остаток',
  'detectedTransactions': 'Найдено {n} операций',
  'statementImportAgain': 'Импорт ещё раз',
  'statementNoTransactions': 'Не удалось извлечь операции.',
  'statementImported': 'Добавлено в ваши операции',
  'importToVera': 'Импорт в Vera',
  'statementFallbackWarning':
      'Ключ Gemini API отсутствует или выписку не удалось разобрать. Пожалуйста, введите операции вручную.',
  'statementFallbackAction': 'ИИ не сработал — ввести вручную',
  'openBankApp': 'Открыть {bank}',
  'umaForwardNote':
      'Действие завершается в банковском приложении. Vera отслеживает результат по SMS или выписке.',
  'forwardedToBank': 'Передано в {bank} · Vera следит',
  'keep': 'Отмена',
  'thisMonthsAiPlan': 'План ИИ на этот месяц',
  'aiPlanFooter': 'Совет Uma — выполните в своём банке; Vera ведёт учёт.',
  'applyAtBank': 'Сделать в банке',
  'securityVeraSideBanner':
      'Vera не является службой безопасности банка. Она замечает аномалии в ваших данных и предупреждает вас; блокировку вы решаете вместе с банком.',
  'statusAllClear': 'Всё чисто',
  'statusMonitoring': 'Наблюдение',
  'securityRecentActivity': 'Недавняя активность',
  'securityScanning': 'Сканирование...',
  'liveAnomalyDetected': 'Аномалия обнаружена',
  'highRiskConfidence': 'Высокий риск',
  'reviewedSignal': 'Проверено',
  'keepBlocked': 'Оставить заблокированным',
  'thisWasMe': 'Это был я',
  'emailField': 'E-mail',
  'passwordField': 'Пароль',
  'loginDemoHint':
      'Быстрый вход в демо-аккаунт: e-mail «{email}», пароль «{password}».',
  'umaVoiceStart': 'Спросить голосом',
  'umaVoiceStop': 'Остановить запись',
  'umaVoiceListening': 'Слушаю...',
  'umaVoicePermissionDenied':
      'Нужен доступ к микрофону. Разрешите для Vera в настройках устройства.',
  'umaVoiceUnavailable': 'Распознавание речи недоступно на этом устройстве.',
  'umaToolGoalCreated': 'Готово. Создана цель на {target} TL.',
  'umaToolBillAdded': 'Добавлен счёт {name}, к оплате через {days} дн.',
  'umaToolExpenseAdded': 'Расход {name} ({amount} TL) записан.',
  'umaSuggestionPay': 'Оплатить мою карту',
  'umaSuggestionSubs': 'Показать подписки',
  'umaSuggestionAnalyze': 'Анализировать траты',
  'voiceCommandTooltip': 'Голосовая команда',
  'requireConfirmation': 'Требовать подтверждение',
  'requireConfirmationDesc':
      'Показывать карточку подтверждения перед действием',
  'orderFrom': 'От',
  'orderTo': 'Кому',
  'orderAmount': 'Сумма',
  'accountTilePersonal': 'Личные данные',
  'accountTileEmail': 'E-mail',
  'accountTileSecurity': 'Безопасность и PIN',
  'accountTileStorage': 'Политика хранения',
  'accountTileHelp': 'Помощь и поддержка',
  'infoDisplayName': 'Отображаемое имя',
  'infoMember': 'Членство',
  'infoMemberDescription':
      'Демо-аккаунт Vera. После подключения бэкенда здесь появятся дата регистрации и план.',
  'infoEmailLabel': 'Адрес электронной почты',
  'infoEmailUsage': 'Где используется',
  'infoEmailDescription':
      'Используется для демо-сессии. Данные остаются на устройстве, на сервер ничего не отправляется.',
  'infoSessionVault': 'Хранилище сессии',
  'infoSessionVaultDescription':
      'Данные сессии шифруются через flutter_secure_storage и хранятся только на этом устройстве.',
  'infoFaceId': 'Face ID',
  'infoFaceIdOn': 'Вкл. — при входе требуется биометрическая проверка.',
  'infoFaceIdOff': 'Выкл. — достаточно пароля / демо-входа.',
  'infoFraudAlerts': 'Оповещения о мошенничестве',
  'infoFraudAlertsOn':
      'Вкл. — при подозрительной операции отправляется локальное уведомление.',
  'infoFraudAlertsOff': 'Выкл. — оповещения показываются только в приложении.',
  'infoSyncMode': 'Режим синхронизации',
  'infoLocalData': 'Локальные данные',
  'infoLocalDataDescription':
      'OCR-чеки и добавленные банки хранятся в SharedPreferences. "Экспорт данных" — в P1-бэклоге.',
  'helpFaqQ1': 'Vera подключается к моему банку?',
  'helpFaqA1':
      'Нет. У Vera нет лицензии AISP/PSP. Данные приносите вы: PDF-выписки, фото чеков, скриншоты или ручной ввод. Vera объединяет их с помощью ИИ и направляет действия в ваше банковское приложение.',
  'helpFaqQ2': 'Где хранятся мои данные?',
  'helpFaqA2':
      'Чувствительные данные сессии — flutter_secure_storage (шифрование, на устройстве). OCR и записи о банках — SharedPreferences. Сервера нет, третьим лицам данные не передаются.',
  'helpFaqQ3': 'Что если нет ключа Gemini API?',
  'helpFaqA3':
      'OCR и импорт выписок работают через детерминированный fallback (появляется бейдж DEMO). UMA отвечает через эвристический intent-роутер. Весь поток работает — отключён только live-парсинг ИИ.',
  'helpContact': 'Контакт',
  'demoUser': 'Демо-пользователь',
  'umaThinking': 'Uma думает...',
  'umaAskHint': 'Спросите Uma...',
  'umaStatusOnline': 'ИИ-ассистент · онлайн',
  'umaSuggestionBuyGold': 'Купить 10 г золота',
  'umaSuggestionMoveSavings': 'Перевести 2500 TL в сбережения',
  'umaActionPolicy': 'ПОЛИТИКА ДЕЙСТВИЙ',
  'umaActionPolicyDesc':
      'Vera не двигает деньги сама; каждое действие открывает банковское приложение для вашего подтверждения.',
  'onbStep1Title': 'Добро пожаловать в Vera',
  'onbStep1Subtitle':
      'Сначала выберите язык. Позже его всегда можно поменять в настройках.',
  'onbStep2Title': 'Сделайте под себя',
  'onbStep2Subtitle':
      'Выберите палитру и настроение бренда. Тему можно изменить и позже.',
  'onbStep3Title': 'Добавьте свои данные',
  'onbStep3Subtitle':
      'Vera не подключается к вашему банку — вы приносите выписки, а Vera помогает их понять. Начните сейчас или добавьте позже.',
  'onbContinue': 'Продолжить',
  'onbStart': 'Открыть Vera',
  'onbSkip': 'Пропустить',
  'onbBack': 'Назад',
  'onbImportNow': 'Импортировать выписку',
  'onbScanNow': 'Сканировать чек',
  'onbContinueWithoutImport': 'Продолжить без импорта',
  'onbPalettePreviewTitle': 'Живой предпросмотр',
  'onbPalettePreviewBody':
      'Ваш выбор сразу меняет карточки, AI-акценты и общее настроение интерфейса.',
  'onbBlankCanvasTitle': 'Начать с пустого экрана тоже нормально',
  'onbBlankCanvasBody':
      'Если хотите, продолжайте сейчас без импорта; Vera подскажет вам и первый шаг уже внутри приложения.',
  'goalEmptyPrompt': 'Вы ещё не задали цель — нажмите, чтобы добавить.',
  'goalEmptyHint':
      'Сначала задайте цель, и Uma подскажет, сколько стоит откладывать каждый месяц в вашем ритме.',
  'goalEmptyCta': 'Задать цель',
  'goalMonthsLabel': 'ЗА СКОЛЬКО МЕСЯЦЕВ',
  'goalMonthsOption': '{n} мес.',
  'goalAdviceSummary': '{amount} в месяц · {months} мес.',
  'goalCalculate': 'Рассчитать',
  'goalPresetEmergency': 'НЗ (6 мес) · {amount}',
  'goalPresetVacation': 'Отпуск (3 мес) · {amount}',
  'goalPresetCar': 'Автомобиль (12 мес) · {amount}',
  'fieldName': 'Название',
  'fieldAmountTl': 'Сумма (TL)',
  'fieldDate': 'Дата',
  'fieldCategory': 'Категория',
  'fieldDescription': 'Описание',
  'fieldLabelOptional': 'Метка (необязательно)',
  'actionAdd': 'Добавить',
  'actionUpdate': 'Обновить',
  'actionDelete': 'Удалить',
  'actionManual': 'Вручную',
  'addBillTitle': 'Добавить новый счёт',
  'editBillTitle': 'Редактировать счёт',
  'addBillNameHint': 'например, Turk Telekom',
  'dueDateLabel': 'Срок оплаты',
  'addBillCta': 'Добавить счёт',
  'noTrackedBillsTitle': 'Пока нет отслеживаемых счетов',
  'noTrackedBillsBody': 'Vera напомнит за день до срока оплаты.',
  'billKindCard': 'Карта',
  'billKindInternet': 'Интернет',
  'billKindElectric': 'Электричество',
  'billKindWater': 'Вода',
  'billKindGas': 'Газ',
  'billKindRent': 'Аренда',
  'billKindOther': 'Другое',
  'addManualTxnTitle': 'Добавить операцию вручную',
  'txnTypeExpense': 'Расход',
  'txnTypeIncome': 'Доход',
  'addManualTxnNameHint': 'например, Migros',
  'aiSuggestionLabel': 'Подсказка Uma',
  'acceptSuggestion': 'Принять',
  'categoryMarket': 'Маркет',
  'categoryFood': 'Еда и напитки',
  'categoryFuel': 'Топливо',
  'categoryBill': 'Счета',
  'categoryHealth': 'Здоровье',
  'categoryEducation': 'Образование',
  'categoryEntertainment': 'Развлечения',
  'categoryTransfer': 'Перевод',
  'categorySalary': 'Зарплата',
  'categorySubscription': 'Подписка',
  'categoryMusic': 'Музыка',
  'categoryVideo': 'Видео',
  'categoryStorage': 'Хранилище',
  'categoryDeveloper': 'Разработка',
  'categoryAi': 'ИИ',
  'noTransactionsTitle': 'Операций пока нет',
  'noTransactionsBody':
      'Добавьте первую операцию, импортируйте выписку или отсканируйте чек.',
  'addHoldingTitle': 'Добавить актив в портфель',
  'addHoldingSubtitle':
      'Выберите один из классов ниже и введите стоимость в TL. Uma автоматически пересчитает веса.',
  'addHoldingHint': 'например, THYAO или XU100 ETF',
  'holdingValueLabel': 'Стоимость (TL)',
  'removeHolding': 'Удалить этот актив',
  'noWealthActionsTitle': 'Uma ещё не предпринимала действий',
  'noWealthActionsBody':
      'Когда вы включите автономный режим, здесь появятся рекомендации и ребалансировки.',
  'startPortfolioTitle': 'Начните собирать портфель',
  'startPortfolioBody':
      'Добавьте акции, золото, наличные или криптоактивы. Uma будет следить за отклонениями и писать сюда советы.',
  'wealthApprovalAuto': 'Авто',
  'wealthApprovalHybrid': 'Гибрид',
  'wealthActionReversed': 'ОТМЕНЕНО',
  'holdingBucketEquity': 'Акции',
  'holdingBucketGold': 'Золото',
  'holdingBucketCash': 'Наличные',
  'holdingBucketCrypto': 'Крипто',
  'holdingBucketFunds': 'Фонд',
  'holdingBucketBonds': 'Облигации',
  'subscriptionsAttentionCount': 'В этом цикле {n} планам нужно внимание',
  'noSubscriptionsDetectedTitle': 'Подписки пока не обнаружены',
  'noSubscriptionsDetectedBody':
      'Импортируйте выписку или отсканируйте чек — Vera автоматически найдёт регулярные платежи.',
  'noSubscriptionsForFilterTitle': 'Нет подписок для этого фильтра',
  'noSubscriptionsForFilterBody': 'Попробуйте другие фильтры.',
  'subsAlertSavingsTitle': 'Потенциал ежемесячной экономии',
  'subsAlertSavingsMessageEmpty':
      'Подписки пока не найдены. Импортируйте выписку или добавьте подписку вручную, и Vera начнёт её отслеживать.',
  'subsAlertSavingsMessageActive':
      'Vera нашла подписки, которые можно заморозить или перевести на более дешёвый план без ущерба для вашего ритма.',
  'subsAlertSavingsMetric': 'ЭКОНОМИЯ',
  'subsAlertPriceTitle': 'Обнаружено повышение цены',
  'subsAlertPriceMessageNone': 'В этом цикле нет необычных скачков цены.',
  'subsAlertPriceMessageSome':
      'Один или несколько планов подорожали по сравнению с прошлым месяцем.',
  'subsAlertPriceMetric': 'РОСТ',
  'subsAlertUnusedTitle': 'Редко используемые планы',
  'subsAlertUnusedMessageNone': 'Все подписки выглядят здоровыми.',
  'subsAlertUnusedMessageSome':
      'По вашему недавнему паттерну активности {n} планов выглядят малоиспользуемыми.',
  'subsAlertUnusedMetric': 'ПУСТО',
  'subsInsightEmpty':
      'Vera анализирует ваши выписки или чеки и собирает подписки здесь.',
  'subsInsightHealthy':
      'В этом месяце подписки выглядят здоровыми. Срочной утечки экономии не видно.',
  'subsInsightNeedsAttention':
      'У вас есть {n} подписок, которые стоит проверить. Vera оценивает, что вы можете вернуть около {amount} в месяц, если заморозите неиспользуемые и понизите более дорогие планы.',
  'subsDetectedFromImport': 'Обнаружено по импортированной операции',
  'subsSeenInRecentTransactions': 'Встречалось {n}× в недавних операциях',
  'subsKnownVendorLabel': 'Известный поставщик подписки',
  'subsRecommendationDetected':
      'Vera обнаружила эту подписку в импортированной выписке. Вы всё ещё ей пользуетесь?',
  'subsStatusActive': 'АКТИВНА',
  'subsStatusPriceUp': 'ЦЕНА ВЫРОСЛА',
  'subsStatusUnused': 'МАЛО ИСПОЛЬЗУЕТСЯ',
  'subsStatusRenewsSoon': 'СКОРО ПРОДЛИТСЯ',
  'proactiveBadge': 'VERA ЗАМЕТИЛА',
  'proactiveBillTitle': 'Счёт {name} скоро подойдёт',
  'proactiveBillBody':
      '{amount} · осталось {days} дн. Попросить Uma подготовить оплату?',
  'proactiveBillCta': 'Оплатить через Uma',
  'proactiveBillPrompt': 'Помоги мне оплатить счёт {name}.',
  'proactivePriceTitle': '{name} подорожал',
  'proactivePriceBody': '+{delta} в месяц. Хотите заморозить подписку?',
  'proactivePriceCta': 'Открыть подписки',
  'proactiveUnusedTitle': '{name} почти не используется',
  'proactiveUnusedBody':
      'Последнее использование: {last}. Это может быть тихой утечкой денег.',
  'proactiveUnusedCta': 'Открыть подписки',
  'proactiveHealthyTitle': 'Сейчас нет критических сигналов',
  'proactiveHealthyBody':
      'Сейчас не видно ни срочного счёта, ни скачка цены, ни явно бесполезной подписки. Если хотите, Uma всё равно может быстро оценить этот период.',
  'proactiveHealthyCta': 'Попросить Uma оценить',
  'proactiveEmptyTitle': 'Vera пока не нашла сигнал для отслеживания',
  'proactiveEmptyBody':
      'После импорта выписки Vera будет показывать здесь ближайшие платежи, подписки и небольшие риски.',
  'proactiveEmptyCta': 'Импортировать выписку',
  'securityEmptyTitle': 'Сейчас нет предупреждений для проверки',
  'securityEmptyBody':
      'Радар мошенничества Vera тихо следит за вашими устройствами и импортированными транзакциями. Если что-то случится, это появится здесь.',
  'close': 'Закрыть',
  'categoryOther': 'Прочее',
  'receiptDefaultName': 'Чек',
  'wealthInsightAddPortfolio':
      'Автономный режим выключен. Добавь портфель, чтобы Uma отслеживала отклонения и предлагала шаги.',
  'wealthInsightPaused':
      'Автономный режим приостановлен. Vera следит за отклонениями, но ждёт твоего подтверждения перед движением средств.',
  'wealthInsightActive':
      'Uma активна с политикой "{profile}". В пределах месячного лимита {limit} TL выполнено или подготовлено {count} корректировок портфеля.',
  'goalReached': 'Цель достигнута. Можно поставить новую.',
  'goalRemainingPlan':
      'Чтобы накопить оставшиеся {remaining} TL за {months} мес., нужно откладывать {monthly} TL в месяц.',
  'goalNarrativeNewTarget': 'Можно задать новую сумму для цели.',
  'goalNarrativeNoData':
      'Пока нет данных о транзакциях. Импортируй выписку или добавь несколько записей вручную, чтобы Uma предложила план.',
  'goalNarrativeTrim':
      'Нужно откладывать {monthly} TL в месяц. Начать стоит с небольших сокращений по категории {topCategory}.',
  'todayAt': 'Сегодня, {time}',
  'loginContinueEmail': 'Продолжить с email',
  'loginEmailPasswordRequired': 'Email и пароль обязательны.',
  'loginFirebaseError': 'Ошибка входа Firebase: {code}.',
  'loginFirebaseReadyFooter':
      'Firebase auth подключён. Демо-режим остаётся доступным для hackathon-сценариев.',
  'loginCreateAccount': 'Создать аккаунт',
  'dividerOr': 'или',
  'signupTitle': 'Создайте аккаунт',
  'signupSubtitleFirebase':
      'Ваш профиль Vera будет синхронизироваться через Firebase.',
  'signupSubtitleLocal':
      'Firebase ещё не настроен. Поток продолжится в локальном демо-режиме.',
  'signupFieldFullName': 'Полное имя',
  'signupFieldEmail': 'Email',
  'signupFieldPassword': 'Пароль',
  'signupFieldConfirmPassword': 'Подтвердите пароль',
  'signupErrorNameRequired': 'Введите полное имя.',
  'signupErrorInvalidEmail': 'Введите корректный email.',
  'signupErrorShortPassword': 'Пароль должен быть не короче 6 символов.',
  'signupErrorPasswordMismatch': 'Пароли не совпадают.',
  'signupErrorAcceptTerms': 'Примите условия, чтобы продолжить.',
  'signupFailedTemplate': 'Не удалось создать аккаунт: {code}.',
  'signupTerms': 'Я принимаю условия Vera и политику локальных демо-данных.',
  'signupStrengthWeak': 'Слабый',
  'signupStrengthMedium': 'Средний',
  'signupStrengthStrong': 'Сильный',
  'signupCtaCreate': 'Создать Firebase-аккаунт',
  'signupCtaContinueLocal': 'Продолжить локально',
  'signupAlreadyHaveAccount': 'Уже есть аккаунт? ',
  'signupSignIn': 'Войти',
  'demoSampleLoaded': 'Данные демо-аккаунта загружены.',
  'demoBankPrimary': 'Vera Bank — Текущий счёт',
  'demoBankSavings': 'Vera Bank — Сберегательный',
  'demoBillCreditCard': 'Выписка по кредитной карте',
  'demoBillElectric': 'Счёт за электричество',
  'demoBillInternet': 'Счёт за интернет',
  'demoTxnSalary': 'Зарплата',
  'demoTxnGrocery': 'Продукты',
  'demoTxnFuel': 'Топливо',
  'demoTxnRestaurant': 'Ресторан',
  'demoTxnPharmacy': 'Аптека',
  'demoTxnRent': 'Аренда',
  'demoTxnTransfer': 'Перевод — Сбер. счёт',
  'demoTxnFamilyIncoming': 'Входящий перевод — Семья',
  'demoTxnAtm': 'Снятие наличных в банкомате',
  'deleteAccount': 'Удалить аккаунт',
  'deleteAccountTile': 'Удалить аккаунт',
  'deleteAccountTileValue': 'Удалить облачные данные и выйти',
  'deleteAccountDemoTileValue': 'Очистить демоданные на этом устройстве',
  'deleteAccountTitle': 'Удалить этот аккаунт?',
  'deleteAccountBody':
      'Ваш аккаунт Vera, синхронизированные данные и локальный кэш на этом устройстве будут удалены безвозвратно. Это действие нельзя отменить.',
  'deleteAccountDemoBody':
      'Это очистит демоаккаунт и удалит локальные данные с этого устройства. Это действие нельзя отменить.',
  'deleteAccountConfirm': 'Удалить аккаунт',
  'deleteAccountCancel': 'Отмена',
  'deleteAccountProcessing': 'Удаление аккаунта...',
  'deleteAccountDone': 'Аккаунт удалён.',
  'deleteAccountError':
      'Не удалось удалить аккаунт. Пожалуйста, войдите снова и повторите попытку.',
  'deleteAccountRecentLogin':
      'Для безопасности войдите в аккаунт ещё раз перед удалением.',
  'continueWithGoogle': 'Продолжить через Google',
  'googleSignInUnavailable':
      'Для входа через Google в этой сборке должен быть настроен Firebase.',
};
