part of '../app_strings.dart';

const Map<String, String> _trStrings = {
  'navHome': 'Ana sayfa',
  'navWealth': 'Servet',
  'navPlans': 'Planlar',
  'navSecurity': 'Güvenlik',
  'navUma': 'UMA',
  'helloLabel': 'Merhaba,',
  'defaultUserName': 'Vera Kullanıcısı',
  'totalNetWorth': 'TOPLAM NET DEĞER',
  'liveFeed': 'CANLI',
  'syncing': 'EŞİTLENİYOR',
  'thisMonth': 'bu ay',
  'actionSend': 'Gönder',
  'actionRequest': 'İste',
  'actionTopUp': 'Yükle',
  'actionPay': 'Öde',
  'connectedAccounts': 'Bağlı hesaplar',
  'refresh': 'Yenile',
  'syncingDots': 'Eşitleniyor...',
  'firstSyncPending': 'İlk senkron bekleniyor',
  'updatedAt': 'Güncellendi {time}',
  'firstScanPending': 'İlk tarama bekleniyor',
  'lastScanAt': 'Son tarama {time}',
  'recentTransactions': 'Son işlemler',
  'itemsCount': '{n} işlem',
  'itemsVisible': 'görünür',
  'connectBank': 'Banka ekle',
  'homeFirstStepsTitle': 'İlk adımı birlikte atalım',
  'homeFirstStepsBody':
      'Vera en iyi ilk verin geldikten sonra şekillenir. Bir ekstre yükle, fiş tara ya da bir banka ekleyerek ana ekranı canlandır.',
  'homeFirstStepsHint':
      'Bunlardan sadece biri bile önerileri, bakiyeyi ve akıllı uyarıları başlatır.',
  'connectedAccountsEmptyTitle': 'Henüz bağlı hesap görünmüyor',
  'connectedAccountsEmptyBody':
      'Bir banka eklediğinde bakiyeni ana ekranda izler, Uma aksiyonlarını daha doğru bağlamla hazırlarız.',
  'addBankTitle': 'Banka ekle',
  'addBankSubtitle':
      'Vera bankaya bağlanmıyor — sen ekliyorsun, bakiyeyi takip ediyor.',
  'addBankName': 'Banka adı',
  'addBankLast4': 'Son 4 hane',
  'addBankBalance': 'Bakiye (TL)',
  'addBankColor': 'Renk',
  'addBankSave': 'Bankayı ekle',
  'addBankNameRequired': 'Banka adı gerekli.',
  'bankAdded': '{name} eklendi',
  'umaInsight': 'UMA İÇGÖRÜ',
  'umaInsightNoData':
      'Vera seni henüz tanımıyor. Bir ekstre yükle, fiş tara veya banka ekle; birlikte akıllı önerileri başlatalım.',
  'umaInsightNoTransactions':
      'Henüz işlem görünmüyor. İlk ekstreni yükle ya da manuel işlem ekle; Uma harcama düzenini çıkarsın.',
  'umaInsightNoPattern':
      'Bu dönem için anlamlı bir harcama deseni henüz oluşmadı. Yeni işlemler geldikçe burada daha net içgörü göreceksin.',
  'umaInsightTopCategory':
      'En çok {category} tarafında yoğunlaştın: {amount}, yani analiz edilen toplam {total} harcamanın %{share}’i.',
  'umaInsightImportCta': 'Ekstre yükle',
  'umaInsightAddFirstTxnCta': 'İlk işlemi ekle',
  'umaInsightDeepenCta': 'Uma ile derinleştir',
  'spent': 'Harcanan',
  'incoming': 'Gelen',
  'creditHealthScore': 'Kredi sağlık skoru',
  'creditStatIncome': 'GELİR',
  'creditStatDti': 'BORÇ/GELİR',
  'creditStatTerm': 'VADE',
  'creditTermMo': '{n} ay',
  'creditTermMonths': '{n} ay',
  'creditRunSimulation': 'Kredi simülasyonunu çalıştır',
  'creditCurrentDecision': 'Geçerli karar',
  'creditPersonalLoan': 'Kişisel kredi · {amount}',
  'creditMonthsApr': '{n} ay · %{apr} APR',
  'creditUmaInsight': 'UMA İÇGÖRÜ',
  'creditEligibleProducts': 'Uygun ürünler',
  'creditLoanSimulation': 'Kredi simülasyonu',
  'creditLoanSimulationSubtitle':
      'İstediğin değerleri ayarla, Vera kararı anlık günceller.',
  'creditFieldLoanAmount': 'Kredi tutarı',
  'creditFieldTerm': 'Vade',
  'creditFieldIncome': 'Aylık gelir',
  'creditFieldDebt': 'Aylık borç',
  'creditScoreDisclaimer':
      'Bu ekran gelir, borç yükü ve seçilen vadeye göre hazırlanmış demo uygunluk görünümüdür. Banka onayı yerine geçmez.',
  'creditResultMonthlyPayment': 'Tahmini aylık taksit',
  'creditResultTotalCost': 'Toplam geri ödeme',
  'creditResultPaymentLoad': 'Taksit / gelir',
  'creditResultDtiAfter': 'Kredi sonrası borç oranı',
  'creditResultGuidance':
      'Gerçek banka akışına geçmeden önce senaryoları burada karşılaştır. Daha düşük taksit yükü ve daha düşük borç oranı genelde daha güvenli bir plan sunar.',
  'subsRenewalLabel': 'Yenileme',
  'subsActivityLabel': 'Aktivite',
  'profileDailyBriefing': 'Günlük AI özeti',
  'profileDailyBriefingSub':
      'Hesap durumu, şüpheli aktivite ve tasarruf önerileriyle güne başla',
  'profileLiveSync': 'Canlı veri senkronu',
  'profileLiveSyncLive': 'Canlı',
  'profileLiveSyncBalanced': 'Dengeli',
  'profileLiveSyncSaver': 'Tasarruflu',
  'profileAutoApprove': 'Otomatik onay limiti',
  'profileAutoApproveOff': 'Kapalı',
  'profileSmartNotif': 'Akıllı bildirimler',
  'profileSmartNotifSub':
      'Fraud, yenileme ve onay değişiklikleri için uyarılar',
  'profileFaceId': 'Face ID kilidi',
  'profileFaceIdSub': 'Hassas aksiyonlardan önce biyometrik kilit iste',
  'profileFraudHigh': 'Yüksek hassasiyetli fraud uyarıları',
  'profileFraudHighSub':
      "Vera'nın olağandışı cihaz ve ödeme örüntülerini daha erken yakalamasına izin ver",
  'profileVaultTitle': 'Korumalı oturum kasası',
  'profileVaultSubtitle':
      'Kimlik bilgisi yerel tercihlerden ayrı şekilde saklanır.',
  'profileVaultSignIn': 'Giriş',
  'profileVaultProtectedSince': 'Korunma başlangıcı',
  'profileVaultSyncMode': 'Senkron modu',
  'profileVaultApproval': 'Onay kuralı',
  'profileVaultThisDevice': 'Bu cihaz',
  'profileVaultManualOnly': 'Yalnızca manuel',
  'profileVaultSyncLive': 'Canlı senkron',
  'profileVaultSyncBalanced': 'Dengeli senkron',
  'profileVaultSyncSaver': 'Pil tasarruflu senkron',
  'profileAiToneBadge': 'AI TONU / {tone}',
  'profileConnectedTitle': '{n} bağlı kurum',
  'profileConnectedSubtitle':
      'Canlı bakiyeler mevcut senkron politikası ve feed cache üzerinden tazelenir.',
  'profileConnectedAccount': 'Hesap {last4}',
  'orderTitleBuyGold': '10g altın alımı',
  'orderTitlePayCard': 'Kredi kartı ekstresini öde',
  'orderTitleGoldRate': 'Fiyat',
  'orderTitleDue': 'Vade',
  'orderTitleDueToday': 'Bugün',
  'orderPillReady': 'HAZIR',
  'orderPillSent': 'BANKADA',
  'orderPillDismissed': 'İPTAL',
  'creditTitle': 'Kredi',
  'creditSubtitle': 'Gerçek gelirine göre borçlanma.',
  'creditScoreLabel': 'KREDİ PUANI',
  'openCredit': 'Krediyi aç',
  'creditSummaryCardSubtitle':
      'Başvuru öncesi taksit, toplam geri ödeme ve borç yükünü modelle.',
  'wealthTitle': 'Servet',
  'wealthSubtitle': 'Paranız otonom çalışıyor.',
  'portfolio': 'PORTFÖY',
  'ytd': 'YBB',
  'today': 'bugün',
  'autonomousWealth': 'Otonom Servet',
  'profile': 'PROFİL',
  'moveLimit': 'HAREKET LİMİTİ',
  'approval': 'ONAY',
  'activityFeed': 'Aktivite akışı',
  'explainability': 'Açıklanabilirlik',
  'undo': 'Geri al',
  'viewDetails': 'Detayları gör',
  'plansTitle': 'Planlar',
  'plansSubtitle': 'Sessiz para sızıntılarını yakala.',
  'subscriptionIntelligence': 'ABONELİK ZEKASI',
  'detectedPlans': 'Tespit edilen planlar',
  'filterAll': 'Tümü',
  'filterAttention': 'Dikkat gerek',
  'filterUnused': 'Kullanılmıyor',
  'filterPriceChanges': 'Fiyat değişimi',
  'freezePlan': 'Planı dondur',
  'reviewPlan': 'Planı incele',
  'askUma': "UMA'ya sor",
  'securityTitle': 'Güvenlik & öngörü',
  'securitySubtitle':
      'Vera bankanı bloke etmez; harcama verilerinden öneri ve uyarı üretir.',
  'securityStatBlockedLabel': 'AÇIK',
  'securityStatBlockedSub': 'öneri',
  'securityStatReviewedLabel': 'İNCELENEN',
  'securityStatReviewedSub': 'bu hafta',
  'securityStatDevicesLabel': 'ÖRÜNTÜ',
  'securityStatDevicesSub': 'izlenen',
  'securityAccountSection': 'HARCAMA RADARI',
  'securityClearBody': 'Açık harcama öngörüsü yok — verilerin düzenli görünüyor.',
  'securityActiveBody': 'Vera şu an {n} harcama öngörüsünü incelemeni öneriyor.',
  'securityViewReport': 'UMA AÇIKLAMASI',
  'securityDecisionKept':
      'Bu öngörüyü izlemede tuttun. Benzer hareketlerde sana tekrar hatırlatırım.',
  'securityDecisionApproved':
      'Bunu normal harcama olarak işaretledin. Benzer önerileri daha az göstereceğim.',
  'securityPillBlocked': 'ÖNCELİKLİ',
  'securityPillKept': 'İZLEMEDE',
  'securityPillApproved': 'NORMAL',
  'fraudAlertTitle': 'Yeni harcama öngörüsü',
  'spendingInsightAlertTitle': 'Yeni harcama öngörüsü',
  'securityInsightsSection': 'Harcama öngörüleri',
  'securityTipsSection': 'Bankanda seni koru',
  'securityTipBankTitle': 'İşlemi bankanda onayla',
  'securityTipBankBody':
      'Vera yalnızca öneri verir. Transfer, ödeme ve kart işlemlerini her zaman kendi banka uygulaman üzerinden tamamla.',
  'securityTipPinTitle': 'PIN ve biyometri',
  'securityTipPinBody':
      'Profil ayarlarından Face ID ve fraud bildirimlerini aç; Vera şüpheli örüntüleri sana bildirir.',
  'securityTipAlertsTitle': 'Veri kaynağını güncel tut',
  'securityTipAlertsBody':
      'Ekstre veya fiş yükle, manuel işlem ekle — öngörüler ne kadar güncel verin varsa o kadar isabetli olur.',
  'fraudReasonOutlier':
      'Bu harcama {median} TL seviyesindeki tipik tutarının belirgin şekilde üstünde ve alışılmış düzenin {ratio} katı.',
  'fraudNameRoundTransfer': 'Yuvarlak transfer · {amount} TL',
  'fraudReasonRoundTransfer':
      'Yüksek ve yuvarlak tutarlı transferler çoğu zaman normaldir, ancak Vera hızlı onay için bunları öne çıkarır.',
  'fraudNameBurst': '{merchant} kısa sürede {count} kez geçti',
  'fraudLocationBurstTotal': 'Toplam harcama {total} TL',
  'fraudReasonBurst':
      'Aynı iş yeri kısa bir aralıkta {count} kez göründü. Beklenen bir hareket olup olmadığını kontrol et.',
  'profileAndSettings': 'Profil & Ayarlar',
  'sectionAppearance': 'GÖRÜNÜM & TEMA',
  'sectionAi': 'YAPAY ZEKA TERCİHLERİ',
  'sectionNotifications': 'BİLDİRİMLER',
  'sectionConnected': 'BAĞLI KURUMLAR',
  'sectionAccount': 'HESAP',
  'sectionLanguage': 'DİL',
  'brandPalette': 'Marka paleti',
  'mood': 'Mod',
  'moodLight': 'Açık',
  'moodDark': 'Koyu',
  'vibe': 'Stil',
  'vibeCalm': 'Sakin',
  'vibeStandard': 'Standart',
  'vibeBold': 'Cesur',
  'language': 'Dil',
  'signOut': 'Çıkış yap',
  'umaTone': 'Uma tonu',
  'toneConcise': 'Kısa',
  'toneCoach': 'Koç',
  'toneProactive': 'Proaktif',
  'scanReceipt': 'Fiş tara',
  'scanReceiptTitle': 'Fiş veya ekran tara',
  'scanReceiptSubtitle':
      'Fiş, fatura veya banka ekranını okutup işleme dönüştür.',
  'scanHint':
      'Net bir fotoğraf kullan. Vera iş yeri, toplam ve satırları çıkarır.',
  'takePhoto': 'Fotoğraf çek',
  'pickFromGallery': 'Galeriden seç',
  'scanReading': 'AI okuyor...',
  'scanTotalLabel': 'Toplam',
  'scanAgain': 'Yeniden tara',
  'addToTransactions': 'İşlemlerime ekle',
  'addedToTransactions': 'İşlemlerine eklendi',
  'scanNoTotal': 'Tutar okunamadı, fişi tekrar tara.',
  'parsedByAi': 'AI',
  'parsedFallback': 'DEMO',
  'scanFallbackWarning':
      'AI servisine ulaşılamadı veya fiş çözümlenemedi. Lütfen işlemi manuel gir.',
  'scanFallbackAction': 'AI çalışmadı — manuel gir',
  'savingsStoryLabel': 'BU AY TASARRUF',
  'savingsStoryFooter': "Uma'nın 3 önerisiyle",
  'savingsStoryDelta': 'Geçen aya göre %{pct} daha az',
  'upcomingBills': 'Yaklaşan ödemeler',
  'billPayViaUma': 'Uma ile öde',
  'daysLeft': '{n} gün kaldı',
  'statementImport': 'Ekstre yükle',
  'statementImportTitle': 'Banka ekstresini yükle',
  'statementImportSubtitle':
      'PDF veya görsel olarak ekstreni yükle, AI işlemleri çıkarsın.',
  'pickStatementFile': 'Dosya seç (PDF / görsel)',
  'statementImportHint':
      'PDF veya görsel yükle. Vera bakiye ve hareketleri cihaz üzerinde okur.',
  'statementParsing': 'AI ekstreyi okuyor...',
  'closingBalance': 'Kapanış bakiyesi',
  'detectedTransactions': '{n} işlem tespit edildi',
  'statementImportAgain': 'Yeniden yükle',
  'statementImported': 'Ekstre işlemlerine eklendi',
  'statementNoTransactions': 'Ekstreden işlem çıkarılamadı.',
  'importToVera': "Vera'ya aktar",
  'statementFallbackWarning':
      'AI servisine ulaşılamadı veya ekstre çözümlenemedi. Lütfen işlemleri manuel gir.',
  'importFallbackNextTitle': 'Sonraki en iyi adım',
  'importFallbackNextBody':
      'İstersen işlemleri manuel ekleyebilir veya Uma\'dan bunu senin adına kaydetmesini isteyebilirsin.',
  'importFallbackAskUma': 'Uma\'dan kaydetmesini iste',
  'importFallbackManualEntry': 'Manuel işlem ekle',
  'statementFallbackAction': 'AI çalışmadı — manuel gir',
  'openBankApp': '{bank} uygulamasını aç',
  'umaForwardNote':
      'İşlem bankanda tamamlanır. Vera SMS veya ekstreyle sonucu yakalar.',
  'forwardedToBank': "{bank}'a yönlendirildi · Vera takip ediyor",
  'keep': 'Vazgeç',
  'thisMonthsAiPlan': 'Bu ayın AI önerisi',
  'aiPlanFooter': "Uma'nın önerisi — bankanda uygula, Vera kaydını tutar.",
  'applyAtBank': 'Bankamda uygula',
  'securityVeraSideBanner':
      'Vera bir banka veya ödeme kuruluşu değildir. Hesabına erişemez, kartını durduramaz; yalnızca getirdiğin verilerle harcama öngörüsü sunar.',
  'statusAllClear': 'Öngörü yok',
  'statusMonitoring': '{n} öneri',
  'securityRecentActivity': 'Harcama öngörüleri',
  'securityScanning': 'Analiz ediliyor...',
  'liveAnomalyDetected': 'Verilerinden',
  'highRiskConfidence': 'Yüksek öncelik',
  'reviewedSignal': 'Düşük öncelik',
  'keepBlocked': 'İzlemeye devam',
  'thisWasMe': 'Normal harcama',
  'emailField': 'E-posta',
  'passwordField': 'Şifre',
  'loginTitle': "Vera'ya giriş yap",
  'loginSubtitle':
      'Hesabınla giriş yap; profil tercihleri ve AI aksiyonları çıkış yapana kadar yerelde kalır.',
  'loginEmailHint': 'ornek@vera.app',
  'loginFooter':
      'Firebase yapılandırılmadıysa giriş başarısız olur. .env\'i kontrol et.',
  'loginDemoHint':
      'Hızlı deneme için demo hesabı: e-posta "{email}", şifre "{password}".',
  'umaVoiceStart': 'Sesle sor',
  'umaVoiceStop': 'Dinlemeyi durdur',
  'umaVoiceListening': 'Dinliyorum...',
  'umaVoicePermissionDenied':
      'Mikrofon izni gerekli. Cihaz ayarlarından Vera için mikrofonu aç.',
  'umaVoiceUnavailable': 'Bu cihazda ses tanıma kullanılabilir değil.',
  'umaToolGoalCreated': 'Tamam, {target} TL\'lik hedefi oluşturdum.',
  'umaToolBillAdded': '{name} faturasını {days} gün sonrası için ekledim.',
  'umaToolExpenseAdded': '{name} ({amount} TL) işlemini kaydettim.',
  'umaSuggestionPay': 'Kredi kartımı öde',
  'umaSuggestionSubs': 'Aboneliklerimi göster',
  'umaSuggestionAnalyze': 'Harcamalarımı analiz et',
  'voiceCommandTooltip': 'Sesli komut',
  'requireConfirmation': 'Onayımı iste',
  'requireConfirmationDesc':
      'Eyleme geçmeden önce her zaman bir onay kartı göster',
  'orderFrom': 'Kimden',
  'orderTo': 'Kime',
  'orderAmount': 'Tutar',
  'accountTilePersonal': 'Kişisel bilgiler',
  'accountTileEmail': 'E-posta',
  'accountTileSecurity': 'Güvenlik & PIN',
  'accountTileStorage': 'Veri saklama',
  'accountTileHelp': 'Yardım & destek',
  'accountTileHelpValue': 'SSS, destek ve hata bildirimi',
  'infoDisplayName': 'Görünen ad',
  'infoMember': 'Üyelik',
  'infoMemberDescription':
      'Demo oturumu bu cihazda yerel olarak çalışır.',
  'infoSignInMethod': 'Giriş yöntemi',
  'infoEmailLabel': 'E-posta adresi',
  'infoEmailUsage': 'Nerede kullanılır',
  'infoEmailDescription':
      'Demo oturumu için kullanılıyor. Veriler cihazda kalır, sunucuya gönderilmez.',
  'infoEmailDescriptionLive':
      'Bu adres Firebase Auth girişi, hesap kurtarma ve önemli Vera bildirimleri için kullanılır.',
  'authMethodGoogle': 'Google ile devam et',
  'authMethodEmail': 'E-posta ve şifre',
  'authMethodDemo': 'Demo kasası',
  'infoSessionVault': 'Oturum kasası',
  'infoSessionVaultDescription':
      'Oturum verisi flutter_secure_storage ile cihazda şifreli saklanır. Yalnızca bu cihazda erişilebilir.',
  'infoFaceId': 'Face ID',
  'infoFaceIdOn': 'Etkin · oturum açıldığında biyometrik doğrulama istenir.',
  'infoFaceIdOff': 'Kapalı · sadece şifre / demo girişi yeterli.',
  'infoFraudAlerts': 'Fraud uyarıları',
  'infoFraudAlertsOn':
      'Etkin · şüpheli işlem tespit edilince yerel bildirim gönderir.',
  'infoFraudAlertsOff': 'Kapalı · uyarılar sadece uygulama içinde görünür.',
  'infoSyncMode': 'Senkron modu',
  'infoLocalData': 'Yerel veri',
  'infoLocalDataDescription':
      'OCR fişleri ve banka eklemeleri SharedPreferences\'ta tutuluyor. "Verileri dışa aktar" P1 backlog\'unda.',
  'helpFaqQ1': 'Vera bankama bağlanır mı?',
  'helpFaqA1':
      'Hayır. Vera AISP/PSP lisansı taşımıyor. Veriyi sen getiriyorsun: PDF ekstre, fiş fotoğrafı, ekran görüntüsü ya da manuel giriş. Vera AI ile birleştirip yorumluyor ve doğru bankaya yönlendiriyor.',
  'helpFaqQ2': 'Verim nerede saklanıyor?',
  'helpFaqA2':
      'Hassas oturum bilgisi flutter_secure_storage ile şifreli yerel kasada; OCR ve ekleme işlemleri SharedPreferences\'ta. Sunucu yok, üçüncü tarafa veri gitmiyor.',
  'helpFaqQ3': 'Gemini API key yoksa ne olur?',
  'helpFaqA3':
      'OCR ve ekstre import deterministic fallback ile çalışır (DEMO rozeti görünür). UMA chat heuristic intent router ile cevap verir. Tüm akış çalışır, sadece AI parsing canlı değildir.',
  'helpContact': 'İletişim',
  'demoUser': 'Demo kullanıcı',
  'notSet': 'Belirtilmedi',
  'dragDropHint': 'Dosyayı buraya sürükle bırak',
  'dragDropActive': 'Dosyayı bırak',
  'dragDropOr': 'veya aşağıdaki butonları kullan',
  'umaGreeting':
      'Merhaba {name}. İçe aktardığın işlemleri okudum. Kart faturası ödeyebilir, transfer hazırlayabilir veya altın fiyatına bakabiliriz. Para hareketi hep senin bankanda olur; ben hazırlığı yapar, sonucu takip ederim.',
  'umaReplyBuyGold':
      '{bank} üzerinden 10 gram altın alım planını hazırladım. Uygulamayı açıp onayla; SMS\'ten sonucu takip ederim.',
  'umaReplyPayCard':
      '{bank} ekstresi ödemeye hazır. Uygulamayı doğrudan ödeme ekranında açacağım.',
  'umaReplyMoveSavings':
      'Acil durum fonu planın hazır. Bankanı aç ve transferi orada onayla. Bu transferden sonra hedefe %{pct} ulaşıyorsun.',
  'umaReplySubscriptions':
      'Bakmaya değer {n} planın var. Aylık abonelik toplamın {total} civarında.',
  'umaReplySubscriptionsEmpty':
      'Şu an aktif abonelik tespit etmedim. Bir ekstre yüklersen Vera tekrarlayan ödemeleri bulup listeye ekler.',
  'umaReplyAnalyze':
      'Bu ay en çok {top} kategorisinde {topAmount} harcadın. Toplam çıkış {spending}. İstersen kategori limitleri ayarlayabiliriz.',
  'umaReplyAnalyzeEmpty':
      'Henüz analiz edebileceğim işlem yok. Fiş tara veya bir ekstre yükle, sonra harcamayı parçalayalım.',
  'umaReplyExplainWealth':
      'Vera portföyünü içe aktardığın hesaplar üzerinden takip ediyor. Bu ay hisse kovan biraz yüksek görünüyor; bir sonraki bankayı açtığında altın veya nakide takviye önerim olacak.',
  'umaReplyLoan':
      'İçe aktardığın ekstrelerdeki gelir ve borç verisine göre orta tutarda kişisel kredi için güçlü görünüyorsun. Kredi simülasyonunu açarsan tutar ve vadeyi güvenli bir aralığa birlikte ayarlayabiliriz.',
  'umaReplySecurity':
      'O transferi işaretledim çünkü alıcı bir kez daha görünmüştü ve cihaz konumu olağan örüntünle eşleşmedi. Vera bankanı bloklamaz — uyarır, kararı sen verirsin.',
  'umaReplyFallback':
      'Bunu da yapabilirim. İstersen kısa bir finansal değerlendirme veya güvenli bir sonraki adım hazırlayayım.',
  'umaReplyNeedsData':
      'Henüz yeterli kullanıcı verisi görünmüyor. Ekstre yükle, fiş tara, manuel işlem ekle veya bir hedef kur; sonra sana daha net yardımcı olayım.',
  'umaReplyLocalOnly':
      'Şu anda yerel moddayım. Banka aksiyonları başlatamam ama hedef kurma, manuel işlem kaydetme ve veri düzenleme konularında yine yardımcı olabilirim.',
  'umaReplyToolNeedsDetails':
      'Bunu tamamlamak için bir iki ayrıntı daha gerekiyor. Tutar, ad veya vade bilgisini biraz daha net yazar mısın?',
  'umaToolProposal':
      '{summary} hazır. İstersen bunu sohbet içinden onaylayıp uygulayayım.',
  'umaThinking': 'Uma düşünüyor...',
  'umaAskHint': "Uma'ya sor...",
  'umaNewChat': 'Yeni sohbet',
  'umaStatusOnline': 'AI asistan · çevrimiçi',
  'umaStatusLocalOnly': 'Yerel mod · sınırlı AI',
  'umaStatusNeedsData': 'Hazır · veri bekliyor',
  'umaAssistantBadge': 'UMA',
  'umaToolBadge': 'AKSİYON TAMAMLANDI',
  'umaFallbackBadge': 'SONRAKİ ADIM',
  'umaSystemBadge': 'SİSTEM',
  'umaConfidenceLabel': 'Güven %{pct}',
  'umaConfirmAction': 'Aksiyonu onayla',
  'umaActionConfirmedToast': 'Uma aksiyonu uyguladı',
  'umaSourceReadiness': 'Sistem durumu',
  'umaSourceMemory': 'Kullanıcı hafızası',
  'umaWhyGoldPlan':
      'Bağlı hesap ve mevcut birikim akışına göre bu altın aksiyonu uygun görünüyor.',
  'umaWhyBillPlan':
      'Yaklaşan ödeme ve mevcut hesap bağlamı bu fatura aksiyonunu destekliyor.',
  'umaWhyGoalPlan':
      'Mevcut hedef ilerlemen ve nakit ritmine göre bu birikim adımı anlamlı görünüyor.',
  'umaWhySubscriptions':
      'Abonelik listesi ve son tekrar eden işlemlerine dayanarak bu özeti ürettim.',
  'umaWhySpending':
      'Son işlemlerinden çıkan kategori dağılımına göre bu cevabı verdim.',
  'umaWhyWealth':
      'Portföy bucket dağılımı ve son varlık girişlerine dayanıyorum.',
  'umaWhyLoan':
      'Gelir, gider ve borç ritmine dair mevcut sinyalleri kullanarak yorumluyorum.',
  'umaWhySecurity':
      'Uyarı dili, görülen anomali ve kullanıcı kontrolü ilkesine göre sade tutuldu.',
  'umaWhyInsufficientData':
      'Yeterli veri veya kaynak kapsamı olmadığı için kesin konuşmuyorum.',
  'umaWhyLocalOnly':
      'Firebase veya Gemini tarafı hazır olmadığında yalnızca yerel bağlama dayanıyorum.',
  'umaWhyGroundedAnswer':
      'Bu cevap uygulama içindeki mevcut veri kaynaklarına dayalı olarak üretildi.',
  'umaWhyFallbackSoft':
      'Daha emin konuşmak için biraz daha veri girişi iyi olur.',
  'umaWhyFallbackDirect':
      'Bu konuda emin olmak için veri kapsamı yeterli değil; tahmin yürütmüyorum.',
  'umaWhyMissingContext':
      'Eksik bağlamı tamamladığında bunu daha güvenli şekilde yapabilirim.',
  'umaToolExecutedWhy':
      'Onayının ardından bu eylem uygulama içindeki veriye kaydedildi.',
  'umaPolicyNeedsConfirmation':
      'Bu eylem verini değiştireceği için önce onayını istiyorum.',
  'umaPolicyMissingContext':
      'Bu eylemi güvenle yapmak için birkaç kritik bilgi eksik.',
  'umaPolicyReady': 'Bağlam yeterli görünüyor, eylem hazır.',
  'umaPolicyBlocked': 'Bu eylem şu an mevcut politika nedeniyle engellendi.',
  'umaPolicyGoalSummary': '{amount} tutarında bir hedef oluşturma',
  'umaPolicyGoalSummaryUnknown': 'Hedef oluşturma',
  'umaPolicyBillSummary': '{name} faturasını {days} gün sonrası için ekleme',
  'umaPolicyBillSummaryUnknown': 'Fatura ekleme',
  'umaPolicyExpenseSummary': '{name} işlemini {amount} olarak kaydetme',
  'umaPolicyExpenseSummaryUnknown': 'Manuel gider kaydetme',
  'umaSuggestionBuyGold': '10g altın al',
  'umaSuggestionMoveSavings': "2500 TL'yi birikime aktar",
  'umaActionPolicy': 'EYLEM POLİTİKASI',
  'umaActionPolicyDesc':
      'Vera para hareketini bankanda yapar; sen her zaman onay verirsin.',
  'umaAuditTrailTitle': 'Denetim izi',
  'umaAuditTrailSubtitle':
      'Uma yanıtları, bankaya yönlendirmeler ve geri bildirim kararların için imzalı yerel kayıt.',
  'umaAuditTrailEmpty': 'Henüz imzalı Uma aksiyonu yok.',
  'umaAuditTrailCount': 'Bu cihazda {count} imzalı aksiyon kaydı var.',
  'umaAuditTrailEmptyDetail':
      'Henüz imzalı aksiyon görünmüyor. Uma\'dan bir şey yapmasını iste; güven izi burada belirecek.',
  'umaAuditNoteAttached': 'Not eklendi',
  'umaAuditReplyGenerated': 'Yanıt üretildi',
  'umaAuditForwarded': 'Bankaya yönlendirildi',
  'umaAuditKeptForReview': 'İnceleme için tutuldu',
  'umaAuditHelpfulFeedback': 'Yararlı geri bildirim',
  'umaAuditCorrectionFeedback': 'Düzeltme geri bildirimi',
  'umaAuditMemoryUpdated': 'Hafıza güncellendi',
  'umaAuditConfidenceReduced': 'Düşük güvenli cevap',
  'categoryBudgetLabel': 'BU AYKİ HARCAMALAR',
  'categoryOther': 'Diğer',
  'receiptDefaultName': 'Fiş',
  'categoryBudgetTopHint': 'En çok {category} · %{pct}',
  'categoryRemaining': 'kalan {amount}',
  'categoryOver': 'limit aşıldı · {amount}',
  'categoryNoLimit': 'limit yok',
  'categoryLimitEditTitle': 'Kategori limiti',
  'categoryLimitEditSubtitle':
      '{category} için aylık limiti belirle. Vera her harcamada kalan tutarı gösterir.',
  'categoryLimitField': 'Aylık limit (TL)',
  'categoryLimitSave': 'Kaydet',
  'categoryLimitClear': 'Limiti kaldır',
  'goalsSectionTitle': 'Hedeflerin',
  'goalEmergencyFund': 'Acil durum fonu',
  'goalProgress': '%{pct} yolda',
  'goalRemaining': '{amount} kaldı',
  'goalEditTitle': 'Hedefini düzenle',
  'goalEditTarget': 'Hedef tutar (TL)',
  'goalEditSaved': 'Biriken tutar (TL)',
  'goalEditSave': 'Kaydet',
  'goalEditFooter': 'Vera hedef paranı izler; Uma her ay yeni öneri yapar.',
  'goalEtaMonths': '{n} ayda tamam',
  'goalEtaReached': 'Hedefe ulaştın 🎯',
  'bankActionsTitle': 'Banka seçenekleri',
  'bankActionsDelete': 'Bankayı sil',
  'bankActionsCancel': 'Vazgeç',
  'bankActionsConfirmTitle': 'Silinsin mi?',
  'bankActionsConfirmBody':
      '{name} listeden silinecek. Bakiye toplamından çıkarılır.',
  'bankDeleted': '{name} silindi',
  'bankActionsFeedNote':
      'Bu banka demo verisinde geliyor — silinemez. Kendi eklediklerini silebilirsin.',
  'umaPromptSend': 'Bir arkadaşa para göndermek istiyorum.',
  'umaPromptRequest': 'Bir arkadaştan para iste.',
  'umaPromptTopUp': 'Hesabıma yükleme yapmak istiyorum.',
  'umaPromptPay': 'Kredi kartı faturamı ödemek istiyorum.',
  'umaPromptAnalyze': 'Bu ay harcamalarımı analiz et.',
  'txnDetailWhen': 'Zaman',
  'txnDetailCategory': 'Kategori',
  'txnDetailDirection': 'Yön',
  'txnDetailIncoming': 'Gelen',
  'txnDetailOutgoing': 'Giden',
  'txnDetailAskPrompt': '{name} işlemini değerlendir, {amount} normal mi?',
  'billDetailPrompt': '{name} faturası {amount}, {days} gün kaldı. Ne yapayım?',
  'notifTitle': 'Bildirimler',
  'notifSubtitle': '{n} sinyal Uma tarafından izleniyor',
  'notifEmpty': 'Her şey yolunda. Uma sessizce izlemeye devam ediyor.',
  'notifMarkAllRead': 'Tümünü okudum',
  'notifClear': 'Temizle',
  'notifRead': 'Okundu',
  'notifDismiss': 'Kaldır',
  'notifBlockedDefault': 'Vera bu işlemi anomali olarak işaretledi.',
  'notifPriceIncreaseTitle': '{name} zamlandı',
  'notifPriceIncreaseBody':
      'Aylık +{delta} · şimdi {price}. Plans ekranında dondurabilirsin.',
  'notifUnusedTitle': '{name} kullanılmıyor',
  'notifUnusedBody':
      'Son kullanım: {last}. Vera bunu sessiz para sızıntısı olarak işaretledi.',
  'notifBillTitle': '{name} faturası yaklaşıyor',
  'notifBillBody':
      'Ödenecek tutar {amount}. Uma ile öde veya bankan üzerinden tamamla.',
  'proactiveBadge': 'VERA FARK ETTİ',
  'proactiveBillTitle': '{name} faturası yaklaşıyor',
  'proactiveBillBody':
      '{amount} · {days} gün kaldı. Uma ödeme planını hazırlasın mı?',
  'proactiveBillCta': 'Uma ile öde',
  'proactiveBillPrompt': '{name} faturamı ödemek için yardım et.',
  'proactivePriceTitle': '{name} bu ay zamlandı',
  'proactivePriceBody':
      'Aylık +{delta} artış. Aboneliği dondurmak ister misin?',
  'proactivePriceCta': 'Aboneliklere git',
  'proactiveUnusedTitle': '{name} kullanılmıyor',
  'proactiveUnusedBody':
      'Son kullanım: {last}. Sessiz para sızıntısı olabilir.',
  'proactiveUnusedCta': 'Aboneliklere git',
  'proactiveHealthyTitle': 'Şimdilik kritik bir sinyal yok',
  'proactiveHealthyBody':
      'Şu anda öne çıkan bir fatura, fiyat artışı veya boşa giden abonelik görünmüyor.',
  'proactiveHealthyCta': 'Uma yorumlasın',
  'proactiveEmptyTitle': 'Vera henüz izlenecek sinyal bulmadı',
  'proactiveEmptyBody':
      'Bir ekstre yüklediğinde yaklaşan ödemeler, abonelikler ve küçük riskler burada görünür.',
  'proactiveEmptyCta': 'Ekstre yükle',
  'exportTile': 'Verilerimi dışa aktar',
  'exportTileValue': 'JSON · cihaza özel',
  'exportTitle': 'Vera verilerin',
  'exportSubtitle':
      'İçe aktarılan işlemler, eklediğin bankalar, hedefin ve abonelik listen. Cihazından dışarı bilgi göndermeden kopyalanabilir.',
  'exportCopy': 'JSON kopyala',
  'exportCopied': 'Pano\'ya kopyalandı',
  'onbStep1Title': "Vera'ya hoş geldin",
  'onbStep1Subtitle':
      'Önce kullanmak istediğin dili seç. Dil her zaman ayarlardan değiştirilebilir.',
  'onbStep2Title': 'Görünüşünü ayarla',
  'onbStep2Subtitle':
      'Markanın paletini ve modunu seç. Tema daha sonra da değiştirilebilir.',
  'onbStep3Title': 'Verini getir',
  'onbStep3Subtitle':
      'Vera bankana bağlanmaz — sen ekstreni getirirsin, Vera anlamlandırır. Şimdi başla veya sonra ekle.',
  'onbContinue': 'Devam et',
  'onbStart': 'Veraya başla',
  'onbSkip': 'Atla',
  'onbBack': 'Geri',
  'onbImportNow': 'Ekstre yükle',
  'onbScanNow': 'Fiş tara',
  'onbContinueWithoutImport': 'İçe aktarmadan devam et',
  'onbPalettePreviewTitle': 'Canlı önizleme',
  'onbPalettePreviewBody':
      'Seçtiğin görünüm kartlar, AI vurguları ve genel tona anında yansır.',
  'onbBlankCanvasTitle': 'Boş başlamak da olur',
  'onbBlankCanvasBody':
      'İstersen şimdi hiçbir şey import etmeden devam et; Vera seni içeride ilk adımda da yönlendirir.',
  'demoResetTile': 'Demo verisini sıfırla',
  'demoResetTileValue': 'İçe aktarılanları ve eklemeleri temizle',
  'demoResetTitle': 'Demo verisini sıfırla?',
  'demoResetBody':
      'İçe aktarılan işlemler, eklediğin bankalar ve hedef ilerlemen başlangıç durumuna döner.',
  'demoResetConfirm': 'Sıfırla',
  'demoResetCancel': 'Vazgeç',
  'demoResetDone': 'Demo durumuna döndü',
  'goalEmptyPrompt': 'Henüz hedef belirlemedin — dokun ve ekle.',
  'goalEmptyHint':
      'Önce bir hedef koy, sonra Uma aylık ritmine göre ne kadar ayırman gerektiğini çıkarsın.',
  'goalEmptyCta': 'Hedef kur',
  'goalMonthsLabel': 'KAÇ AYDA',
  'goalMonthsOption': '{n} ay',
  'goalAdviceSummary': 'Aylık {amount} · {months} ay',
  'goalCalculate': 'Hesapla',
  'goalPresetEmergency': 'Acil Durum (6 Ay) · {amount}',
  'goalPresetVacation': 'Tatil (3 Ay) · {amount}',
  'goalPresetCar': 'Araç (12 Ay) · {amount}',
  'fieldName': 'Adı',
  'fieldAmountTl': 'Tutar (TL)',
  'fieldDate': 'Tarih',
  'fieldCategory': 'Kategori',
  'fieldDescription': 'Tanım',
  'fieldLabelOptional': 'Etiket (opsiyonel)',
  'actionAdd': 'Ekle',
  'actionUpdate': 'Güncelle',
  'actionDelete': 'Sil',
  'actionManual': 'Manuel',
  'addBillTitle': 'Yeni fatura ekle',
  'editBillTitle': 'Faturayı düzenle',
  'addBillNameHint': 'Örn. Türk Telekom',
  'dueDateLabel': 'Son ödeme tarihi',
  'addBillCta': 'Fatura ekle',
  'noTrackedBillsTitle': 'Henüz takip edilen fatura yok',
  'noTrackedBillsBody': 'Ödeme tarihinden 1 gün önce Vera sana hatırlatır.',
  'billKindCard': 'Kart',
  'billKindInternet': 'İnternet',
  'billKindElectric': 'Elektrik',
  'billKindWater': 'Su',
  'billKindGas': 'Doğalgaz',
  'billKindRent': 'Kira',
  'billKindOther': 'Diğer',
  'addManualTxnTitle': 'Manuel işlem ekle',
  'txnTypeExpense': 'Gider',
  'txnTypeIncome': 'Gelir',
  'addManualTxnNameHint': 'Örn. Migros',
  'aiSuggestionLabel': 'Uma önerisi',
  'acceptSuggestion': 'Kabul et',
  'categoryMarket': 'Market',
  'categoryFood': 'Yeme & İçme',
  'categoryFuel': 'Akaryakıt',
  'categoryBill': 'Fatura',
  'categoryHealth': 'Sağlık',
  'categoryEducation': 'Eğitim',
  'categoryEntertainment': 'Eğlence',
  'categoryTransfer': 'Transfer',
  'categorySalary': 'Maaş',
  'categorySubscription': 'Abonelik',
  'categoryMusic': 'Müzik',
  'categoryVideo': 'Video',
  'categoryStorage': 'Depolama',
  'categoryDeveloper': 'Geliştirici',
  'categoryAi': 'AI',
  'noTransactionsTitle': 'Henüz işlem yok',
  'noTransactionsBody':
      'İlk işlemini ekle, ekstre yükle veya fiş fotoğrafı çek.',
  'addHoldingTitle': 'Portföye varlık ekle',
  'addHoldingSubtitle':
      'Aşağıdaki bucket\'lardan birini seçip TL değerini gir. Uma ağırlıkları otomatik hesaplar.',
  'addHoldingHint': 'Örn. THYAO veya XU100 ETF',
  'holdingValueLabel': 'Değer (TL)',
  'removeHolding': 'Bu varlığı kaldır',
  'noWealthActionsTitle': 'Uma henüz aksiyon almadı',
  'noWealthActionsBody':
      'Otonom modu açtığında öneriler ve rebalans hareketleri burada görünür.',
  'startPortfolioTitle': 'Portföyünü oluşturmaya başla',
  'startPortfolioBody':
      'Hisse, altın, nakit veya kripto varlıklarını ekle. Uma sapmayı izleyip önerilerini buraya yazar.',
  'wealthApprovalAuto': 'Oto',
  'wealthApprovalHybrid': 'Hibrit',
  'wealthActionReversed': 'GERİ ALINDI',
  'holdingBucketEquity': 'Hisse',
  'holdingBucketGold': 'Altın',
  'holdingBucketCash': 'Nakit',
  'holdingBucketCrypto': 'Kripto',
  'holdingBucketFunds': 'Fon',
  'holdingBucketBonds': 'Tahvil',
  'subscriptionsAttentionCount': 'Bu döngüde {n} plan dikkat istiyor',
  'noSubscriptionsDetectedTitle': 'Henüz tespit edilen abonelik yok',
  'noSubscriptionsDetectedBody':
      'Ekstre yükle veya fiş tara — Vera tekrar eden ödemeleri otomatik tespit eder.',
  'noSubscriptionsForFilterTitle': 'Bu filtreyle eşleşen abonelik yok',
  'noSubscriptionsForFilterBody': 'Diğer filtreleri deneyebilirsin.',
  'subsAlertSavingsTitle': 'Aylık tasarruf potansiyeli',
  'subsAlertSavingsMessageEmpty':
      'Henüz abonelik tespit edilmedi. Ekstre yükle veya manuel ekle, Vera takip etsin.',
  'subsAlertSavingsMessageActive':
      'Vera, rutinini bozmadan dondurabileceğin veya alt pakete düşürebileceğin abonelikler buldu.',
  'subsAlertSavingsMetric': 'KAZANÇ',
  'subsAlertPriceTitle': 'Fiyat artışı tespit edildi',
  'subsAlertPriceMessageNone': 'Bu dönem alışılmadık fiyat sıçraması yok.',
  'subsAlertPriceMessageSome':
      'Bir veya daha fazla planın fiyatı geçen aya göre arttı.',
  'subsAlertPriceMetric': 'ARTAN',
  'subsAlertUnusedTitle': 'Az kullanılan planlar',
  'subsAlertUnusedMessageNone': 'Tüm abonelikler sağlıklı kullanılıyor.',
  'subsAlertUnusedMessageSome':
      'Son aktivite örüntüne göre {n} plan az kullanılıyor görünüyor.',
  'subsAlertUnusedMetric': 'BOŞTA',
  'subsInsightEmpty':
      'Vera ekstreni veya fişlerini analiz edip aboneliklerini bu listede toplar.',
  'subsInsightHealthy':
      'Abonelikler bu ay sağlıklı görünüyor. Acil bir tasarruf kaçağı yok.',
  'subsInsightNeedsAttention':
      'Hızlıca incelemen gereken {n} abonelik var. Vera, kullanılmayanları dondurarak ve fiyat artışı olanları alt pakete düşürerek aylık {amount} kadar geri kazanabileceğini hesaplıyor.',
  'subsDetectedFromImport': 'İçe aktarılan işlemden tespit edildi',
  'subsSeenInRecentTransactions': '{n}× son işlemlerinde göründü',
  'subsKnownVendorLabel': 'Bilinen abonelik vendor\'ı',
  'subsRecommendationDetected':
      'Vera bu aboneliği import edilen ekstreden tespit etti. Hâlâ kullanıyor musun?',
  'subsStatusActive': 'AKTİF',
  'subsStatusPriceUp': 'FİYAT ARTTI',
  'subsStatusUnused': 'AZ KULLANILIYOR',
  'subsStatusRenewsSoon': 'YAKINDA YENİLENİR',
  'securityEmptyTitle': 'Henüz harcama öngörüsü yok',
  'securityEmptyBody':
      'Ekstre veya fiş yükledikçe Vera olağandışı tutarları ve tekrarlayan harcamaları burada öneri olarak gösterir.',
  'close': 'Kapat',
  'wealthInsightAddPortfolio':
      'Otonom mod kapalı. Portföyünü ekle, Uma sapmayı izlesin ve önerilerini sunsun.',
  'wealthInsightPaused':
      'Otonom mod duraklatıldı. Vera sapmayı izliyor ama para hareketi için onayını bekleyecek.',
  'wealthInsightActive':
      'Uma "{profile}" politikasıyla aktif. Aylık {limit} TL limitine sadık kalarak {count} portföy ayarlaması yaptı veya hazırladı.',
  'goalReached': 'Hedefine ulaştın. Yeni bir hedef belirleyebilirsin.',
  'goalRemainingPlan':
      'Kalan {remaining} TL\'yi {months} ayda biriktirmek için aylık {monthly} TL ayırmalısın.',
  'goalNarrativeNewTarget': 'Hedefin için yeni bir tutar belirleyebilirsin.',
  'goalNarrativeNoData':
      'Henüz işlem verisi yok. Ekstre yükle veya birkaç manuel işlem ekle, Uma sana özel öneri sunsun.',
  'goalNarrativeTrim':
      'Hedef için aylık {monthly} TL ayırman gerek. {topCategory} bütçenden küçük kısmalarla başlamak mantıklı.',
  'todayAt': 'Bugün, {time}',
  'loginContinueEmail': 'E-posta ile devam et',
  'loginEmailPasswordRequired': 'E-posta ve şifre gerekli.',
  'loginFirebaseError': 'Firebase girişi başarısız: {code}.',
  'loginFirebaseReadyFooter':
      'Firebase auth bağlı. Demo modu hackathon akışları için açık.',
  'loginCreateAccount': 'Hesap oluştur',
  'dividerOr': 'veya',
  'signupTitle': 'Hesabını oluştur',
  'signupSubtitleFirebase':
      'Vera kimliğin ve profilin Firebase üzerinden senkronlanacak.',
  'signupSubtitleLocal':
      'Firebase henüz yapılandırılmadı. Bu akış yerel demo modunda devam edecek.',
  'signupFieldFullName': 'Ad Soyad',
  'signupFieldEmail': 'E-posta',
  'signupFieldPassword': 'Şifre',
  'signupFieldConfirmPassword': 'Şifreyi tekrarla',
  'signupHintFullName': 'Vera profilinde görünecek isim',
  'signupHintEmail': 'ornek@eposta.com',
  'signupHintPassword': 'En az 6 karakter kullan',
  'signupHintConfirmPassword': 'Aynı şifreyi tekrar gir',
  'signupErrorNameRequired': 'Lütfen ad soyad gir.',
  'signupErrorInvalidEmail': 'Lütfen geçerli bir e-posta gir.',
  'signupErrorShortPassword': 'Şifre en az 6 karakter olmalı.',
  'signupErrorPasswordMismatch': 'Şifreler eşleşmiyor.',
  'signupErrorAcceptTerms': 'Devam etmek için koşulları onayla.',
  'signupFailedTemplate': 'Hesap oluşturulamadı: {code}.',
  'signupTerms':
      'Vera koşullarını ve yerel demo veri politikasını kabul ediyorum.',
  'signupTermsPrefix': '',
  'signupTermsAnd': ' ve ',
  'signupTermsVera': 'Vera koşullarını',
  'signupTermsPolicy': 'veri politikasını kabul ediyorum',
  'signupTermsTitle': 'Vera Koşulları',
  'signupTermsBody':
      'Vera demo içinde yalnızca açıkça başlattığın işlemleri hazırlar veya yönlendirir. Hesap bilgileri, yüklediğin fişler ve ekstre verileri bu cihazda tutulur.',
  'signupPolicyTitle': 'Veri Politikası',
  'signupPolicyBody':
      'Onboarding, bildirimler, fişler ve Uma bağlamı uygulama yeniden açılsa da bu cihazda kalır. İstersen ayarlardan yerel verileri temizleyebilirsin.',
  'signupStrengthWeak': 'Zayıf',
  'signupStrengthMedium': 'Orta',
  'signupStrengthStrong': 'Güçlü',
  'signupCtaCreate': 'Kayıt ol',
  'signupCtaContinueLocal': 'Yerel olarak devam et',
  'signupAlreadyHaveAccount': 'Zaten hesabın var mı? ',
  'signupSignIn': 'Giriş yap',
  'demoSampleLoaded': 'Örnek hesap verileri yüklendi.',
  'demoBankPrimary': 'Vera Bank — Vadesiz',
  'demoBankSavings': 'Vera Bank — Birikim',
  'demoBillCreditCard': 'Kredi kartı ekstresi',
  'demoBillElectric': 'Elektrik faturası',
  'demoBillInternet': 'İnternet faturası',
  'demoTxnSalary': 'Maaş ödemesi',
  'demoTxnGrocery': 'Market alışverişi',
  'demoTxnFuel': 'Akaryakıt',
  'demoTxnRestaurant': 'Restoran',
  'demoTxnPharmacy': 'Eczane',
  'demoTxnRent': 'Kira ödemesi',
  'demoTxnTransfer': 'EFT — Tasarruf hesabı',
  'demoTxnFamilyIncoming': 'Gelen EFT — Aile',
  'demoTxnAtm': 'ATM nakit çekim',
  'deleteAccount': 'Hesabı sil',
  'deleteAccountTile': 'Hesabı sil',
  'deleteAccountTileValue': 'Bulut verisini kaldır ve çıkış yap',
  'deleteAccountDemoTileValue': 'Bu cihazdaki demo verisini temizle',
  'deleteAccountTitle': 'Hesap silinsin mi?',
  'deleteAccountBody':
      'Vera hesabın, senkronize verilerin ve bu cihazdaki yerel önbellek kalıcı olarak silinecek. Bu işlem geri alınamaz.',
  'deleteAccountDemoBody':
      'Demo hesabı ve bu cihazdaki yerel veriler temizlenecek. Bu işlem geri alınamaz.',
  'deleteAccountConfirm': 'Hesabı sil',
  'deleteAccountCancel': 'Vazgeç',
  'deleteAccountProcessing': 'Hesap siliniyor...',
  'deleteAccountDone': 'Hesap silindi.',
  'deleteAccountError':
      'Hesap silinemedi. Lütfen tekrar giriş yapıp yeniden dene.',
  'deleteAccountRecentLogin':
      'Güvenlik nedeniyle hesabı silmeden önce tekrar giriş yapman gerekiyor.',
  'continueWithGoogle': 'Google ile devam et',
  'googleSignInUnavailable':
      'Google ile giris icin bu buildde Firebase yapilandirilmis olmali.',
};
