part of '../app_strings.dart';

const Map<String, String> _zhStrings = {
  'navHome': '首页',
  'navWealth': '财富',
  'navPlans': '订阅',
  'navSecurity': '安全',
  'navUma': 'UMA',
  'helloLabel': '你好，',
  'defaultUserName': 'Vera 用户',
  'totalNetWorth': '净资产总额',
  'liveFeed': '实时',
  'syncing': '同步中',
  'thisMonth': '本月',
  'connectedAccounts': '已连接账户',
  'refresh': '刷新',
  'syncingDots': '同步中...',
  'recentTransactions': '最近交易',
  'itemsCount': '{n} 笔',
  'itemsVisible': '显示',
  'connectBank': '连接银行',
  'homeFirstStepsTitle': '先一起迈出第一步',
  'homeFirstStepsBody':
      '当第一份数据进入后，Vera 才会真正变得有用。导入一份对账单、扫描一张小票，或添加一家银行，让首页先活起来。',
  'homeFirstStepsHint': '哪怕只完成其中一步，也足以启动建议、余额展示和智能提醒。',
  'connectedAccountsEmptyTitle': '还没有已连接的账户',
  'connectedAccountsEmptyBody': '添加一家银行后，我们就能在首页跟踪余额，也能让 Uma 的动作建议更有上下文。',
  'addBankTitle': '添加银行',
  'addBankSubtitle': 'Vera 不连接银行——你来添加并跟踪余额。',
  'addBankName': '银行名称',
  'addBankLast4': '最后4位',
  'addBankBalance': '余额 (TL)',
  'addBankColor': '颜色',
  'addBankSave': '添加银行',
  'addBankNameRequired': '请填写银行名称。',
  'bankAdded': '已添加 {name}',
  'umaInsight': 'UMA 洞察',
  'umaInsightNoData': 'Vera 还不够了解你。导入一份对账单、扫描一张小票，或添加一家银行，我们就能一起开始建立更聪明的建议。',
  'umaInsightNoTransactions': '目前还没有可见交易。导入你的第一份对账单，或手动添加一笔交易，让 Uma 先理解你的消费节奏。',
  'umaInsightNoPattern': '这一阶段还没有形成足够清晰的消费模式。随着新交易进入，这里的洞察会更准确。',
  'umaInsightTopCategory':
      '你花得最多的是 {category}：{amount}，约占已分析总支出 {total} 的 {share}%。',
  'umaInsightImportCta': '导入对账单',
  'umaInsightAddFirstTxnCta': '添加第一笔交易',
  'umaInsightDeepenCta': '让 Uma 深入分析',
  'spent': '支出',
  'incoming': '收入',
  'creditTitle': '信贷',
  'creditSubtitle': '基于您真实收入的借贷。',
  'creditSummaryCardSubtitle': '计算月供和债务比例',
  'openCredit': '打开信贷',
  'wealthTitle': '财富',
  'wealthSubtitle': '您的资金自主运作。',
  'portfolio': '投资组合',
  'ytd': '年初至今',
  'today': '今日',
  'autonomousWealth': '自主财富',
  'profile': '档案',
  'moveLimit': '操作上限',
  'approval': '审批',
  'activityFeed': '动态',
  'explainability': '可解释性',
  'undo': '撤销',
  'viewDetails': '查看详情',
  'plansTitle': '订阅',
  'plansSubtitle': '提前发现隐性支出。',
  'subscriptionIntelligence': '订阅智能',
  'detectedPlans': '已识别订阅',
  'filterAll': '全部',
  'filterAttention': '需关注',
  'filterUnused': '未使用',
  'filterPriceChanges': '价格变动',
  'askUma': '问 UMA',
  'securityTitle': '安全',
  'securitySubtitle': '您的实时防护层。',
  'profileAndSettings': '档案与设置',
  'sectionAppearance': '外观与主题',
  'sectionAi': 'AI 偏好',
  'sectionConnected': '已连接机构',
  'sectionAccount': '账户',
  'sectionLanguage': '语言',
  'sectionNotifications': '通知与安全',
  'brandPalette': '品牌色',
  'mood': '模式',
  'moodLight': '浅色',
  'moodDark': '深色',
  'vibe': '风格',
  'vibeCalm': '安静',
  'vibeStandard': '标准',
  'vibeBold': '大胆',
  'language': '语言',
  'signOut': '退出登录',
  'umaTone': 'Uma 语气',
  'toneConcise': '简洁',
  'toneCoach': '教练',
  'toneProactive': '主动',
  'scanReceipt': '扫描',
  'scanReceiptTitle': '扫描收据或屏幕',
  'scanReceiptSubtitle': '拍摄收据、账单或银行屏幕，AI 自动转为一笔交易。',
  'scanHint': 'AI 阅读凭据，识别类别和金额，并请求您确认。',
  'takePhoto': '拍照',
  'pickFromGallery': '从相册选择',
  'scanReading': 'AI 正在识别...',
  'scanTotalLabel': '合计',
  'scanAgain': '重新扫描',
  'addToTransactions': '加入交易',
  'scanNoTotal': '无法读取金额，请重新扫描。',
  'addedToTransactions': '已加入您的交易',
  'parsedByAi': 'AI',
  'parsedFallback': '演示',
  'scanFallbackWarning': '缺少 Gemini API key，或小票解析失败。请手动录入这笔交易。',
  'scanFallbackAction': 'AI 失败，手动录入',
  'savingsStoryLabel': '本月节省',
  'savingsStoryFooter': '基于 Uma 的 3 条建议',
  'savingsStoryDelta': '比上月少 {pct}%',
  'upcomingBills': '即将到期账单',
  'billPayViaUma': '通过 Uma 支付',
  'daysLeft': '剩余 {n} 天',
  'statementImport': '导入对账单',
  'statementImportTitle': '导入银行对账单',
  'statementImportSubtitle': '上传 PDF 或截图，AI 自动提取交易。',
  'pickStatementFile': '选择文件（PDF / 图片）',
  'statementImportHint': '银行可导出 PDF 对账单——无需开放银行接口，Vera 即可识别。',
  'statementParsing': 'AI 正在阅读对账单...',
  'closingBalance': '期末余额',
  'detectedTransactions': '识别到 {n} 笔交易',
  'statementImportAgain': '重新导入',
  'statementNoTransactions': '未能提取交易。',
  'statementImported': '已加入您的交易',
  'importToVera': '导入到 Vera',
  'statementFallbackWarning': '缺少 Gemini API key，或对账单解析失败。请手动录入这些交易。',
  'statementFallbackAction': 'AI 失败，手动录入',
  'thisMonthsAiPlan': '本月 AI 计划',
  'aiPlanFooter': 'Uma 建议——在您的银行执行，Vera 会记录结果。',
  'applyAtBank': '在我的银行执行',
  'securityVeraSideBanner': 'Vera 并非银行的安全层。它在您的数据中识别异常并提醒您；拦截由您和银行共同决定。',
  'statusAllClear': '一切正常',
  'statusMonitoring': '监控中',
  'securityRecentActivity': '近期活动',
  'securityScanning': '正在扫描...',
  'liveAnomalyDetected': '检测到异常',
  'highRiskConfidence': '高风险',
  'reviewedSignal': '已复核',
  'keepBlocked': '保持拦截',
  'thisWasMe': '这是我本人',
  'emailField': '电子邮箱',
  'passwordField': '密码',
  'loginDemoHint': '快速试用演示账户：邮箱 "{email}"，密码 "{password}"。',
  'umaVoiceStart': '语音提问',
  'umaVoiceStop': '停止录音',
  'umaVoiceListening': '正在听...',
  'umaVoicePermissionDenied': '需要麦克风权限。请在系统设置中为 Vera 启用麦克风。',
  'umaVoiceUnavailable': '此设备不支持语音识别。',
  'umaToolGoalCreated': '已完成。已为你创建 {target} TL 的目标。',
  'umaToolBillAdded': '已添加 {name} 账单，{days} 天后到期。',
  'umaToolExpenseAdded': '已记录支出：{name}（{amount} TL）。',
  'umaSuggestionSubs': '查看我的订阅',
  'umaSuggestionAnalyze': '分析我的消费',
  'voiceCommandTooltip': '语音指令',
  'umaAuditTrailTitle': '审计记录',
  'umaAuditTrailEmpty': '尚无签名的 Uma 操作。',
  'umaAuditTrailCount': '本设备已记录 {n} 个签名操作。',
  'accountTilePersonal': '个人信息',
  'accountTileEmail': '电子邮箱',
  'accountTileSecurity': '安全和 PIN',
  'accountTileStorage': '数据存储',
  'accountTileHelp': '帮助与支持',
  'accountTileHelpValue': '常见问题, 联系',
  'infoDisplayName': '显示名称',
  'infoMember': '会员',
  'infoMemberDescription': 'Vera 演示账号。后端接入后，这里将显示真实的注册日期和套餐。',
  'infoSignInMethod': '登录方式',
  'infoEmailLabel': '电子邮箱',
  'infoEmailUsage': '用途',
  'infoEmailDescription': '用于演示会话。数据保存在本地设备，不会上传到服务器。',
  'infoEmailDescriptionLive':
      '该地址用于 Firebase Auth 登录、账号恢复以及 Vera 的重要提醒。',
  'authMethodGoogle': '使用 Google 继续',
  'authMethodEmail': '邮箱和密码',
  'authMethodDemo': '演示保险库',
  'infoSessionVault': '会话保险箱',
  'infoSessionVaultDescription': '会话数据通过 flutter_secure_storage 加密，仅在本机存储。',
  'infoFaceId': 'Face ID',
  'infoFaceIdOn': '启用 · 登录时需要生物识别验证。',
  'infoFaceIdOff': '关闭 · 仅需密码 / 演示登录。',
  'infoFraudAlerts': '欺诈提醒',
  'infoFraudAlertsOn': '启用 · 检测到可疑活动时发送本地通知。',
  'infoFraudAlertsOff': '关闭 · 提醒仅在应用内显示。',
  'infoSyncMode': '同步模式',
  'infoLocalData': '本地数据',
  'infoLocalDataDescription':
      'OCR 收据和已添加的银行保存在 SharedPreferences。"导出数据"已列入 P1 计划。',
  'infoCloudSync': '云同步',
  'infoCloudSyncActive': '云同步已启用。导入的收据、对账单、银行、个人设置和交易可同步到你的 Vera 空间。',
  'infoCloudSyncInactive': '此会话未启用云同步；Vera 目前仅在本机运行。',
  'fraudAlertTitle': 'Vera • 已拦截可疑交易',
  'googleSignInConfigMissing':
      'Google 登录失败。应用的 SHA-1 指纹可能尚未在 Firebase Console 中注册。管理员需要更新 Firebase 设置。',
  'fraudReasonOutlier': '这笔支出是你近期中位数 {median} TL 的 {multiplier}×。Vera 觉得这跳跃值得关注。',
  'fraudNameRoundTransfer': '整数转账 · {amount} TL',
  'fraudReasonRoundTransfer': '发现一笔超过 10,000 TL 的整数金额。通常是给收款人的正常转账——若是你本人请确认。',
  'fraudNameBurst': '{merchant} · 同日 {count} 次',
  'fraudLocationBurstTotal': '合计 {total} TL',
  'fraudReasonBurst': '今天同一个商户记账 {count} 次。是刷卡重试还是真实购物？',
  'helpFaqQ1': 'Vera 会连接我的银行吗？',
  'helpFaqA1':
      '不会。Vera 没有 AISP/PSP 许可证。数据由你提供：PDF 账单、收据照片、截图或手动输入。Vera 用 AI 进行整合并把真实操作转发到你的银行 App。',
  'helpFaqQ2': '我的数据保存在哪里？',
  'helpFaqA2':
      '敏感会话信息存储于 flutter_secure_storage（设备端加密）。OCR 和银行记录存储于 SharedPreferences。无服务器，无第三方共享。',
  'helpFaqQ3': '没有 Gemini API key 会怎样？',
  'helpFaqA3':
      'OCR 和账单导入使用确定性回退（出现 DEMO 标签）。UMA 通过启发式意图路由器回复。整套流程仍可运行——仅关闭实时 AI 解析。',
  'helpContact': '联系',
  'demoUser': '演示用户',
  'umaThinking': 'Uma 思考中...',
  'umaAskHint': '问 Uma 任何事...',
  'umaStatusOnline': 'AI 助理 · 在线',
  'onbStep1Title': '欢迎来到 Vera',
  'onbStep1Subtitle': '先选择你要使用的语言。之后你随时都可以在设置中修改。',
  'onbStep2Title': '按你的方式来',
  'onbStep2Subtitle': '选择品牌配色和整体氛围。主题之后也可以调整。',
  'onbStep3Title': '导入你的数据',
  'onbStep3Subtitle': 'Vera 不会直接连接你的银行，而是由你带来对账单，Vera 帮你理解它们。现在开始，或稍后再添加。',
  'onbContinue': '继续',
  'onbStart': '开始使用 Vera',
  'onbSkip': '跳过',
  'onbBack': '返回',
  'onbImportNow': '导入对账单',
  'onbScanNow': '扫描小票',
  'onbContinueWithoutImport': '不导入，直接继续',
  'onbPalettePreviewTitle': '实时预览',
  'onbPalettePreviewBody': '你的选择会立刻反映到卡片、AI 高亮和整体视觉氛围上。',
  'onbBlankCanvasTitle': '空白开始也没问题',
  'onbBlankCanvasBody': '如果你愿意，现在可以先不导入任何内容继续；进入应用后 Vera 也会引导你的第一步。',
  'goalEmptyPrompt': '你还没有设定目标，点这里添加。',
  'goalEmptyHint': '先设定一个目标，然后让 Uma 按你的月度节奏估算每个月该留出多少。',
  'goalEmptyCta': '设定目标',
  'goalMonthsLabel': '计划用时',
  'goalMonthsOption': '{n} 个月',
  'goalAdviceSummary': '每月 {amount} · 共 {months} 个月',
  'goalCalculate': '计算',
  'goalPresetEmergency': '应急基金 (6个月) · {amount}',
  'goalPresetVacation': '度假 (3个月) · {amount}',
  'goalPresetCar': '买车 (12个月) · {amount}',
  'fieldName': '名称',
  'fieldAmountTl': '金额 (TL)',
  'fieldDate': '日期',
  'fieldCategory': '分类',
  'fieldDescription': '说明',
  'fieldLabelOptional': '标签（可选）',
  'actionAdd': '添加',
  'actionUpdate': '更新',
  'actionDelete': '删除',
  'actionManual': '手动',
  'addBillTitle': '新增账单',
  'editBillTitle': '编辑账单',
  'addBillNameHint': '例如 Turk Telekom',
  'dueDateLabel': '到期日',
  'addBillCta': '添加账单',
  'noTrackedBillsTitle': '还没有追踪中的账单',
  'noTrackedBillsBody': 'Vera 会在到期前一天提醒你。',
  'billKindCard': '卡片',
  'billKindInternet': '网络',
  'billKindElectric': '电费',
  'billKindWater': '水费',
  'billKindGas': '燃气',
  'billKindRent': '房租',
  'billKindOther': '其他',
  'addManualTxnTitle': '手动添加交易',
  'txnTypeExpense': '支出',
  'txnTypeIncome': '收入',
  'addManualTxnNameHint': '例如 Migros',
  'aiSuggestionLabel': 'Uma 建议',
  'acceptSuggestion': '接受',
  'categoryMarket': '商超',
  'categoryFood': '餐饮',
  'categoryFuel': '燃油',
  'categoryBill': '账单',
  'categoryHealth': '健康',
  'categoryEducation': '教育',
  'categoryEntertainment': '娱乐',
  'categoryTransfer': '转账',
  'categorySalary': '工资',
  'categorySubscription': '订阅',
  'categoryMusic': '音乐',
  'categoryVideo': '视频',
  'categoryStorage': '存储',
  'categoryDeveloper': '开发者',
  'categoryAi': 'AI',
  'noTransactionsTitle': '还没有交易',
  'noTransactionsBody': '添加第一笔交易、导入对账单，或扫描一张小票。',
  'addHoldingTitle': '向投资组合添加资产',
  'addHoldingSubtitle': '从下方选择一种资产类型并输入其 TL 价值。Uma 会自动重新计算权重。',
  'addHoldingHint': '例如 THYAO 或 XU100 ETF',
  'holdingValueLabel': '价值 (TL)',
  'removeHolding': '移除此资产',
  'noWealthActionsTitle': 'Uma 还没有采取动作',
  'noWealthActionsBody': '启用自动模式后，建议和再平衡动作会显示在这里。',
  'startPortfolioTitle': '开始建立你的投资组合',
  'startPortfolioBody': '添加股票、黄金、现金或加密资产。Uma 会跟踪偏离并在这里给出建议。',
  'wealthApprovalAuto': '自动',
  'wealthApprovalHybrid': '混合',
  'wealthActionReversed': '已撤销',
  'holdingBucketEquity': '股票',
  'holdingBucketGold': '黄金',
  'holdingBucketCash': '现金',
  'holdingBucketCrypto': '加密',
  'holdingBucketFunds': '基金',
  'holdingBucketBonds': '债券',
  'subscriptionsAttentionCount': '本周期有 {n} 个计划需要关注',
  'noSubscriptionsDetectedTitle': '还没有检测到订阅',
  'noSubscriptionsDetectedBody': '导入对账单或扫描小票，Vera 会自动识别重复付款。',
  'noSubscriptionsForFilterTitle': '没有符合该筛选条件的订阅',
  'noSubscriptionsForFilterBody': '试试其他筛选条件。',
  'subsAlertSavingsTitle': '每月节省潜力',
  'subsAlertSavingsMessageEmpty': '还没有检测到订阅。导入对账单或手动添加后，Vera 就会开始跟踪。',
  'subsAlertSavingsMessageActive': 'Vera 找到了可以在不打乱你日常的情况下冻结或降级的订阅。',
  'subsAlertSavingsMetric': '节省',
  'subsAlertPriceTitle': '检测到价格上涨',
  'subsAlertPriceMessageNone': '本周期没有异常的价格跳涨。',
  'subsAlertPriceMessageSome': '一个或多个计划的价格较上月上涨了。',
  'subsAlertPriceMetric': '上涨',
  'subsAlertUnusedTitle': '低使用计划',
  'subsAlertUnusedMessageNone': '所有订阅看起来都很健康。',
  'subsAlertUnusedMessageSome': '根据你最近的活动模式，有 {n} 个计划看起来使用较少。',
  'subsAlertUnusedMetric': '闲置',
  'subsInsightEmpty': 'Vera 会分析你的对账单或小票，并把订阅整理到这里。',
  'subsInsightHealthy': '你的订阅本月看起来很健康，没有明显的紧急节省漏洞。',
  'subsInsightNeedsAttention':
      '你有 {n} 个订阅值得复查。Vera 估计，通过冻结不使用的订阅并将更贵的计划降级，你每月大约可以回收 {amount}。',
  'subsDetectedFromImport': '从导入交易中检测到',
  'subsSeenInRecentTransactions': '最近交易中出现了 {n} 次',
  'subsKnownVendorLabel': '已知订阅商户',
  'subsRecommendationDetected': 'Vera 从导入的对账单中检测到这项订阅。你现在还在使用它吗？',
  'subsStatusActive': '活跃',
  'subsStatusPriceUp': '涨价',
  'subsStatusUnused': '低使用',
  'subsStatusRenewsSoon': '即将续费',
  'proactiveBadge': 'VERA 发现了',
  'proactiveBillTitle': '{name} 账单快到了',
  'proactiveBillBody': '{amount} · 还剩 {days} 天。要让 Uma 帮你准备付款计划吗？',
  'proactiveBillCta': '通过 Uma 支付',
  'proactiveBillPrompt': '帮我支付 {name} 账单。',
  'proactivePriceTitle': '{name} 涨价了',
  'proactivePriceBody': '每月增加 +{delta}。要冻结这项订阅吗？',
  'proactivePriceCta': '查看订阅',
  'proactiveUnusedTitle': '{name} 使用率很低',
  'proactiveUnusedBody': '最近一次使用：{last}。这可能是一笔安静流失的钱。',
  'proactiveUnusedCta': '查看订阅',
  'proactiveHealthyTitle': '当前没有关键风险信号',
  'proactiveHealthyBody': '目前没有紧急账单、价格突增或明显浪费的订阅。如果你愿意，Uma 仍然可以快速解读这一阶段。',
  'proactiveHealthyCta': '让 Uma 看看',
  'proactiveEmptyTitle': 'Vera 还没有发现需要关注的信号',
  'proactiveEmptyBody': '导入一份对账单后，Vera 会在这里突出显示即将到来的付款、订阅和小风险。',
  'proactiveEmptyCta': '导入对账单',
  'securityEmptyTitle': '目前没有需要查看的提醒',
  'securityEmptyBody': 'Vera 的欺诈雷达会静默监控你的设备和导入交易。一旦有异常，就会显示在这里。',
  'close': '关闭',
  'categoryOther': '其他',
  'receiptDefaultName': '收据',
  'wealthInsightAddPortfolio': '自治模式已关闭。添加你的投资组合，Uma 才能跟踪偏离并给出建议。',
  'wealthInsightPaused': '自治模式已暂停。Vera 仍在监控偏离，但在动用资金前会等待你的确认。',
  'wealthInsightActive':
      'Uma 正在以"{profile}"策略运行。在每月 {limit} TL 限额内，已完成或准备 {count} 项投资组合调整。',
  'goalReached': '你已达成目标，可以设定一个新目标。',
  'goalRemainingPlan':
      '若要在 {months} 个月内存满剩余 {remaining} TL，每月需要预留 {monthly} TL。',
  'goalNarrativeNewTarget': '可以为你的目标设定一个新金额。',
  'goalNarrativeNoData': '还没有交易数据。导入对账单或手动添加几笔记录，Uma 就能为你定制计划。',
  'goalNarrativeTrim': '你需要每月预留 {monthly} TL。从 {topCategory} 预算上做小幅削减是一个合理的起点。',
  'todayAt': '今天，{time}',
  'loginContinueEmail': '使用邮箱继续',
  'loginEmailPasswordRequired': '邮箱和密码必填。',
  'loginFirebaseError': 'Firebase 登录失败：{code}。',
  'loginFirebaseReadyFooter': 'Firebase auth 已连接。Demo 模式仍可用于 hackathon 流程。',
  'loginCreateAccount': '创建账户',
  'dividerOr': '或',
  'signupTitle': '创建你的账户',
  'signupSubtitleFirebase': '创建账户——你的 Vera 资料和数据将安全同步。',
  'signupSubtitleLocal': '未配置服务器。流程将在本机以演示模式继续。',
  'signupFieldFullName': '全名',
  'signupFieldEmail': '邮箱',
  'signupFieldPassword': '密码',
  'signupFieldConfirmPassword': '确认密码',
  'signupErrorNameRequired': '请输入你的全名。',
  'signupErrorInvalidEmail': '请输入有效的邮箱。',
  'signupErrorShortPassword': '密码至少 6 个字符。',
  'signupErrorPasswordMismatch': '两次输入的密码不一致。',
  'signupErrorAcceptTerms': '请同意条款以继续。',
  'signupFailedTemplate': '账户创建失败：{code}。',
  'signupTerms': '我接受 Vera 条款和本地演示数据政策。',
  'signupStrengthWeak': '弱',
  'signupStrengthMedium': '中',
  'signupStrengthStrong': '强',
  'signupCtaCreate': '注册',
  'signupCtaContinueLocal': '以演示继续',
  'signupAlreadyHaveAccount': '已有账户？',
  'signupSignIn': '登录',
  'demoSampleLoaded': '示例账户数据已加载。',
  'demoBankPrimary': 'Vera 银行 — 活期',
  'demoBankSavings': 'Vera 银行 — 储蓄',
  'demoBillCreditCard': '信用卡账单',
  'demoBillElectric': '电费账单',
  'demoBillInternet': '宽带账单',
  'demoTxnSalary': '工资发放',
  'demoTxnGrocery': '超市购物',
  'demoTxnFuel': '加油',
  'demoTxnRestaurant': '餐厅',
  'demoTxnPharmacy': '药房',
  'demoTxnRent': '房租支付',
  'demoTxnTransfer': '转账 — 储蓄账户',
  'demoTxnFamilyIncoming': '入账转账 — 家人',
  'demoTxnAtm': 'ATM 取现',
  'deleteAccount': '删除账户',
  'deleteAccountTile': '删除账户',
  'deleteAccountTileValue': '移除云端数据并退出登录',
  'deleteAccountDemoTileValue': '清除此设备上的演示数据',
  'deleteAccountTitle': '要删除此账户吗？',
  'deleteAccountBody': '你的 Vera 账户、已同步数据以及此设备上的本地缓存都会被永久删除。此操作无法撤销。',
  'deleteAccountDemoBody': '这将清除演示账户并移除此设备上的本地数据。此操作无法撤销。',
  'deleteAccountConfirm': '删除账户',
  'deleteAccountCancel': '取消',
  'deleteAccountProcessing': '正在删除账户...',
  'deleteAccountDone': '账户已删除。',
  'deleteAccountError': '删除账户失败。请重新登录后再试。',
  'deleteAccountRecentLogin': '出于安全考虑，请先重新登录再删除账户。',
  'continueWithGoogle': '使用 Google 继续',
  'googleSignInUnavailable': '此构建版本需要先配置 Firebase 才能使用 Google 登录。',
  'bankActionsTitle': '银行选项',
  'bankActionsCancel': '取消',
  'bankActionsDelete': '删除银行',
  'bankActionsConfirmTitle': '删除此银行？',
  'bankActionsConfirmBody': '{name} 将被移除，并不再计入总余额。',
  'bankDeleted': '已删除 {name}',
  'bankActionsFeedNote': '此银行随演示数据预置，无法删除。可以删除你自己添加的银行。',
  'billDetailPrompt': '我的 {name} 账单是 {amount}，还剩 {days} 天。我该怎么做？',
  'categoryBudgetLabel': '本月消费',
  'categoryBudgetTopHint': '{category} 最多 · {pct}%',
  'categoryLimitEditTitle': '类别预算',
  'categoryLimitEditSubtitle': '为 {category} 设定月度预算，Vera 会在每笔消费时显示剩余额度。',
  'categoryLimitField': '月度上限（TL）',
  'categoryLimitSave': '保存',
  'categoryLimitClear': '取消预算',
  'categoryNoLimit': '未设上限',
  'categoryOver': '超出 {amount}',
  'categoryRemaining': '剩 {amount}',
  'creditFieldDebt': '现有月供',
  'creditFieldIncome': '每月收入',
  'creditFieldLoanAmount': '贷款金额',
  'creditFieldTerm': '期限',
  'creditLoanSimulation': '贷款计算器',
  'creditLoanSimulationSubtitle': '调整数值——月供和债务比例实时计算。',
  'creditScoreDisclaimer':
      '此页面不计算信用评分。真实信用评分请咨询你的银行或征信机构。这里仅根据你输入的数值显示大致的月供和债务比例。',
  'creditTermMonths': '{n} 个月',
  'creditResultMonthlyPayment': '预估每月还款',
  'creditResultTotalCost': '总还款额',
  'creditResultPaymentLoad': '月供 / 收入',
  'creditResultDtiAfter': '新的债务收入比',
  'creditResultGuidance':
      '银行通常希望债务收入比低于 35%。超过 40% 会限制可选方案。仅供规划参考。',
  'demoResetTile': '重置演示数据',
  'demoResetTileValue': '清除导入和添加项',
  'demoResetTitle': '重置演示数据？',
  'demoResetBody': '已导入的交易、你添加的银行和目标进度都会回到初始状态。',
  'demoResetCancel': '取消',
  'demoResetConfirm': '重置',
  'demoResetDone': '已回到演示状态',
  'exportTile': '导出我的数据',
  'exportTileValue': 'JSON · 仅本机',
  'exportTitle': '你的 Vera 数据',
  'exportSubtitle': '已导入的交易、你添加的银行、目标和检测到的订阅。无需离开设备即可复制。',
  'exportCopy': '复制 JSON',
  'exportCopied': '已复制到剪贴板',
  'firstScanPending': '等待首次扫描',
  'firstSyncPending': '等待首次同步',
  'goalEditTitle': '编辑你的目标',
  'goalEditTarget': '目标金额（TL）',
  'goalEditSaved': '已存（TL）',
  'goalEditFooter': 'Vera 跟踪余额；Uma 每月给你一个新提醒。',
  'goalEditSave': '保存',
  'goalEmergencyFund': '应急储备金',
  'goalEtaMonths': '还需 {n} 个月',
  'goalEtaReached': '已达成 🎯',
  'goalProgress': '已达 {pct}%',
  'goalRemaining': '还差 {amount}',
  'goalsSectionTitle': '你的目标',
  'lastScanAt': '上次扫描 {time}',
  'loginTitle': '登录 Vera',
  'loginSubtitle': '使用你的账号登录；个人偏好和 AI 操作在退出之前保存在本机。',
  'loginEmailHint': 'you@vera.app',
  'loginFooter': '若未配置 Firebase，登录会失败。请检查 .env 文件。',
  'notifTitle': '通知',
  'notifSubtitle': '{n} 条 Uma 正在关注',
  'notifEmpty': '一切平静。Uma 仍在悄悄关注。',
  'notifBillTitle': '{name} 账单临近',
  'notifBillBody': '金额 {amount}。通过 Uma 或你的银行支付。',
  'notifPriceIncreaseTitle': '{name} 上调了价格',
  'notifPriceIncreaseBody': '每月 +{delta} · 现 {price}。可在"订阅"中冻结。',
  'notifUnusedTitle': '{name} 几乎未用',
  'notifUnusedBody': '最近使用：{last}。Vera 把它标记为"沉默支出"。',
  'notifBlockedDefault': 'Vera 把这笔交易标记为异常。',
  'profileAiToneBadge': 'AI 风格 / {tone}',
  'profileAutoApprove': '自动批准上限',
  'profileAutoApproveOff': '关闭',
  'profileConnectedTitle': '已连接 {n} 家机构',
  'profileConnectedSubtitle': '实时余额按当前同步策略和数据缓存刷新。',
  'profileConnectedAccount': '账户 {last4}',
  'profileDailyBriefing': '每日 AI 简报',
  'profileDailyBriefingSub': '用账户状态、可疑活动和储蓄提示开启一天',
  'profileFaceId': 'Face ID 重新解锁',
  'profileFaceIdSub': '敏感操作前需要生物识别解锁',
  'profileFraudHigh': '高敏感度欺诈提醒',
  'profileFraudHighSub': '让 Vera 更早标记异常的设备和支付模式',
  'profileLiveSync': '实时数据同步',
  'profileLiveSyncLive': '实时',
  'profileLiveSyncBalanced': '平衡',
  'profileLiveSyncSaver': '省电',
  'profileSmartNotif': '智能通知',
  'profileSmartNotifSub': '欺诈、续订和审批变更提醒',
  'profileVaultTitle': '受保护的会话存储',
  'profileVaultSubtitle': '身份与本机偏好分开持久化保存。',
  'profileVaultSignIn': '登录',
  'profileVaultProtectedSince': '保护起始',
  'profileVaultThisDevice': '此设备',
  'profileVaultApproval': '审批护栏',
  'profileVaultManualOnly': '仅手动',
  'profileVaultSyncMode': '同步模式',
  'profileVaultSyncLive': '实时同步',
  'profileVaultSyncBalanced': '平衡同步',
  'profileVaultSyncSaver': '省电同步',
  'securityAccountSection': '账户安全',
  'securityActiveBody': 'Fraud Radar 正在跟踪 {n} 条活动提醒。',
  'securityClearBody': '最近一次扫描没有未处理的欺诈提醒。',
  'securityPillBlocked': 'AI 已拦截',
  'securityPillApproved': '你已批准',
  'securityPillKept': '保持拦截',
  'securityDecisionKept': '你保持了此事件的拦截。Fraud Radar 会继续把类似模式视为高风险。',
  'securityDecisionApproved': '你将此事件标为安全。Fraud Radar 会用这一反馈减少类似的误报。',
  'securityStatBlockedLabel': '已拦截',
  'securityStatBlockedSub': '生效',
  'securityStatReviewedLabel': '已复核',
  'securityStatReviewedSub': '本周',
  'securityStatDevicesLabel': '设备',
  'securityStatDevicesSub': '可信',
  'securityViewReport': '查看 UMA 报告',
  'subsRenewalLabel': '续订',
  'subsActivityLabel': '活动',
  'txnDetailWhen': '时间',
  'txnDetailCategory': '类别',
  'txnDetailDirection': '方向',
  'txnDetailIncoming': '收入',
  'txnDetailOutgoing': '支出',
  'txnDetailAskPrompt': '看一下 {name} 这笔交易——{amount} 算正常吗？',
  'umaAuditTrailSubtitle': 'Uma 在本机的回复签名日志。',
  'umaAuditTrailEmptyState': '尚无签名记录。与 Uma 对话后会出现在这里。',
  'umaAuditNoteAttached': '已附备注',
  'umaAuditActionReplyGenerated': '已生成回复',
  'umaGreeting':
      '你好 {name}。我读过你导入的对账单。我可以分析你的消费、找出闲置的订阅，并帮你设定储蓄目标。我不会动用资金——需要操作时会引导你到银行 App。',
  'umaPromptAnalyze': '分析我这个月的消费。',
  'umaReplyAnalyze': '本月最大支出是 {top}，共 {topAmount}。总流出 {spending}。需要的话可以按类别设置上限。',
  'umaReplyAnalyzeEmpty': '还没有可分析的交易。扫描收据或导入对账单，我们就能一起细看消费。',
  'umaReplyExplainWealth': 'Vera 通过你导入的账户跟踪投资组合。本月权益略微超配，建议下次打开银行时补充黄金或现金。',
  'umaReplyLoan': '从你导入的对账单看，收入与负债都不错，适合中等规模的个人贷款。打开信贷模拟，我可以帮你调到更稳妥的金额和期限。',
  'umaReplySecurity': '我标记了那笔转账，因为收款人之前只出现过一次，且设备位置与你的常规模式不匹配。Vera 不会在银行端拦截——它会提醒你，最终由你决定。',
  'umaReplySubscriptions': '你有 {n} 项值得复核的计划。月度订阅总额约 {total}。',
  'umaReplySubscriptionsEmpty': '我暂时没看到活跃订阅。导入一份对账单，Vera 会识别周期性扣款。',
  'umaReplyFallback': '可以帮你做这个。如果愿意，我可以给一个简短的财务读取，或者准备一个安全的下一步。',
  'updatedAt': '已更新 {time}',
};
