/// Estimated loan offer from a specific Turkish bank. The numbers are
/// generated by Gemini using its general knowledge of publicly advertised
/// consumer-loan rates — they are guidance, never a real quote.
class BankLoanOffer {
  const BankLoanOffer({
    required this.bankName,
    required this.estimatedApr,
    required this.monthlyPayment,
    required this.totalCost,
    this.note = '',
  });

  /// Display name of the bank (e.g. "Ziraat Bankası").
  final String bankName;

  /// Estimated annual percentage rate, 0..1 (0.45 = 45% APR).
  final double estimatedApr;

  /// Estimated monthly installment in TL.
  final double monthlyPayment;

  /// Total amount paid over the loan term in TL.
  final double totalCost;

  /// Short qualifier — e.g. "Maaş müşterilerine özel", "İlk kredi promosyonu".
  final String note;

  factory BankLoanOffer.fromJson(Map<String, dynamic> json) {
    double parseDouble(Object? value) {
      if (value is num) return value.toDouble();
      if (value is String) {
        final cleaned = value
            .replaceAll('%', '')
            .replaceAll('TL', '')
            .replaceAll(',', '.')
            .trim();
        return double.tryParse(cleaned) ?? 0;
      }
      return 0;
    }

    var apr = parseDouble(json['estimatedApr'] ?? json['apr']);
    if (apr > 5) apr = apr / 100; // model returned a percentage, normalize.

    return BankLoanOffer(
      bankName: (json['bankName'] as String? ?? '').trim(),
      estimatedApr: apr,
      monthlyPayment: parseDouble(json['monthlyPayment']),
      totalCost: parseDouble(json['totalCost']),
      note: (json['note'] as String? ?? '').trim(),
    );
  }
}

/// Aggregate credit insight: an estimated Findeks-style score band and the
/// per-bank loan offers we surface in the Credit tab.
class CreditEstimate {
  const CreditEstimate({
    required this.score,
    required this.band,
    required this.summary,
    required this.offers,
  });

  /// 0..1900 Findeks-style score (informational only).
  final int score;

  /// Localized band label ("Düşük", "Orta", "İyi", "Çok İyi") returned by
  /// Gemini in the active UI language.
  final String band;

  /// One-sentence rationale Gemini provides to explain the estimate.
  final String summary;

  final List<BankLoanOffer> offers;

  factory CreditEstimate.fromJson(Map<String, dynamic> json) {
    final rawOffers = (json['offers'] as List? ?? const [])
        .whereType<Map>()
        .map((e) => BankLoanOffer.fromJson(Map<String, dynamic>.from(e)))
        .where((offer) => offer.bankName.isNotEmpty)
        .toList();
    final score = json['score'];
    return CreditEstimate(
      score: score is num ? score.toInt() : 0,
      band: (json['band'] as String? ?? '').trim(),
      summary: (json['summary'] as String? ?? '').trim(),
      offers: rawOffers,
    );
  }
}
